### ISSUE TITLE
sim name doesn't match "Basics" convention

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gravity-force-lab-basics#1]
Current sim title is "Gravity Force Lab Basics".  Shouldn't it be "Gravity Force Lab: Basics", to be consistent with other "Basics" sims?  I.e. "Forces and Motion: Basics", "Energy Skate Park: Basics", "Molecule Shapes: Basics", ...

**Comment by pixelzoom** [comment]
Assigning to @jbphet since he created the entry in gravity-force-lab-basics-strings_en.json.

**Comment by pixelzoom** [comment]
I went ahead and fixed this. @jbphet please review.

**Comment by jbphet** [comment]
Looks good to me - thanks. Closing.
