### ISSUE TITLE
new sonification link needed for interviews

### ISSUE THREAD

**Issue by zepumph** [phetsims/gravity-force-lab-basics#104]
This will use GFLB dev.33

This will include work done in #94 #101 #100 #103 #98 and #95.

**Comment by zepumph** [comment]
https://phet-dev.colorado.edu/html/phet-io-wrapper-sonification/1.0.0-dev.104/phet-io-wrapper-sonification/sonification.html

https://phet-dev.colorado.edu/html/phet-io-wrapper-sonification/1.0.0-dev.104/phet-io-wrapper-sonification/gravity-force-lab-basics/html/gravity-force-lab-basics-sonification.html?sonificationFile=sonificationOptions&massSound=0&forceSound=3&massBoundaryLimitSound=2&accessibility

Over to you @terracoda.

**Comment by terracoda** [comment]
Taggin @kainip to see if I can.

**Comment by terracoda** [comment]
Closing since interviews have happened. Hopefully, we will have anew version ready soon for a next round of interviews.
