### ISSUE TITLE
Mass descriptions: Toggle to comparative density descriptions when Constant Size is checked

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#106]
Related to new scales in #96,  Mass descriptions in the PDOM will need to toggle from comparative mass size to comparative density when the Constant Size checkbox is checked.

@terracoda to add screen shot of A11y View with necessary changes.

**Comment by terracoda** [comment]
@zepumph, as discussed in our meeting Mar 5th/6th here is a screen shot of the A11y View where size descriptions need to toggle to density when the Constant Size checkbox is checked.

Note the help text for the mass stepper controls is already toggling, so there are just 2 updates. And the `aria-valuetext` for the mass steppers will be handled by other issues (#96 and https://github.com/phetsims/scenery/issues/951).

<img width="1226" alt="state-of-sim-size-density" src="https://user-images.githubusercontent.com/1902116/53860769-60297800-3fe2-11e9-85f8-4048b59cdcac.png">

**Comment by zepumph** [comment]
#96 covered everything except the first item in the screenshot: 

"Currently, force on mass1 by mass 2 is of equal size . . . . "

I'll look at that first.

**Comment by zepumph** [comment]
@terracoda, I totally trust your design, but I wonder if this isn't a mistake. To me here "equal size" is referring to the size of the force arrows, not the size of the masses. Are we sure that when the constant radius checkbox is checked we want it to read

"Currently, force on mass 1 by mass 2 is of equal density and pointing directly opposite to the force on mass 2 by mass 1."

**Comment by terracoda** [comment]
@zepumph good catch - that is indeed a mistake. I just saw the word size and flagged it. Apologies. That is indeed the force and does not toggle with the checkbox!! :-P

**Comment by zepumph** [comment]
Not a worry! In that case I think these were all implemented by #96 or prior to my work in the repo. Is there anything else left to change here in the PDOM?

**Comment by terracoda** [comment]
@zepumph, I'll close this issue when I verify #96, thanks!
