### ISSUE TITLE
Position slider's verbose aria-valuetext: describe position instead of providing a kilometer mark

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#107]
With some indication from interviews...Providing both the kilometer mark and distance from other sphere on focus of a mass position slider may not be super helpful.

The values together seem to be a bit of information/number overload, and it is not clear to @terracoda if the kilometer mark value is of much importance to the the learning goals of the simulation. Initial thinking was that the kilometer mark could provide some orientation of where the sphere is positioned along the invisible track of the slider.

**Questions:** 
- Is position along track at all useful? If so, perhaps a described position would be better? 
- Would it be better to just focus on distance throughout the entire position interaction (from focus to change of focus)?
- It might be much more useful to include some wording that makes it clear that the distance provided is the "distance between centers of spheres" in the more verbose `aria-valuetext` provided on focus.

**Note** that a dynamic verbose value for `aria-valuetext` is dependent on https://github.com/phetsims/scenery/issues/951

**Note** that examples do not include the brief focus alert describing the size of the force arrows.

**Currently, verbose `aria-valuetext` provides:**
With Distance checked kilometer mark and distance in kilometers:
- 2.8 kilometer mark, 4 kilometers from ‪mass 2‬, mass 1 position slider.

With Distance NOT checked kilometer mark and described relative distance:
- 2.8 kilometer mark, close to ‪mass 2‬, mass 1 position slider.

**Initial idea for a change to the verbose `aria-valuetext`**
**Option 1: Remove positioning along track all together and add "center" somewhere**
With Distance checked, distance in kilometers:
- 4 kilometers from ‪center of mass 2‬‬, mass 1 position slider
- 4 kilometers from ‪mass 2‬‬'s center, mass 1 position slider
- mass 1's center, 4 kilometers from mass 2's center‬‬, mass 1 position slider

With Distance NOT checked, described relative distance:
- Close to center of ‪mass 2‬‬, mass 1 position slider
- Close to ‪mass 2's center‬‬, mass 1 position slider
- mass 1's center, close to ‪mass 2's, mass 1 position slider

**Option 2: If position is needed, describe position on track instead**
With Distance checked, distance in kilometers:
- On left side of track, center 4 kilometers from ‪center of mass 2‬, mass 1 position slider.
- On left side of track, center 4 kilometers from ‪mass 2's, mass 1 position slider.
- On left side of track, mass 1's center, 4 kilometers from ‪mass 2's‬, mass 1 position slider. 

With Distance NOT checked, described relative distance:
- On left side of track, close to center of ‪mass 2‬, mass 1 position slider. 
- On left side of track, center close to mass 2‬'s , mass 1 position slider.
- On left side of track, mass 1's center, close to mass 2's‬, mass 1 position slider

If described position in Option 2 is needed, possible descriptions for track position could be:
- On left side of track
- On right side of track
- Halfway along track (May not be needed. Could just not describe this position all.)

We already have 3 position landmarks implemented:
- Left edge (0 kilometer mark)
- Right edge (9.6 kilometer mark)
- Last stop (when spheres can't get any closer together)

Edited: Change number of interviews.

**Comment by terracoda** [comment]
@emily-phet, do you see what I am trying to do with these descriptions? 
1. Do you think we need to provide position at all?
2. If so, do you think any of the drafted example values might be better than using "kilometer mark"?
3. Do you have a preference any of the phrases that describe the centers between the spheres?

**Comment by terracoda** [comment]
Feedback from March 12th Design Meeting:

1. Do you think we need to provide position at all?
- Note ready to drop position all together, so go with describe position.
2. If so, do you think any of the drafted example values might be better than using "kilometer mark"?
- Do not need to include center.
3. Do you have a preference any of the phrases that describe the centers between the spheres?
- Do not need to include center.

**Comment by terracoda** [comment]
@terracoda to update design document examples and walkthrough with new phrases for position and distance.
- [ ] examples updated
- [ ] walkthrough updated

**Note** that having different (more versbose) `aria-valuetext` on focus is dependent on phetsims/scenery#951.

**Comment by terracoda** [comment]
@zepumph, I removed "describe center explicitly" from title as we decided not to consider doing that.

**Comment by terracoda** [comment]
I have a couple options for the phrasing to discuss at Tuesday's GFLB design meeting, so marking as a meeting issue one last time before implementation.

**Comment by terracoda** [comment]
@zepumph, I've got all position/distance changes updated in the design document and will be assigning things over to you after Tuesday's design meeting when I clarify the wording on a couple of phrases.

**Comment by terracoda** [comment]
Marking as high priority in case it is possible to get these changes in for interviews in the later half of next week.

**Comment by terracoda** [comment]
@zepumph, https://github.com/phetsims/gravity-force-lab-basics/issues/107#issuecomment-478736118 is basically contains three tasks that all intermingled:

Task 1: Replace all strings that contain kilometer marks (position value) with one of the new described position regions or landmarks. All together there are about 6 described position values which are laid out the [Table: Position Regions & Landmarks](https://docs.google.com/document/d/1HdDG9ds2MdbCb21l9qk3cI8yBQxK6-wBWNXC4Tloji8/edit#heading=h.k9vtfb4kzkmi):
- Left side of track
- Right side of track
- Last stop right (mass 1 only)
- Last stop left (mass 2 only)
- Track end left (mass 1 only)
- Track end right (mass 2 only)

Task 2: Adjust `aria-valuetext` on focus for the mass position sliders
- Examples are in the [Table: Focus events for Move mass 1 slider](https://docs.google.com/document/d/1HdDG9ds2MdbCb21l9qk3cI8yBQxK6-wBWNXC4Tloji8/edit#heading=h.etekga3uwpzz)

Task 3: Use the Cognitive walk-through as a guide to update `aria-valuetext` and alerts provided during interaction with the Move mass sliders
- See [Cognitive Walkthrough](https://docs.google.com/document/d/1HdDG9ds2MdbCb21l9qk3cI8yBQxK6-wBWNXC4Tloji8/edit#heading=h.ty8avmawwxa)

I hope that makes things more clear. I can make 3 issues if yo would prefer. Apologies for the mega-issue.

**Comment by zepumph** [comment]
@terracoda hopefully a lot/most of this is accomplished. Like you predicted, I was able to simplify quite a bit of logic in PositionDescriber, because the "edge cases" are built into the main value text generating function. I don't think this is without quirks and bugs, but I walked through the walkthrough, only looking at the white rows (with distance checked), and things are looking pretty nice! 

I'm excited to talk tonight.

**Comment by terracoda** [comment]
@zepumph, the white rows work perfectly!
aria-valuetextFocus values

The grey rows where we are to get described regions for position rather than actual distance in kilometers are working a bit erratically.

I do not get the region name on every step.

What I would like is:
Step 1: Progress 
**Issues:**

**Comment by terracoda** [comment]
Oops did not mean to post - will edit previous comment.

**Comment by terracoda** [comment]
@zepumph, I significantly updated https://github.com/phetsims/gravity-force-lab-basics/issues/107#issuecomment-479346050.

**Comment by terracoda** [comment]
And will start a new issue for Task 3 (with Distance not checked).
