### ISSUE TITLE
Mass descriptions: Not hearing value in billions of kilograms (aria-valuetext) on a mass change

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#109]
@zepumph, I hear the mass alert on a mass change with no new mass value.

I would expect to hear both the new mass value and the mass alert.

I am wondering if this a bug, or perhaps it is related to your comment https://github.com/phetsims/gravity-force-lab-basics/issues/96#issuecomment-469423271 in issue #96.

I am marking this issue as a question.

**Comment by terracoda** [comment]
For reference, the pattern for changing mass/density is found in the [Changing mass alerts](https://docs.google.com/document/d/1HdDG9ds2MdbCb21l9qk3cI8yBQxK6-wBWNXC4Tloji8/edit#heading=h.ce5d7rlnapb8) section in the design doc.

**Comment by terracoda** [comment]
@zepumph FYI, this issue is related to #105.

**Comment by terracoda** [comment]
@zepumph, more specifically this issue is related to https://github.com/phetsims/gravity-force-lab-basics/issues/105#issue-417549739 and Changing mass alerts in the design doc.

I have just marked #105 as high priority, so I will mark this one the same. I think you might work on these 2 issues together.

**Comment by zepumph** [comment]
To make sure we are on the same page, I understand it as the "mass value" being delivered with aria-valuetext, and the "mass alert" through aria-live. 

You said you get and alert and no value "on a mass change"

The only way I can reproduce this is if I use a mouse to adjust the mass controls. I would expect aria-valuetext to not be read out when using a mouse, since the PDOM element won't have focus then.

@terracoda can you specify if/how you are able to reproduce this with a keyboard, or how I should proceed.

It is possible that I'm witnessing different logic than you are because of work done in #96, (though I don't think it is really likely a culprit of inconsistency).

**Comment by terracoda** [comment]
@zepumph, yes, using VoiceOver, Safari and either my bluethooth keyboard or my laptop keyboard I do not hear the value changes in `aria-valuetext` on the steppers. I only hear the aria-live force alerts.

I would expect to hear the new value in the `aria-valuetext` for billions of kilograms before the force alert each time I press the up or down arrow keys and the left or right arrow keys.

Could it be a problem with the stepper? The sliders in this sim and in other sims like RIAW work fine and provide the `aria-valuetext` and their companion alert.

**Comment by zepumph** [comment]
@KatieWoe agreed to take a look with me on a mac device. We were able to reproduce the issue from master. Then I committed a potential fix above, and found that things didn't work any better. Thanks for your help @KatieWoe.

The above commit seems like a good change even if it doesn't fix this. Before this the REGULAR and BASICS mass controls had different ways of setting the on value change aria value text. That was unnecessary, so I aligned the implementations to both use the onChange value text creator.

**Comment by zepumph** [comment]
@chrisklus also agreed to help out with some pairing. We messed around with his working copy for about 90 minutes and settled on https://github.com/phetsims/sun/issues/497 as the culprit. Here are all the factors we looked into that didn't have any effect on voiceover speaking the value text on value change:

* changing the label
* omitting the valuenow attribute
* short circuiting the mass describer function and just setting the valuetext to a string+random number
* looking at the on focus aria value text (which is working as expected)
* looking at the `a11yUseTimer` in AccessibleNumberSpinner

@terracoda time for a stupid question. Has this ever worked? Or was this working as expected until just a few weeks ago when I messed with how aria-valuetext was implemented in https://github.com/phetsims/gravity-force-lab-basics/issues/107 and https://github.com/phetsims/scenery/issues/951.

**Comment by terracoda** [comment]
@zepumph, if my memory is correct, I think that once the once the force alerts were added (As mass gets bigger, force arrows get bigger), that the billions of kilograms stopped working. That was quite a few versions ago, and I am not 100% sure exactly when the mass amounts stopped.

I'll look at this more as soon as possible. Thanks for all the hard work investigating the issue.

**Comment by zepumph** [comment]
this should be fixed by work in https://github.com/phetsims/sun/issues/497. Marking on hold to confirm once that issue is taken care of.

**Comment by zepumph** [comment]
@terracoda I'm curious if this is fixed now. Can you confirm? In https://github.com/phetsims/sun/issues/497 we redesigned the number spinner HTML. There is still work to do to make sure that we have the best component possible, but does the current version have working aria-valuetext and does the other logic still work?

**Comment by terracoda** [comment]
I'll check as soon as I can.

**Comment by terracoda** [comment]
A value is being read out, but the value is not `aria-valuetext`.
I hear the verbose `aria-valuetext` on focus and then I hear "3000000000", "4000000000", etc when I change the value. VoiceOver is reading out the value by digit, "three zero zero zero zero zero..." 

Short answer, no, it's not working.

I GFL Regular, it works fine, but the mass control there is a slider, not a number spinner.

**Comment by terracoda** [comment]
Just adding my GFLB comment here from phetsims/sun#497.
Once phetsims/sun#497 is implemented, we can choose the best label for this sim's Mass control:
>For example, for Gravity Force Lab Basics, here are some options:
> -   Mass 1 spinbutton
> -   Mass 1 stepper
> -   Mass 1 number spinner
> -   Mass 1 number picker
> -   Mass 1 mass changer
>
> I think I like "Mass 1 mass changer" and "Mass 1 number spinner" best.

**Comment by zepumph** [comment]
@terracoda is this now fixed from work done in https://github.com/phetsims/sun/issues/497

**Comment by terracoda** [comment]
Yep, you fixed it! Sounds great! And utterance queue is not piling up; nicely jumping to latest value after quick changes!

Closing!
