### ISSUE TITLE
Screen reader saying "clickable" on PDOM text?

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#110]
As of maybe a week or 2 ago, I started hearing "clickable 1of 4" when reading through the dynamic state-of-the-sim list. 

I am using Safari and VoiceOver. I never heard this before. I would not describe the text as clickable. I am not sure why VoiceOver is suddenly describing the text as clickable. 

Is the dynamic list different than before a couple of weeks ago?

I'm going to check GFL Regular and see what it is doing.

**Comment by terracoda** [comment]
@zepumph, do you know why we need `data-focusable="false"` attribute on everything?

I don't hear "clickable" on the paragraphs, but I do on the list items. Not sure why? And this is new behaviour.

**Comment by terracoda** [comment]
I lied I am hearing "clickable" on most paragraphs, too. I do not hear "clickable" on the paragraphs that come right before a `ul`. I do not hear "clickable" on headings.

I am wondering if NVDA is doing something similar?

**Comment by terracoda** [comment]
@zepumph, I found some discussion about this on the WebAim email archive:
- [https://webaim.org/discussion/mail_thread?thread=6876](https://webaim.org/discussion/mail_thread?thread=6876)
- [https://webaim.org/discussion/mail_thread?thread=7559](https://webaim.org/discussion/mail_thread?thread=7559)

@zepumph, can you verify if an `OnClick event handler is added to the body element so that the script will pick up a click anywhere on the page` (Mike Moore's comment from the WebAim email archive, April 2015)

This seems like new behaviour to me, so perhaps a recent change to common code has added an OnClick event on an ancestor to the PDOM where there was not one before?

**Comment by terracoda** [comment]
Wondering if this issue is related to https://github.com/phetsims/a11y-research/issues/133

**Comment by jessegreenberg** [comment]
Indeed @terracoda, the reading of "clickable" everywhere is being caused by https://github.com/phetsims/a11y-research/issues/133 sorry about that.

**Comment by terracoda** [comment]
This seems to have been fixed by https://github.com/phetsims/a11y-research/issues/133#issuecomment-478011466

For VoiceOver.

Is it safe to close this issue for now, @zepumph?

**Comment by zepumph** [comment]
Sounds good!
