### ISSUE TITLE
Change label of position slider

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#112]
Please change labels for mass position sliders
FROM:
- mass 1, position
- mass 2, position

TO:
- Move mass 1
- Move mass 2

They will be read out as:
- Move mass 1, slider
- Move mass 2, slider

**Comment by terracoda** [comment]
This issue is design-related changes that will take place in issue #107.

@zepumph, if it's easy, you could just change the label of the position sliders first, and then work on #107.

**Comment by zepumph** [comment]
This sounds very nice. Good design!

**Comment by terracoda** [comment]
Thanks :-) Nice implementation!
