### ISSUE TITLE
For interviews Wed. April 10th 

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#115]
@zepumph, 2 interviews are schedule for Wednesday April 10th.

At end of day Tuesday (April 9th), please port best version of sim to sonification wrapper and provide Dev links for interviews.

**Comment by zepumph** [comment]
I think everything is set up for this now. I couldn't get https://github.com/phetsims/gravity-force-lab-basics/issues/109 figured out, but did get some investigation on it. 

Here is the link to the sonification wrapper for tomorrow.
https://phet-dev.colorado.edu/html/phet-io-wrapper-sonification/1.0.0-dev.111/phet-io-wrapper-sonification/sonification.html

**Comment by terracoda** [comment]
Thanks @zepumph. I'll close this issue after interviews this week.

**Comment by terracoda** [comment]
Interviews completed, so closing this issue.
