### ISSUE TITLE
GFLBAlertManager may be getting initialized more than once

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/gravity-force-lab-basics#117]
From https://github.com/phetsims/inverse-square-law-common/issues/61 I noticed duplications of some of the alerts when clicking checkboxes. I think it may be because the alert manager is getting initialized more than once.

**Comment by terracoda** [comment]
Thanks @jessegreenberg, I verified this issue in GFL BASICS with VoiceOver. I hear the alerts three times after checking or unchecking any of the checkboxes.

**Comment by zepumph** [comment]
@jessegreenberg and I saw this in OL, I think this may have to do with more general UtteranceQueue work.

**Comment by jessegreenberg** [comment]
There were duplicates in the a11y view caused by changes in https://github.com/phetsims/scenery-phet/issues/490. We are still seeing check box related alerts get announced three times.

I noticed that `GFLBAlertManager.initialize()` is called in GFLBMassNode and in GFLBScreenView. Since there are two masses, that could explain why we are seeing three alerts.  When I change 
```js
`const alertManager = GFLBAlertManager.initialize( model );` 
```
to
```js
const alertManager = GFLBAlertManager.getManager();`
```
in GFLBMassNode the duplicates seem to go away, @zepumph does that look correct?

**Comment by zepumph** [comment]
In https://github.com/phetsims/inverse-square-law-common/issues/63 I fixed the pattern so that alert managers are only created once. This should now be fixed. @jessegreenberg please review

**Comment by jessegreenberg** [comment]
https://github.com/phetsims/inverse-square-law-common/issues/63 looks great @zepumph, and duplicate alerts are gone. Closing.
