### ISSUE TITLE
Keyboard Shortcuts Dialog adjustments & additions

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#118]
There are no small steps in this sim, but there are in GFL Regular. If it is possible and not too tedious due to shared resources between the 2 sims (3 if you include Coulomb's Law):
- Please remove the line about small steps under Change Mass (but only if this is not a big pain)

Also, this sim and GFL Regular have checkboxes, so 
- Under Basic Actions, please add the instructions for checkboxes after the item already there for buttons
    - The visual representation would be just like the button item, but with different words. The square brackets represent the Space key icon.:
        - "Toggle checkboxes [SPACE]" 
    - The a11y text for the checkbox item is: 
        - "Toggle checkboxes with Space key."

Edited: added only if line.

**Comment by terracoda** [comment]
@zepumph, do you need a visual for this?

**Comment by zepumph** [comment]
No visual needed, implemented both of them (as it was simple in the way it was set up).  Let me know what you think

**Comment by terracoda** [comment]
@zepumph, sounds and looks great, but could you please put the "Toggle checkboxes" line just after the Press buttons and just before the Escape to exit dialog.

Apologies for not being explicit about the order in the original post.

**Comment by zepumph** [comment]
In the above commit I reordered things, and I also refactored GeneralKeyboardHelpSection to be more explicit and easy to tell what the final order is. I also converted to es6. @terracoda please review, and also note that all the work done for this is in common code, and that this is now an option anywhere (I think you already knew that).

**Comment by terracoda** [comment]
@zepumph, the content looks and sounds great.

I think there might be an extra ` aria-labelledby` because I am hearing an end of group announcement after the starting heading block of the dialog. 

I have heard this before, and I just looked in  the code to see why...
<img width="938" alt="Screen Shot 2019-04-30 at 10 54 35 PM" src="https://user-images.githubusercontent.com/1902116/56993534-0043ed80-6b9d-11e9-98c7-01dd95bf0807.png">

I don't think we need the second `aria-labelledby` attribute. Where should I start an issue for a common code issue for a little tweaking of the dialog? Which repo does this common code item belong to?

**Comment by terracoda** [comment]
Oh duh, I see the commit was in scenery-phet. I'll move the comment to scenery-phet.

**Comment by terracoda** [comment]
@zepumph, please close this issue when https://github.com/phetsims/scenery-phet/issues/494 is addressed.

**Comment by terracoda** [comment]
@zepumph, I will close this issue as it is common to all sims and any needed work will be done in phetsims/scenery-phet#494
