### ISSUE TITLE
Fatal error: Missing string: INVERSE_SQUARE_LAW_COMMON/constantRadius in inverse-square-law-common for fallback locale: en

### ISSUE THREAD

**Issue by samreid** [phetsims/gravity-force-lab-basics#12]
Reported by Bayes:
Fatal error: Missing string: INVERSE_SQUARE_LAW_COMMON/constantRadius in inverse-square-law-common for fallback locale: en

**Comment by samreid** [comment]
I'm not sure if the constantRadius string should be in INVERSE_SQUARE_LAW_COMMON or GRAVITY_FORCE_LAB, @jessegreenberg can you comment?

**Comment by jessegreenberg** [comment]
Sorry about that, forgot to commit a change to inverse-square-law-common.  Should be using that string.
