### ISSUE TITLE
I hear no alerts with VoiceOver, and random alerts heard in A11y View with VoiceOver

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#121]
Not sure what happened, I am no longer hearing any alerts using master and Voice Over, though when I use the A11y View with a screen reader, alerts are triggered very randomly. The alerts are firing, I can see them in the orange box, but they are not always being read out.

Is this related to recent work in phetsims/scenery-phet/issues/491?

Should I re-open that issue?

**Comment by terracoda** [comment]
Tagging @jessegreenberg in case you have some insights.

**Comment by terracoda** [comment]
Or could this issue be related to recent work in hphetsims/scenery-phet/issues/490?

**Comment by terracoda** [comment]
Ooops, I didn't mean to close.

**Comment by jessegreenberg** [comment]
Hmm, thanks for reporting @terracoda, likely related to recent recent changes in https://github.com/phetsims/scenery-phet/issues/490.

**Comment by zepumph** [comment]
It also may be linked to https://github.com/phetsims/scenery-phet/issues/491

**Comment by terracoda** [comment]
@zepumph, I was wondering if I should reopen phetsims/scenery-phet#491 , but I'll let you assess and and re-open as necessary.

**Comment by zepumph** [comment]
@terracoda I would like to discuss this tonight together and to hear what you are experiencing. I think that will be the easiest step forward.

**Comment by zepumph** [comment]
>@zepumph, I was wondering if I should reopen phetsims/scenery-phet#491 , but I'll let you assess and and re-open as necessary.

Good idea

**Comment by terracoda** [comment]
@zepumph, we can discuss tonight, but I basically hear zero `aria-live` alerts, and only hear `label` content and `aria-valuetext` when interacting with anything (sliders, checkboxes, buttons).

**Comment by zepumph** [comment]
After discussing with @terracoda, we reverted some of the changes in https://github.com/phetsims/scenery-phet/issues/491

like https://github.com/phetsims/scenery-phet/commit/7a6c7c9936cb7178dc3088836a241ddffb959291

We also noticed that we need to increase the alertStableDelay for the position sliders and mass number spinners. I wonder if we should do this by increasing the default (reverting the change in https://github.com/phetsims/scenery-phet/issues/491) or just changing those specific usages in GFLB.

**Comment by jessegreenberg** [comment]
Solution proposed and ready for review in https://github.com/phetsims/scenery-phet/issues/491

**Comment by zepumph** [comment]
@terracoda will you please review.

**Comment by terracoda** [comment]
@zepumph, the alerts are working well. 
A couple of times I didn't hear the mass value in kilograms, but I haven't isolated that.
I am going to close this issue as things are working very well, and will keep watching for mass alert misses and see if I can isolate it.

And I checked the A11y View, too. The alerts are working well, there. I still get the normal repetition of aria-live alerts that I have always noticed in the A11y View. There are no pile ups in the utterance queue, so the repetition is not bothersome to me at this point.

I am going to close this issue.
