### ISSUE TITLE
Factor out gravitation constant to common code

### ISSUE THREAD

**Issue by zepumph** [phetsims/gravity-force-lab-basics#123]
GFLB and Gravity and Orbits both use the gravitational constant, but it is different in both, and neither are what most of the top google searches seem to dictate as `6.674(08) x 10-11`. After talking on slack with @samreid and @pixelzoom, I'm going to make `PHET_CORE/PhysicalConstants.js` to house numbers like these in the future. and move this use there.

**Comment by zepumph** [comment]
Added in the above commits @samreid please review.

**Comment by samreid** [comment]
Looks good, thanks!  I made minor text updates and var => const.  I would also recommend assigning to the responsible dev to make sure the value change didn't disturb any overt behavior, for this repo and probably a new issue for GAO.

**Comment by zepumph** [comment]
Thanks for the cleanup! I've been working in this repo and already tested here, and will continue to be on the look out. I also created https://github.com/phetsims/gravity-and-orbits/issues/279. Closing
