### ISSUE TITLE
Redesign - Remove on focus listener that changes aria-valuetext on position sliders

### ISSUE THREAD

**Issue by zepumph** [phetsims/gravity-force-lab-basics#124]
Because of a lack of support discovered as part of https://github.com/phetsims/gravity-force-lab-basics/issues/119 and https://github.com/phetsims/a11y-research/issues/138

From talking with @terracoda during our  meeting tonight:

**Possible option 1:** 
Only provide "left/right side of track" a single time immediately after other landmarks like "last stop" and "track end". Also we can make sure "left/right side of track" is announced on startup position AND after a Reset. This way we don't have too many updates happening all the time.

**Possible option 2:** 
Provide no references to "left/right side of track" .

In both options we will also move the "close/farther" progress phrases to `aria-live` alerts rather than providing it in `aria-valuetext`.

Assigning to @terracoda to decide what she would like from the design. We were liking option 1 during the meeting.

May 1 & 2: Edited content for clarity.

**Comment by terracoda** [comment]
@zepumph, I am still liking option 1, and I will update the design doc asap, before Monday morning, and hopefully before.

**Comment by terracoda** [comment]
Tagging issue #122

**Comment by terracoda** [comment]
@zepumph, I have update the big table as if Option was implemented.
Handing over to you.

**Comment by terracoda** [comment]
@zepumph, please note that I haven't yet cleaned up all the places in the document where I was explaining when & what position regions/landmarks to use. The tables have reliable information, so just stick to the tables and the text for option 1 in https://github.com/phetsims/gravity-force-lab-basics/issues/124#issue-439072224

Here are direct links to the updated tables:
- [Table: Position Regions & Landmarks](https://docs.google.com/document/d/1HdDG9ds2MdbCb21l9qk3cI8yBQxK6-wBWNXC4Tloji8/edit#heading=h.k9vtfb4kzkmi) - provides the overview of the described position
- [18 step Cognitive walkthrough](https://docs.google.com/document/d/1HdDG9ds2MdbCb21l9qk3cI8yBQxK6-wBWNXC4Tloji8/edit#heading=h.ty8avmawwxa) - 2 table under this heading are updated as if option 1 is implemented.

**Comment by zepumph** [comment]
Above is the change to the aria-valuetext, next is adding the close/far to the alert.

**Comment by zepumph** [comment]
Above the alerts were moved over. @terracoda please review. I think this is good enough for feedback though it may not be perfect yet.

**Comment by terracoda** [comment]
@zepumph, apologies for not getting to this on the weekend. I found some issues. **If at all possible** could you please address by end of your day Monday:
1. Missing the word "**force**" (my emphasis) in two _progress alert_ phrases.
  a. I would like the _progress alert_ phrases (i.e. phrases starting with "Closer" and "Farther away") to include the word "**force**" (bolded for emphasis only):
      - "Closer, **force** arrows get bigger, forces now 43.6 ‪newtons‬." 
      - "Farther away, **force** arrows get smaller, forces now 26.4 ‪newtons‬."

2. _Progress alert_ frequency is too frequent. I think the logic that is controlling the frequency of the _progress alerts_  seems to be reversed. It was my design intention to have the _progress alerts_ on the first step and on directional changes, and then only kilometers on the second step and continued steps in the same direction. Here's an example:
a. Step 1: mass 1 moves closer to mass 2: "Closer, force arrows get bigger, forces now 43.6 ‪newtons‬."
b. Step 2: Continuing in same direction: "Force arrows get bigger, forces now 59.3 ‪newtons‬."
c. Step 3: Same direction again: "Force arrows get bigger, forces now 85.4 ‪newtons‬."
d. Step 4: Change in direction: "Farther away, force arrows get smaller, forces now 59.3 ‪newtons‬."

3. The "Last stop left/right" landmark in the `aria-valuetext` can become stale once the users moves the other mass sphere or makes the mass of the other sphere smaller. Apologies, I didn't foresee this problem when I was thinking the design through. As a solution, we may need to move the "Last stop left/right" phrase parameter into the force alert like the "Closer/Farther away" phrase parameters. If we did then there would be a special force alert for when the a last-stop condition is true:
a. mass 1 reaches last stop condition at 1.7 km from mass 2:  
    - aria-valuetext: "1.7 kilometers from mass 2"
    - alert text: "Last stop right, force arrows small, forces now 184.7 ‪newtons‬."
      - @zepumph note that this would mean prepending "Last stop right/ or left" to the current special-case alert that describes the state of the force arrows (the actual size of the force arrows): "Force arrows small, forces now 184.7 ‪newtons‬." Does that make sense?

I hope these are clear @zepumph, and just do what you an for the end of day today. Thanks @zepumph! And if you cannot get to these today, I will review the above ideas with the consultants.

**Comment by zepumph** [comment]
(1) and (2) should be fixed by the above commit. (1) just needed me to change a string, and (2) was a stupid bug where there was one flipped if statement, so basically everything was backwards, position alerts when there shouldn't be, and no position alerts when it was appropriate to.

**Comment by terracoda** [comment]
@zepumph, thanks! It sounds much better now, please make dev link and port to sonification wrapper for issue #122, and you are awesome!

**Comment by zepumph** [comment]
(3) is just like https://github.com/phetsims/gravity-force-lab-basics/issues/125#issuecomment-489831657 and above comments about the Mass Control's value text and the constant size checkbox. It may be nice to think through solutions together.

**Comment by terracoda** [comment]
@zepumph, yes, I figured it was a similar problem. Now, that we will not use a blur event to reset it the `aria-valuetext`.

**Comment by zepumph** [comment]
"Last stop right" should never be in an alert with "Closer". Instead it should overwrite that piece, so if at the last stop, then moved in a step, then moved out back to the last stop, the alert would say:
"Last stop right, force arrows small, forces now 184.7 ‪newtons‬."

@terracoda would ideally like to keep the "Track end left" in the aria-valuetext. It is nice to have them when focusing that element, and there is no worry of that state changing when the slider is not being interacted with (unlike the last stop right/left). If the implementation is too difficult to do this (which is isn't), she said we could move that out to the alert too. I don't foresee that being the case.

**Comment by terracoda** [comment]
@zepumph, your comment above looks good. I think you understand this, but just for clarity, I'll add that due to the spheres horizontal positioning, "Last stop right" would never be in an alert with "Farther away" and "Last stop left" would never be in an alert with "Closer".

Imagine the user is starting an interaction with the Move mass 1 slider and is 1 key press away from mass 2. They get their focus information which may be:
- Focus: "2.5 kilometers from ‪mass 2‬, Move mass 1 slider"
- Step 1 reaches the last stop right: 
  - `aria-valuetext:` 2 kilometers from mass 2
  - aria-live alert: "Last stop right. Force arrows medium size, forces now 333.7 ‪newtons‬."

@zepumph, I got to update the walk-through in the design doc.
I also just noticed that the distance value in the `aria-valuetext` can also get out of synch, see screenshot below. I think you might have been resetting this with a blur event before?? Or maybe this is how it has been working and I didn't actually notice.
<img width="1020" alt="distance-out-of-synch" src="https://user-images.githubusercontent.com/1902116/57370667-fa4b9f00-7190-11e9-8be0-76e961532124.png">

As you said in our meeting, it might be better to put all the position landmarks in alerts. I'll do the walk-through and assign back to you asap.

**Comment by terracoda** [comment]
@zepumph, FYI, I have been working on this and am almost ready to summarize. Apologies for the delay.

**Comment by terracoda** [comment]
Oops wrong issue!

**Comment by terracoda** [comment]
Nope, correct issue. I'm working on this ;-)

**Comment by terracoda** [comment]
@zepumph, I've updated the table. I'll add a summary of details here in the morning to make sure this issue (and any remaining questions I have) are clear.

**Comment by terracoda** [comment]
@zepumph, apologies this has taken so long. 
I also updated the summary section on Position & Distance and added a description of the pseudo-logic for special cases.
- [Summary logic for position/distance](https://docs.google.com/document/d/1HdDG9ds2MdbCb21l9qk3cI8yBQxK6-wBWNXC4Tloji8/edit#heading=h.l8i3vsko1d7c)

I updated and split the tables for the cognitive walk-through.  There are now two groups - one group for Distance checked and one for Distance not checked. Hopefully this makes it way easier to follow step by step.
- [Walkthrough with Distance Checked](https://docs.google.com/document/d/1HdDG9ds2MdbCb21l9qk3cI8yBQxK6-wBWNXC4Tloji8/edit#heading=h.ty8avmawwxa)
- [Walkthrough with Distance Not checked](https://docs.google.com/document/d/1HdDG9ds2MdbCb21l9qk3cI8yBQxK6-wBWNXC4Tloji8/edit#heading=h.wekkeuwlc0qc)

I have a question at Step 11 about if we should reduce the occurrences of "Left/right side of track"
and a question at Step 16 about if "Track end left/right" should be handled just like "Last stop left/right".

In both cases, we can take the path of least resistance for implementation.

**Comment by terracoda** [comment]
@zepumph 
Re my comment
> In both cases, we can take the path of least resistance for implementation.

**To be more clear:**
- Step 11 ("Left/right side of track") if it is easier to leave as currently implemented, please do so.
- Step 16 ("Track end left/right") leave in `aria-valuetext` if easier, or implement as `aria-live alert` just like "Las stop left/right", whichever is easier (or more elegant).

**Comment by zepumph** [comment]
@terracoda I hope that everything is done in the above commit. I went through both walk throughs and things are looking pretty good. In general I made comments in line in the walkthrough, but I will mention the stuff I noticed here too for clarity:

* "Left/right side of track" regions are only stated through valuetext when crossing the center line.
* "Track end left/right" along with "last stop left/right" are in the alerts, overriding the "closer/farther" as appropriate. I like it like that, let me know what you think!
* When you have "last stop right/left" you include state data in the walkthrough like "force arrows medium size." Right now, when REACHING the last stop, but not quite there yet, it is easier to treat it like a change in position description, which is why instead we have "force arrows get bigger/smaller". It's this way mainly because that's how it worked out. Let's talk about it!  
* In the walk through when distance is not checked, a lot of the regions are different from what you have in the doc. Likely this is alright, but I wanted to give you a chance to look over them just to be sure. (This is most of the comments in the doc, just to keep track of it).

**Comment by zepumph** [comment]
>When you have "last stop right/left" you include state data in the walkthrough like "force arrows medium size." Right now, when REACHING the last stop, but not quite there yet, it is easier to treat it like a change in position description, which is why instead we have "force arrows get bigger/smaller". It's this way mainly because that's how it worked out. Let's talk about it!

@terracoda and I discussed, and we are alright with the way it currently is.

**Comment by terracoda** [comment]
@zepumph, I am just following up on your last comment and our discussion.
From a description perspective where I am assuming the user is not seeing the arrows, I was asking myself when is the best time for them to find out about the actual size of the arrows. I thought that the last stop/the track end (an early cue) was a good time to reveal this state-info about the size of the arrows. 

I am comfortable leaving our decision as-is, and as we finish off GFL Regular, I can think about this early cuing a little more.

**Comment by zepumph** [comment]
@terracoda, now because of work in https://github.com/phetsims/gravity-force-lab-basics/issues/128 some of this is fixed. I still haven't been able to get the reset to work correctly. I'll keep working on it soon. Here is the patch for that work in progress:


<details>

```

Index: gravity-force-lab-basics/js/gravity-force-lab-basics/view/GFLBScreenView.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- gravity-force-lab-basics/js/gravity-force-lab-basics/view/GFLBScreenView.js	(revision c4ffa8d6381d443b65e5a2eb1686c873c934c4dd)
+++ gravity-force-lab-basics/js/gravity-force-lab-basics/view/GFLBScreenView.js	(date 1559083195157)
@@ -235,6 +235,13 @@
       const resetAllButton = new ResetAllButton( {
         listener: () => {
           model.reset();
+          positionDescriber.reset();
+
+          // This is a hacky workaround to get the reset to display the correct aria-valuetext, see https://github.com/phetsims/gravity-force-lab-basics/issues/124
+          model.object1.positionProperty.value = 0;
+          model.object1.positionProperty.reset();
+          model.object2.positionProperty.value = 0;
+          model.object2.positionProperty.reset();
         },
         right: this.layoutBounds.maxX - 10,
         bottom: this.layoutBounds.maxY - 10,
Index: gravity-force-lab-basics/js/gravity-force-lab-basics/view/GFLBMassNode.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- gravity-force-lab-basics/js/gravity-force-lab-basics/view/GFLBMassNode.js	(revision c4ffa8d6381d443b65e5a2eb1686c873c934c4dd)
+++ gravity-force-lab-basics/js/gravity-force-lab-basics/view/GFLBMassNode.js	(date 1559082485589)
@@ -46,6 +46,7 @@
         y: MASS_NODE_Y_POSITION,
         snapToNearest: model.snapObjectsToNearest, // in meters, charges will snap to the nearest 0.1 meters in model coordinates
         stepSize: GFLBConstants.MASS_STEP_SIZE,
+        additionalA11yDependencies: [ model.showDistanceProperty ],
         tandem: Tandem.required
       }, options );
 
Index: gravity-force-lab-basics/js/gravity-force-lab-basics/view/describers/GFLBPositionDescriber.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- gravity-force-lab-basics/js/gravity-force-lab-basics/view/describers/GFLBPositionDescriber.js	(revision c4ffa8d6381d443b65e5a2eb1686c873c934c4dd)
+++ gravity-force-lab-basics/js/gravity-force-lab-basics/view/describers/GFLBPositionDescriber.js	(date 1559083249378)
@@ -8,6 +8,7 @@
   const gravityForceLabBasics = require( 'GRAVITY_FORCE_LAB_BASICS/gravityForceLabBasics' );
   const GravityForceLabPositionDescriber = require( 'GRAVITY_FORCE_LAB/gravity-force-lab/view/describers/GravityForceLabPositionDescriber' );
   const ISLCA11yStrings = require( 'INVERSE_SQUARE_LAW_COMMON/ISLCA11yStrings' );
+  const StringProperty = require( 'AXON/StringProperty' );
   const StringUtils = require( 'PHETCOMMON/util/StringUtils' );
   const Util = require( 'DOT/Util' );
 
@@ -38,6 +39,9 @@
 
       super( model, object1Label, object2Label, options );
 
+      // @private {Property.<String>[]}} - keep track of these for resetting
+      this.previousTextProperties = [];
+
       // link GFLB property to whether or now we use quantitative distance for alerts and value text
       model.showDistanceProperty.link( showDistance => {
         this.useQuantitativeDistance = showDistance;
@@ -53,9 +57,8 @@
      */
     getOnChangeAriaValueTextCreator( objectEnum ) {
 
-      // keep track of the previous value text
-      let previousText = '';
-
+      const previousTextProperty = new StringProperty( '' );
+      this.previousTextProperties.push( previousTextProperty );
       const superValueTextCreator = super.getOnChangeAriaValueTextCreator( objectEnum );
       return () => {
 
@@ -64,11 +67,11 @@
 
         // When distance isn't checked, the qualitative alerts are the same between region changes, so add a space such
         // that the AT will still read the value text each time. See https://github.com/phetsims/gravity-force-lab-basics/issues/113#issuecomment-481413715
-        if ( !this.model.showDistanceProperty.get() && previousText === newAriaValueText ) {
+        if ( previousTextProperty.value === newAriaValueText ) {
           newAriaValueText = newAriaValueText + ' ';
         }
 
-        previousText = newAriaValueText;
+        previousTextProperty.value = newAriaValueText;
         return newAriaValueText;
       };
     }
@@ -88,6 +91,16 @@
       } );
     }
 
+    /**
+     * @public
+     * Reset the describer
+     */
+    reset() {
+      console.log( 'resetting sub');
+      this.previousTextProperties.forEach( property => property.reset() );
+      super.reset();
+    }
+
     // @override
     getDistanceIndex( distance ) {
       assert && assert( distance > 0, 'Distance between spheres should always be positive.' );
Index: inverse-square-law-common/js/view/ISLCObjectNode.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- inverse-square-law-common/js/view/ISLCObjectNode.js	(revision 94d9b64518b0fb54952caa9af6440c341c26e494)
+++ inverse-square-law-common/js/view/ISLCObjectNode.js	(date 1559083249384)
@@ -125,7 +125,10 @@
       arrowTailWidth: 3,
       arrowStroke: null,
 
-      tandem: Tandem.required
+      tandem: Tandem.required,
+
+      // TODO: document
+      additionalA11yDependencies: []
     }, options );
 
     var tandem = options.tandem;
@@ -340,7 +343,8 @@
       a11yCreateValueChangeAriaValueText: positionDescriber.getOnChangeAriaValueTextCreator( this.enum ),
 
       // This object's PDOM description also depends on the position of the other object, so include it here.
-      a11yDependencies: object === model.object1 ? [ model.object2.positionProperty ] : [ model.object1.positionProperty ]
+      a11yDependencies: options.additionalA11yDependencies.concat( object === model.object1 ?
+        [ model.object2.positionProperty ] : [ model.object1.positionProperty ] )
     };
 
     // a11y - initialize the accessible slider
Index: inverse-square-law-common/js/view/describers/PositionDescriber.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- inverse-square-law-common/js/view/describers/PositionDescriber.js	(revision 94d9b64518b0fb54952caa9af6440c341c26e494)
+++ inverse-square-law-common/js/view/describers/PositionDescriber.js	(date 1559082747019)
@@ -15,6 +15,7 @@
   const ISLCA11yStrings = require( 'INVERSE_SQUARE_LAW_COMMON/ISLCA11yStrings' );
   const ISLCDescriber = require( 'INVERSE_SQUARE_LAW_COMMON/view/describers/ISLCDescriber' );
   const Property = require( 'AXON/Property' );
+  const StringProperty = require( 'AXON/StringProperty' );
   const StringUtils = require( 'PHETCOMMON/util/StringUtils' );
 
   // strings
@@ -130,6 +131,8 @@
       // see https://github.com/phetsims/gravity-force-lab-basics/issues/88
       this.useQuantitativeDistance = true;
 
+      this._previousPositionRegionProperties = [];
+
       Property.multilink(
         [ this.object1.positionProperty, this.object2.positionProperty ],
         ( x1, x2 ) => {
@@ -304,7 +307,9 @@
      * @returns {Function}
      */
     getOnChangeAriaValueTextCreator( objectEnum ) {
-      let previousPositionRegion = null;
+
+      const previousPositionRegionProperty = new StringProperty( '' );
+      this._previousPositionRegionProperties.push( previousPositionRegionProperty );
 
       // NOTE: AccessibleValueHandler supports parameters to this function, but recognize that subtypes override this
       // method before adding these, see https://github.com/phetsims/gravity-force-lab-basics/issues/113
@@ -314,8 +319,8 @@
         const newPositionRegion = this.getCurrentPositionRegion( objectEnum );
 
         // Only include the region if it is different from the previous. The key
-        if ( previousPositionRegion !== newPositionRegion ) {
-          previousPositionRegion = newPositionRegion;
+        if ( previousPositionRegionProperty.value !== newPositionRegion ) {
+          previousPositionRegionProperty.value = newPositionRegion;
 
           return StringUtils.fillIn( positionDistanceFromOtherObjectPatternString, {
             positionRegion: newPositionRegion,
@@ -330,6 +335,15 @@
       };
     }
 
+    /**
+     * @public
+     */
+    reset() {
+      console.log( 'resetting super');
+
+      this._previousPositionRegionProperties.forEach( property => property.reset() );
+    }
+
     /**
      * @param {ISLCObjectEnum} objectEnum
      * @returns {boolean}

```

</details>

**Comment by zepumph** [comment]
@terracoda I ended up only setting it on region change, meaning only when crossing the center line. This simplified the code, and also the reset case. 

@jessegreenberg I added reset methods to `AccessibleSlider` and `AccessibleValueHandler`. 

Overall I'm happy with these changes. We will see what dev testing/code review brings. 

@terracoda please review the aria-valuetext for the positions as a whole. Lots of changes have occurred in this issue. It would also be good to have a look at at the alerts accompanying position changes. Let me know what you think!

**Comment by terracoda** [comment]
@zepumph, I realy like how this is working! We get a sense of the track in the scene summary, and then if the side of the track changes, we hear that we have crossed over to a different side.

The `aria-valuetext` goes nice with edge alerts as well.

I think this is just the right balance. I am pleased the results as well. Closing.
