### ISSUE TITLE
Remove on focus force alerts for position and mass control sliders

### ISSUE THREAD

**Issue by zepumph** [phetsims/gravity-force-lab-basics#127]
@terracoda found this from the consultant interview. Basically we can remove them for 2 reasons:

1. Information overload, note that the size of the arrow is already in the screen summary and on each of the descriptions for the mass spheres.
2. Thiss force alert relies on a focus event, which isn't cross platform enough.

@terracoda asked the consultant what's expected when a control gains focus, and they said (not surprisingly):
- where the control is at,
- what the control is for, and 
- the name of the control.

**Comment by terracoda** [comment]
@zepumph, specifically we are talking about the short aria-live alert that describes the size of the arrows when either a move mass or change mass control gains focus. This issue is not related to `aria-valuetext`.

**Comment by zepumph** [comment]
@terracoda all 4 on focus alerts have been removed. Please review.

**Comment by terracoda** [comment]
Beautiful. Verified and closing.
