### ISSUE TITLE
The updating of all aria-valuetext?

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#128]
In light of issues #125 and #124 should we consider more deeply the idea that @zepumph mentioned on Wednesday that allow for a 1 to many relationship for controls? Or more simply having all aria-valuetext update when there's a model change.

Discuss pros and cons with @emily-phet.

**Comment by jessegreenberg** [comment]
This issue may be related: https://github.com/phetsims/sun/issues/507

**Comment by jessegreenberg** [comment]
Also, Accessibility.js currently has a setter for aria-valuetext, would it be too tricky to use that? AccessibleValueHandler could update the aria-valuetext when its valueProperty changes while in other situations the client can set ariaValuetext directly through the Accessibility trait.

**Comment by zepumph** [comment]
>while in other situations the client can set ariaValuetext directly through the Accessibility trait.

Though I think that is close, I am worried about that solution because I don't like the idea of duplicating complicated aria-valuetext creation logic in AccessibleValueHandler and spiratically whereever you need to link to another Property. Instead I was looking into calling over to AccessibleValueHandler to update accordingly. See `AccessibleValueHandler.updateOnFocusAriaValueText` which does this for the on focus value text (which will likely be deleted soon). There we can only have a single usage of the value-text creation logic for the Node, but we can call from outside forces to update it. I think something like this seems reasonable, but I wonder if there is a better solution. 

@jessegreenberg can we brainstrom this next a11y dev meeting?

**Comment by terracoda** [comment]
@zepumph, I am not sure of priority for this issue.
But if we need to solve this issue to solve issue noted in https://github.com/phetsims/gravity-force-lab-basics/issues/124#issuecomment-490443573, then I would mark it as high priority.

**Comment by zepumph** [comment]
- [ ]  Note, on reset, the aria-valuetext isn't being updated correctly with "left/right side of track" if the object was on its starting side, and then is reset to that same side (because there is no change, so it doesn't explicitely say it.

**Comment by zepumph** [comment]
After discussing this with @jessegreenberg, we decided to add a list of dependencies to `AccessibleValueHandler` so that the valuetext can update whenever any of them change. 

It was also important to support this through an option and a setter for convenience, so I will add that too.

**Comment by zepumph** [comment]
I added `a11yDependencies` above. This seemed to fix the issues in GFLB, though not the ones related to reset. @jessegreenberg can you please review. @terracoda I'll assign you to review over in https://github.com/phetsims/gravity-force-lab-basics/issues/124 once some edge cases for GFLB are more sorted out.

**Comment by zepumph** [comment]
Note @jessegreenberg I'm most worried about how I'm handling "oldValue." Although it worked in JT, I'm not confident in the long term strength of that logic.

**Comment by jessegreenberg** [comment]
Changes to AccessibleValueHandler look great @zepumph, very nice. `oldValue` looks very reasonable, I can't think of cases where that will break. One question regarding a code comment:
> This looks messy, but in reality you can only supply the valuePattern OR the create function, so this works as an "either or" situation.

Do you think this could be changed/improved somehow? I am having a hard time remembering why they were mutually exclusive.

**Comment by zepumph** [comment]
Sounds good. Please let me know what you think about it now, feel free to close or recommend.

**Comment by jessegreenberg** [comment]
👍
