### ISSUE TITLE
Change alerts when Distance checkbox is unchecked and checked

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#129]
Currently, when a user unchecks the Distance checkobox, the hear:
- Distance hidden.

In my May 10th session, the consultant was unsure of what "Distance hidden" meant. She was unsure what she would hear instead of values in kilometers. She seemed hesitant to explore with Distance no checked.

**Suggested options for a clarity:**
1. Distance relative, kilometers hidden.
2. Kilometers hidden, distance relative.
3. Kilometers hidden, distance described.

**Comment by terracoda** [comment]
Actually, we will go with changes to both alerts:
- Distance measured in kilometers.
- Distance measurement hidden.

**Comment by terracoda** [comment]
@zepumph , just adding the state changes for clarity
**When Distance checkbox becomes unchecked**
- Distance measurement hidden.

**When Distance checkbox becomes checked**
    Distance measured in kilometers.

**Comment by zepumph** [comment]
Updated above, closing
