### ISSUE TITLE
Screen Summary: tweak to static description of screen summary

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#133]
Based on a comment from my May 10th session, I think it might be a good idea to add the idea of the existence of a track into the static part of the screen summary.

**Currently, the second paragraph in the static intro reads:**
> The Play Area has a blue sphere labeled Mass 1 and a red sphere labeled Mass 2. A force arrow starts at the center of each sphere and points directly at the opposite sphere. Spheres can be moved closer or farther from one another. The mass of each sphere can be increased or decreased. Each sphere is held in place by a robot.

**Please change to:**
> The Play Area has **two mass spheres,** a blue sphere labeled mass 1 and a red sphere labeled mass 2. A force arrow starts at center of each sphere and points directly at opposite sphere. Spheres can be moved closer or farther from each other **along a track**. The mass of each sphere can be increased or decreased. Each sphere is held in place by a robot.

**Comment by terracoda** [comment]
@zepumph, not sure you can notice it, but I bolded the new words in previous comment.

**Comment by zepumph** [comment]
Implemented above, thanks for the bolding!
