### ISSUE TITLE
Add other mass name to "go-beyond-edge" alerts

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#137]
In following up to issue #135, if there is time please add the other mass's name, so these "go-beyond-edge" alerts so they would look like this:

**Random examples for mass 1:**
- **F**arthest **from mass 2**, force arrows tiny, forces 0.7 ‪newtons‬. 
- **C**losest **to mass 2**, force arrows tiny, forces 39.5 ‪newtons‬.
- **E**xtremely close **to mass 2**, force arrows very small, forces 144.2 ‪newtons‬.
- **V**ery close **to mass 2**, force arrows huge, forces 1067.9 ‪newtons‬.

**Random examples for mass 2:**
- **E**xtremely close **to mass 1**, force arrows small, forces 184.7 ‪newtons‬.
- **F**ar **from mass 1**, force arrows tiny, forces 11.5 ‪newtons‬.
- **V**ery close **to mass 1**, force arrows large, forces 454 ‪newtons‬.
- **F**arthest **from mass 1**, force arrows tiny, forces 21.7 ‪newtons‬.

As mentioned in https://github.com/phetsims/gravity-force-lab-basics/issues/135#issuecomment-495556155, I don't want this request to block this sim from going into Dev Testing. 

If logic to handle this request does not already exist, we could make this addition when we are finishing off GFL Regular. I am marking as low priority (so as not be a blocking issue).

**Comment by zepumph** [comment]
Implementing this simplified some of the code, so it was nice to do as part of the code review in https://github.com/phetsims/gravity-force-lab-basics/issues/134. @terracoda please review.

**Comment by terracoda** [comment]
Awesome, I'll verify in the morning ;-)

**Comment by terracoda** [comment]
Adding the mass name to these edge alerts sounds awesome to me! Thanks for adding this nice polish to the alerts. Closing.
