### ISSUE TITLE
Remove list structure on Mass Controls

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#138]
In light of https://github.com/phetsims/ohms-law/issues/148#issuecomment-497514617, it is likely best to remove the list structure around the Mass controls.

Hopefully, this is quite easy to do. 
@zepumph, I'd keep the `aria-labelledby` on the parent `div`.

**Possible pseudo-code**
```html
<h3 id="mass-heading">Mass Controls</h3>
<div aria-labelledby="mass-heading">
<Mass 1 slider/number spinner>
<Mass 2 slider/number spinner>
</div>
```

**Comment by zepumph** [comment]
I ended up replacing the `UL` with a div, and the `LI` with a div. The resulting output has more divs, but keeps the aria-valuetext in the a11y view more inline:

![image](https://user-images.githubusercontent.com/6856943/58730970-08f53280-839a-11e9-9c18-b9669624934f.png)


When the `LI` tags are just removed, we get this:

![image](https://user-images.githubusercontent.com/6856943/58731003-1d392f80-839a-11e9-8e42-7af3f387e72e.png)



I can do either one, but just committed the one with an extra nested 'div' please review.

**Comment by terracoda** [comment]
@zepumph, the goup of mass controls sounds great on VoiceOver! Closing this issue.
