### ISSUE TITLE
Review Sim

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/gravity-force-lab-basics#14]
@arouinfar @ariel-phet this sim is pretty much feature complete.  We still need to make sure that #10 is done, along with some other cleanup.  But @arouinfar can you please review 

http://www.colorado.edu/physics/phet/dev/html/gravity-force-lab-basics/1.0.0-dev.4/gravity-force-lab-basics_en.html

Does anything need to change?  Are we ready for some pixel polishing?

Potential helpful query param: ```showGrid``` - shows the distance grid which the masses are constrained to.

**Comment by arouinfar** [comment]
Change requests discussed after status:

- [ ] Make distance line gray and give it a thinner stroke so it's less vector-y
- [ ] Reduce size of checkboxes to roughly match height of first letter
- [ ] Increase size of spinners to be more like Proportion Playground
- [ ] Add black shadow to "mass 1" and "mass 2" labels
- [ ] Unbold "billion kg" labels
- [ ] Move Mass 2 panel slightly to the left so that the space between the panels is equal

**Comment by jessegreenberg** [comment]
Should
> Reduce size of checkboxes to roughly match height of first letter

Be applied to gravity-force-lab as well?

**Comment by jessegreenberg** [comment]
@arouinfar @ariel-phet here is a new version with these changes:

http://www.colorado.edu/physics/phet/dev/html/gravity-force-lab-basics/1.0.0-dev.5/gravity-force-lab-basics_en.html

**Comment by jessegreenberg** [comment]
In the above link, I think the labels are a little small with the increase in size to the number picker.

**Comment by ariel-phet** [comment]
@jessegreenberg 

1. Agreed the mass labels of "billion kg" probably need to be larger
2. I think the distance readout can be even vertically closer to the distance line
3. There are a few layering issues shown in the screenshot below
- I think the force arrows show be on top of the distance dashed leader lines
- I think the force value readout should also be layered on top of the dashed leader lines

![capture](https://user-images.githubusercontent.com/4051174/27750998-87d222fa-5d97-11e7-9d08-0316cebf0ba6.PNG)

**Comment by arouinfar** [comment]
Ditto everything @ariel-phet said. I would add that the mass and "billion kg" labels could be bumped up a pt or two, but their relative size should stay about the same.

@jessegreenberg I really like the new checkbox size, so I would go ahead and apply it to all `inverse-square-law` sims.

**Comment by ariel-phet** [comment]
@jessegreenberg @arouinfar to clarify I did not think that the "Mass 1" and "Mass 2" labels needed to be changed in size....just the size of the "billion kg" text

**Comment by arouinfar** [comment]
Thanks for the clarification @ariel-phet! Increasing the spinner size made the "Mass 1" and "Mass 2" seem a bit smaller to me, but looking at it again, I realize it's the same size as the checkbox text, which seems appropriate.

@jessegreenberg let's increase the "billion kg" labels a bit and see how things look.

**Comment by jessegreenberg** [comment]
> There are a few layering issues shown in the screenshot below

Good catch.  Actually I am seeing this in gravity-force-lab too, this will be a fix in inverse-square-law-common.

**Comment by jessegreenberg** [comment]
The layering issue was closed with phetsims/inverse-square-law#9. Since this sim is now being dev tested this can be closed and final polishes can come from new issues. Closing.
