### ISSUE TITLE
Add Challenges & Lessons Learned for this sim in design doc

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#142]
I have listed out several design [challenges and lessons learned](https://docs.google.com/document/d/1HdDG9ds2MdbCb21l9qk3cI8yBQxK6-wBWNXC4Tloji8/edit#heading=h.4t4p8jfg9z9) in the design document.

@jessegreenberg, @zepumph, and @arouinfar, please review and add anything you think that is note-worthy and that is good to keep in mind for future or past designs.

**Comment by terracoda** [comment]
Please un-assign yourselves after you have had a look and added any comments.

**Comment by jessegreenberg** [comment]
I read through it, content looks good to me @terracoda.

**Comment by arouinfar** [comment]
@terracoda this looks great! It was also helpful in understanding how/why the descriptions have evolved since the initial draft we worked on.

**Comment by terracoda** [comment]
@zepumph, no rush, and once you comment, we can close this issue. I am particularly interested in your thoughts around having multiple repos to manage. Are there challenges, lessons learned there?

**Comment by terracoda** [comment]
@arouinfar, re your comment on the evolution of the descriptions, please comment if anything sound not quite right. It is possible that we could address any strangeness in the descriptions for this sim as we wrap-up on Gravity Force Lab Regular.

**Comment by arouinfar** [comment]
@terracoda thanks for asking! I looked over the a11y design doc, and spent some time playing with dev.39 using the a11y view. Generally, things are looking great!

I had one minor question about the Interactive Alerts. I noticed that there are alerts when the mass spinners are changed, but not when the distance between the masses is changed. Both of these interactions lead to a change in the force, so it seems a bit odd to have an alert in one case, but not the other.

As for the description content itself, I have one area of concern. When Constant Size is checked, the help text under H3: Mass Controls reads:

`Change {{density of spheres}} in billions of kilograms.`

Density is measured in mass per unit volume, so "billions of kilograms" is incorrect. It would more accurate to say "billions of kilograms per cubic kilometer" or even the more general "billions of kilograms per unit volume". 

That said, I have a bigger question as to whether this help text and alerts ("As {{density}} decreases, force arrows get smaller..) should refer to densities at all. Yes, the density will change, but that's as a result of the user changing the value of the mass. The goal here is for students to understand the relationship between the mass and force. When constant size is unchecked, some students may conflate mass and size, so the Constant Size option allows students to really just focus on the mass itself. I think changing the descriptions to refer to density adds on the layer of complexity we were trying to eliminate in the first place.

**Comment by terracoda** [comment]
@arouinfar, thanks for your review. There should indeed be alerts about the force when the mass spheres are moved. Were already beyond dev.113, so dev.39 may not have had the force alerts yet for position changes.

I'll start a new issue where you have access to the latest version, and we can discuss your concerns about wording for density.

**Comment by arouinfar** [comment]
Thanks for opening #149 @terracoda.

> There should indeed be alerts about the force when the mass spheres are moved.

On startup, I dragged the masses back and forth. The descriptions in the PDOM updated appropriately, but there weren't any interactive alerts. This was the latest dev:
https://phet-dev.colorado.edu/html/gravity-force-lab-basics/1.0.0-dev.39/phet/gravity-force-lab-basics_a11y_view.html

![image](https://user-images.githubusercontent.com/8419308/59518198-6ac99800-8e82-11e9-8572-e7aafa0e2928.png)

**Comment by terracoda** [comment]
@arouinfar, I see. You have to use the keyboard. The alerts do not work with mouse alone ;-)

**Comment by terracoda** [comment]
Try the Keyboard Shortcuts dialog for instructions on how to use the keyboard. We will see if the instructions work ;-)

**Comment by arouinfar** [comment]
> You have to use the keyboard. The alerts do not work with mouse alone ;-)

Thanks @terracoda. Using the keyboard to move the masses still doesn't produce any alerts in the a11y view. I do see alerts for the spinners, checkboxes, and resetAllButton, regardless of whether the interaction took place with the keyboard or mouse.

![image](https://user-images.githubusercontent.com/8419308/59535001-01ab4a00-8ead-11e9-9941-4dc7322c753d.png)

However, if I instead use dev.39 with VoiceOver, I do hear this after moving one of the masses:

`Closer, forces arrows get better, forces now 43.6 N`

Not sure what's going on, but it seems like this alert is simply not being shown in the a11y view.

**Comment by zepumph** [comment]
@terracoda I added two challenges to the document, in red. Let me know what else I can do.

**Comment by terracoda** [comment]
@zepumph, awesome comments. Thanks.
@arouinfar and I are discussing "density" concerns in issue #149.
Closing this issue.
