### ISSUE TITLE
Scene descriptions have similar words

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-force-lab-basics#144]
For https://github.com/phetsims/QA/issues/333
Discussed in a call with @zepumph.  I noticed that, when listening to the screen description, several similar words one right after the other could cause confusion.  Specifically, the list describes the magnitude of the force, mass 1, and mass 2 and these same words repeat several times.  Nothing there is wrong, but more careful wording may make things more understandable.

**Comment by terracoda** [comment]
@KatieWoe, can you be more specific?

What part of the screen summary could be confusing? 

This is how things are chunked up:
**Static parts (non-changing parts)**
1. Tell users it is an interactive sim
2. Describe what's in the Play Area
3. Describe what's in the Control Area

**Dynamic part (changing parts)**
4. Current-state-of-the-sim: Describes a big-picture view of the spheres together in relation to each other: details of force, distance, mass, and counter force are provided.

**Hints for interaction (how to get started)**
5. Initial interaction hint: Change position and ‪mass‬ of spheres to explore.
6. Keyboard Shortcuts hint.

**Note that once in Play Area**, the mass spheres are described again in a similar fashion, but this time from the perspective of each specific sphere. I was worried that this was a lot of repetition, but blind users have responded positively to this approach.

@KatieWoe, are concerned about the description of "mass" in 3rd bullet of item 4?
- "Mass of ‪mass 1‬ is {{2}} billion kilograms, {{half the size of}} ‪mass 2‬ at {{4}} billion kilograms."

**Comment by KatieWoe** [comment]
These are the sections that tripped me up when going at a fast speed:

>Currently, force on mass 1 by mass 2 is of equal size and pointing directly opposite to the force on mass 2 by mass 1.
>Force arrows are tiny at 33.4 ‪newtons‬.
‪>mass 1‬ and ‪mass 2‬ are close to each other, centers exactly 4 kilometers apart.
>Mass of ‪mass 1‬ is 2 billion kilograms, half the size of ‪mass 2‬ at 4 billion kilograms.
>Robots pull very little keeping spheres in place.

>‪mass 1‬, Blue Sphere
>Force arrow is tiny, and points directly at ‪mass 2‬.
>Size of force on ‪mass 1‬ by ‪mass 2‬ is 33.4 ‪newtons‬.
>‪mass 1‬ is 2 billion kilograms, half the size of ‪mass 2‬, and also 4 kilometers from ‪mass 2‬.

**Comment by terracoda** [comment]
Yep, ok, thanks for your comments. The difference between these 2 descriptions is the first one provides a description of the spheres in relation to each other, and the second is just a description of mass 1.

I've had positive responses from blind users on this approach, so I won't change it at this point.
