### ISSUE TITLE
Wrap-up: Complete interview spreadsheet

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#145]
In an effort to consolidate access to interview data across multiple teams and protocols, we need to provide brief details in the sim-specific interview spreadsheet for this sim, located here:
https://docs.google.com/spreadsheets/d/1b63z-1QDC9uaU_szffuEsayJhVGxJfAlMMhB8NRh47k/edit#gid=0

@terracoda has started to fill it out, and needs help finding interview dates and protocol numbers from @briannatomlinson and @emily-phet

**Comment by briannatomlinson** [comment]
Ok! I added the interview information that I had about GFLB. To my knowledge those are all of the interviews that we completed.

**Comment by terracoda** [comment]
@briannatomlinson, thanks. Now, I just need to know if we did any other interviews with sighted kids, regarding the sound design. I'll reach out to @arouinfar.

**Comment by terracoda** [comment]
@arouinfar, do you know if any interviews were done by you or @amanda-phet on Gravity Force Lab Basics? I'm thinking about recent interviews, perhaps with sound. 

I am assuming you likely did some interviews for the initial visual design as well. I'll check with @emily-phet if I need to make note of those interviews, too.

**Comment by arouinfar** [comment]
@terracoda there have been 3 GFLB interviews conducted under our K-12 interview protocol with 8th graders with no visual impairments. Two of the interviewees used a version with sonification, and one interview predated the sound design. I've added all three to the spreadsheet.

**Comment by terracoda** [comment]
@arouinfar, you are amazing! Thanks!

**Comment by terracoda** [comment]
I think we can close this issue now that all interviews are recorded in the spreadsheet.
