### ISSUE TITLE
Screen reader not reading out adjusted force if mass moved twice

### ISSUE THREAD

**Issue by etwa4650** [phetsims/gravity-force-lab-basics#146]
For  https://github.com/phetsims/QA/issues/333

<b>Test Device</b>

Jordan

  <b>Operating System</b>

Mac OS 10.14.5

  <b>Browser</b>

  Safari 12.1.1

  <b>Problem Description</b>

  If either mass if moved more than once in either direction, the screen reader will read the new distance of the two masses, but it will not read out the new adjusted force.

  <b>Steps to Reproduce</b>

  1: Go to the sim, turn on Voice Over
  2: Using keyboard nav, select a mass
  3: Move the mass with the arrow keys at least twice in one direction

  <b>Visuals</b>

 https://drive.google.com/open?id=16wYOZK75nVWuJ9aPZKKshZ6KvugHFhld

**Comment by terracoda** [comment]
Nice find etwa4650.

@zepumph, I can reproduce this, and after 1 step VoiceOver recovers, and also three quick steps does not seem to cause the alerts to stop. I have no idea why the alerts would stop only after two quick steps.

Any ideas?

**Comment by terracoda** [comment]
This does not happen on the Mass number-spinner-sliders.

**Comment by terracoda** [comment]
@jessegreenberg and @zepumph, just an FYI that this might nit be a new bug. VoiceOver recovers quite easily, so it is not something that really sticks out. That said, I can reproduce it easily.

**Comment by jessegreenberg** [comment]
Thanks for reporting. I am not able to reproduce with NVDA. @zepumph I will have access to a mac on Friday, I can take a look then.

It sounds like we are missing the alert content. I can see the alerts in the a11y-view. My initial guess would be to increase the `alertStableDelay` of ValueChangeUtterance (unfortunate because it is already quite long).

**Comment by terracoda** [comment]
@jessegreenberg, I agree, I am not sure we want to increase the delay, but we can see if that has something to do with it.

**Comment by zepumph** [comment]
@jessegreenberg thanks, let me know if there is anything I can do to help.

**Comment by jessegreenberg** [comment]
This doesn't happen every time you press arrow keys multiple times in a row, but it happens frequently. I still haven't been able to get it to happen for the mass spinners.

**Comment by jessegreenberg** [comment]
OK, so I *think* this is related to the length of the text used in `aria-valuetext`. I was able to produce the issue in this example:
<details>

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>title</title>
  </head>
  <body>

    <input type="range" id="range-1" aria-orientation="horizontal">
    <input type="range" id="range-2">

    <p id='live-element' aria-live="polite"></p>
  
  </body>

  <script type="text/javascript">
    const range1 = document.getElementById( 'range-1');
    const range2 = document.getElementById( 'range-2');
    const liveElement = document.getElementById( 'live-element' );

    let counter = 0;
    let timeoutId = null;
    const alertLater = ( alert ) => {
      if ( timeoutId !== null )
      window.clearTimeout( timeoutId );

      timeoutId = window.setTimeout( () => {
        liveElement.textContent = alert + ' ' + (++counter);
      }, 1000 );
    }

    let topCounter = 0;
    range1.addEventListener( 'change', ( event ) => {
      range1.setAttribute( 'aria-valuetext', 'a very long aria-valuetext string that will take time to read: ' + range1.value );
      alertLater( 'First Slider Changed' );

    } );

    range2.addEventListener( 'change', ( event ) => {
      range2.setAttribute( 'aria-valuetext', 'a very long aria-valuetext string that will take time to read: ' + range2.value );
      
      alertLater( 'Second Slider Changed' );  
  } );
  </script>
</html>
```
</details>

ValueChangeUtterance was added to work around this exact issue but assumed that the value-text would only be spoken once per interaction. In this case, the aria-valuetext is spoken twice or more to notify the user of each value change so we need to wait about the amount of time the screen reader reads all of the `aria-valuetext` before speaking an alert so VoiceOver doesn't ignore it.

We should submit a bug report to Apple about this, alerts should be working in this case.

We could probably work around this by creating a method that is like "make alertStableDelay dependent on the speed at which the user changed an input value so that VoiceOver has time to read queued aria-valuetext updates". We would probably add this workaround in AccessibleValueHandler.

**Comment by jessegreenberg** [comment]
This diff is sort of what I was thinking, but I haven't tested it with GFLB yet.
<details>

```diff
diff --git a/js/accessibility/AccessibleValueHandler.js b/js/accessibility/AccessibleValueHandler.js
index 46e6db4..d43a327 100644
--- a/js/accessibility/AccessibleValueHandler.js
+++ b/js/accessibility/AccessibleValueHandler.js
@@ -31,6 +31,8 @@ define( require => {
   const SunConstants = require( 'SUN/SunConstants' );
   const timer = require( 'AXON/timer' );
   const Util = require( 'DOT/Util' );
+  const utteranceQueue = require( 'SCENERY_PHET/accessibility/utteranceQueue' );
+  const ValueChangeUtterance = require( 'SCENERY_PHET/accessibility/ValueChangeUtterance' );
 
   const AccessibleValueHandler = {
 
@@ -127,6 +129,10 @@ define( require => {
              */
             a11yCreateValueChangeAriaValueText: _.identity,
 
+            a11yCreateValueChangeAlert: () => {
+              return 'Alert Generated';
+            },
+
             /**
              * List the dependencies this Node's PDOM descriptions have. This should not include the valueProperty, but
              * should list any Properties who's change should trigger description update for this Node.
@@ -247,6 +253,19 @@ define( require => {
           // @private - {null|function} see options for doc
           this.a11yCreateOnFocusAriaValueText = options.a11yCreateOnFocusAriaValueText;
 
+          // @private {null|function} see options for doc
+          this.a11yCreateValueChangeAlert = options.a11yCreateValueChangeAlert;
+
+          // @private {number} - number of times the input has changed in value before the valueChangeUtterance made
+          // was able to be spoken, only applicable if using a11yCreateValueChangeAlert
+          this.timesChangedBeforeAlerting = 0;
+
+          // @private - The utterance sent to the utteranceQueue when the value changes, alert content generated by
+          // optional a11yCreateValueChangeAlert. The alertStableDelay on this utterance will increase if the input
+          // receives many interactions before the utterance can be announced so that VoiceOver has time to read the
+          // aria-valuetext before the alert.
+          this.valueChangeUtterance = new ValueChangeUtterance();
+
           this.setA11yDependencies( options.a11yDependencies );
 
           // listeners, must be unlinked in dispose
@@ -265,7 +284,7 @@ define( require => {
 
           // when the property changes, be sure to update the accessible input value and aria-valuetext which is read
           // by assistive technology when the value changes
-          const valuePropertyListener = () => {
+          const valuePropertyListener = ( value, oldValue ) => {
 
             const formattedValue = this.getA11yFormattedValue();
 
@@ -276,6 +295,23 @@ define( require => {
 
             // update the PDOM input value on Property change
             this.inputValue = formattedValue;
+
+            if ( this.a11yCreateValueChangeAlert ) {
+              this.valueChangeUtterance.reset();
+              
+              this.valueChangeUtterance.alert = this.a11yCreateValueChangeAlert( formattedValue, value, oldValue );
+
+              if ( utteranceQueue.hasUtterance( this.valueChangeUtterance ) ) {
+                this.timesChangedBeforeAlerting++;
+              }
+              else {
+                this.timesChangedBeforeAlerting = 1;
+              }
+              const delayTime = this.timesChangedBeforeAlerting * ValueChangeUtterance.DEFAULT_STABLE_DELAY;
+              this.valueChangeUtterance.alertStableDelay = delayTime;
+
+              utteranceQueue.addToBack( this.valueChangeUtterance );
+            }
           };
           this._valueProperty.link( valuePropertyListener );
 
```
</details>

@zepumph what do you think about this? It adds complexity to AccessibleValueHandler. It is brittle because it only works with certain user settings. That is true for ValueChangeUtterance, but this increases the investment into this workaround. It is an issue with VoiceOver and I don't know if we should spend time changing AccessibleValueHandler and slider usages for this.

On the other hand, is it generally beneficial to have a valueChangeUtterance come with AccessibleValueHandler since often we want `aria-valuetext` followed immediately by an aria-live alert?

**Comment by zepumph** [comment]
@jessegreenberg let's talk about this tomorrow! @twant and I noticed the following thoughts:

* multiplying by 1000 seems like a large coefficient, perhaps there is a better number we can find.
* I don't yet see how `timesChangedBeforeAlerting` correlates to the length of the alert itself. Isn't the length of the alert the factor that changes how VO ignores some alerts?

**Comment by jessegreenberg** [comment]
> multiplying by 1000 seems like a large coefficient, perhaps there is a better number we can find.

There definitely could be, it just seemed like a reasonable starting place. 1000 was determined to be a decent workaround value for this issue when there is only one aria-valuetext to read. So the thought was to multiply this by the number of times we expect aria-valuetext to be read when keys are pressed multiple times.

>  Isn't the length of the alert the factor that changes how VO ignores some alerts?

From what I have seen, it is the length of the aria-valuetext, not the length of the alert. So this variable represents the number of times we expect VO to read an aria-valuetext before reading an alert.

**Comment by jessegreenberg** [comment]
I was preparing a bug report for Apple when I realized that the example HTML where this is happening is still pretty complicated.  And when I removed the window.setTimeout in https://github.com/phetsims/gravity-force-lab-basics/issues/146#issuecomment-502835994 the problem went away.

So this isn't as straight forward as I thought, its more like there is a window of time where sending an alert to VoiceOver is bad. If set immediately on `change`, all is well. If set ~1000 ms after, things are bad if the user changes the value more than once.  Ill try https://github.com/phetsims/gravity-force-lab-basics/issues/146#issuecomment-502865700 in the example HTML before we decide to go further with it.

**Comment by jessegreenberg** [comment]
This HTML does resolve the issue.
<details>

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>title</title>
  </head>
  <body>

    <input type="range" id="range-1">
    <input type="range" id="range-2">

    <p id='live-element' aria-live="polite"></p>
  
  </body>

  <script type="text/javascript">
    const range1 = document.getElementById( 'range-1');
    const range2 = document.getElementById( 'range-2');
    const liveElement = document.getElementById( 'live-element' );

    let counter = 0;
    let timeoutId = null;
    let changeCountBeforeAlerting = 0;
    let alertContent = null;

    const alertLater = ( alert ) => {
      'use strict';

      window.clearTimeout( timeoutId );

      if ( alertContent !== null ) {
        changeCountBeforeAlerting++
      }
      else {
        changeCountBeforeAlerting = 0;
      }

      alertContent = alert + ' ' + (++counter);

      timeoutId = window.setTimeout( () => {
        liveElement.textContent = alertContent;

        alertContent = null;
        changeCountBeforeAlerting = 0;
      }, 1000 * ( changeCountBeforeAlerting + 1 ) );
    }

    let topCounter = 0;
    range1.addEventListener( 'change', ( event ) => {
      range1.setAttribute( 'aria-valuetext', 'a very long aria-valuetext string that will take time to read: ' + range1.value );
      alertLater( 'First Slider Changed' );

    } );

    range2.addEventListener( 'change', ( event ) => {
      range2.setAttribute( 'aria-valuetext', 'a very long aria-valuetext string that will take time to read: ' + range2.value );
      
      alertLater( 'Second Slider Changed' );  
  } );
  </script>
</html>
```
</details>

As @zepumph and @twant mentioned, this delay is probably much longer than it needs to be. VO reads at most 2 aria-valuetext updates when keys are pressed multiple times, so maybe we just need to delay by 1000 * 2 ms in this case.

**Comment by zepumph** [comment]
@jessegreenberg and I worked on this, basically committing the diff that @jessegreenberg created in https://github.com/phetsims/gravity-force-lab-basics/issues/146#issuecomment-502865700. We found that it worked very well, and couldn't reproduce the bug with the changes, but there are a lot of factors at play here:
* Once we reverted changes, and tested phettest, it was particularly hard to reproduce the bug (though it was still possible)
* We only tested one rate of talking for VO
* Things sounded good on NVDA firefox/chrome

We didn't commit our hacky changes to GFLB, so currently there is no way to test this. I will work on a better solution this afternoon, and then ask @terracoda to review.

**Comment by zepumph** [comment]
@jessegreenberg refreshed phetdev (dev.39) and now the bug is much more reproduce-able. How strange!

**Comment by zepumph** [comment]
@terracoda I added some temporary code to GFLB so that we could test this out. If it seems like the direction we should go, then I can clean it up. Let me know what you think.

**Comment by terracoda** [comment]
@zepumph, I think you nailed it. The alerts are no longer stopping. Assigning back to you.

**Comment by KatieWoe** [comment]
May be related to this known issue:
>[Safari, VO] Sometimes VoiceOver will stop reading “value” information when a slider is moved with the keyboard. See https://github.com/phetsims/sun/issues/508 and https://github.com/phetsims/ohms-law/issues/141

If it is and the above solution is effective, it may be worth expanding to other sims.

**Comment by terracoda** [comment]
Thanks @KatieWoe for tagging those issues. I'll let @zepumph comment, but I don't think either of those issues are related. The Ohm's Law issue was about information in `aria-valuetext` not being read out whereas this one is about information in an `aria-live` region not being read out.

I'll let @zepumph comment further about whether this issue is completed and ready to close.

**Comment by jessegreenberg** [comment]
I think this is ready to be closed, but I did happen on one last todo from https://github.com/phetsims/gravity-force-lab-basics/issues/156:
```js
      this.positionUtterance = new ValueChangeUtterance(); // TODO: delete me depending on https://github.com/phetsims/gravity-force-lab-basics/issues/146
```

Usages are already commented out so I think this can be removed, but I will let @zepumph comment for certain.

**Comment by jessegreenberg** [comment]
Ah I see some other TODO code related to this so it may not be quite ready
> refactor this better if we decide to do it, alertPositionUnchanged too, https://github.com/phetsims/gravity-force-lab-basics/issues/146

**Comment by zepumph** [comment]
I did the needed refactoring, and now the only things pointing to this issue are the warnings @jessegreenberg and I added purposefully. I think this is ready to close. @terracoda can you just give a once over to make sure the descriptions still sound as expected?

**Comment by terracoda** [comment]
@zepumph, all still sounds good on MacOS 10.13.6 with VoiceOver and Safari 12.1.1.
