### ISSUE TITLE
ISLCObjectEnum should be `Enumeration`

### ISSUE THREAD

**Issue by zepumph** [phetsims/gravity-force-lab-basics#147]
From https://github.com/phetsims/gravity-force-lab-basics/issues/134, this really feels right, and it would make small bugs like passing in undefined instead of an enum a bit easier. For example a method like this is sloppy:

```js
    /**
     * @param {ISLCObjectEnum} objectEnum
     * @returns {string}
     */
    getOtherObjectLabelFromEnum( objectEnum ) {
      return objectEnum === OBJECT_ONE ? this.object2Label : this.object1Label;
    }

```

**Comment by zepumph** [comment]
@jessegreenberg please review this as part of the code review at large. I tried to move as much static content into the Enumeration as possible.

**Comment by jessegreenberg** [comment]
Looks great, I agree making this an Enumeration is right. My only nit-pick is about formatting, I think it is atypical to create the Enumeration inline with the inverseSquareLawCommon.register call. Modified in the above commit, does this seem reasonable?

**Comment by zepumph** [comment]
No strong preference here, just note that a search for `, new Enumeration` yields 10 others. Ready to close if you are.

**Comment by zepumph** [comment]
(also I don't see the commit in this issue)

**Comment by jessegreenberg** [comment]
>  just note that a search for , new Enumeration yields 10 others

Indeed, I sit corrected. I reverted the change. This issue can be closed.
