### ISSUE TITLE
GFLBMassNode to extend MassNode?

### ISSUE THREAD

**Issue by zepumph** [phetsims/gravity-force-lab-basics#150]
Discovered as part of https://github.com/phetsims/gravity-force-lab-basics/issues/134. This will save code (a real commodity these days) and complexity, especially duplication in `updateGradient`.

**Comment by zepumph** [comment]
@jessegreenberg @twant and I feel pretty good about this. Could you please review for regression, as well as two new points:

* Does the way of using options to support inheritance here make sense?
* Notice that the updateGradient has a conditional about if constantRadius is checked or not. That was not in GFLB. Is it alright that it is now in GFLB? I couldn't see any changes, but you are the responsible dev.

**Comment by zepumph** [comment]
>Notice that the updateGradient has a conditional about if constantRadius is checked or not. That was not in GFLB. Is it alright that it is now in GFLB? I couldn't see any changes, but you are the responsible dev.

I changed my mind. I can tell a difference when the stroke is present. I think it looks good in GFLB. @jessegreenberg can you think of a reason that it was purposefully omitted?

**Comment by jessegreenberg** [comment]
Code looks really nice to me, thanks! I searched through commit history and repo issues in here, GFL, and ISLC and couldn't find anything about lack of stroke. I assume that this visual change is totally great. I actually think it looks better. Closing this issue.
