### ISSUE TITLE
QA credits & A11y Team credits

### ISSUE THREAD

**Issue by zepumph** [phetsims/gravity-force-lab-basics#154]
To make sure we don't forget.

**Comment by terracoda** [comment]
**Currently listed folks as of June 18, 2019**
<img width="638" alt="GFLB-credits-June18" src="https://user-images.githubusercontent.com/1902116/59751384-b617e800-9280-11e9-8f21-a73d7d163ec2.png">

**Comment by terracoda** [comment]
**Updates to team list:**
- [ ] - Team list - change Emily Moore to Emily B. Moore, and add Brianna Tomlinson

**Comment by terracoda** [comment]
@emily-phet could you verify my comment above https://github.com/phetsims/gravity-force-lab-basics/issues/154#issuecomment-503473793 , please?

**Comment by emily-phet** [comment]
👍

**Comment by terracoda** [comment]
@zepumph, for the A11y folks, you just need to change Emily's name and add Brianna Tomlinson.
Assigning issue to you.

**Comment by terracoda** [comment]
@zepumph, this issue is still on your radar, right?

**Comment by zepumph** [comment]
Definitely!

**Comment by zepumph** [comment]
And https://github.com/phetsims/resistance-in-a-wire/issues/208

**Comment by zepumph** [comment]
Alright. From here we will wait for final QA credits.

**Comment by terracoda** [comment]
A11y Team verified! Thanks @zepumph.
<img width="793" alt="credits-gflb" src="https://user-images.githubusercontent.com/1902116/60578787-209d4d80-9d82-11e9-841e-43da98b6a95a.png">

**Comment by KatieWoe** [comment]
Add Logan Bray to QA

**Comment by zepumph** [comment]
Credits have been updated in master and on the 1.0 branch. Closing
