### ISSUE TITLE
lint with sim_es6_eslintrc_review

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/gravity-force-lab-basics#157]
I noticed a handful of lint issues, mostly about line length. And the one for GFLBModel doesn't look wrong or worth fixing. Instead of a sim fix, I am wondering if this item should be removed or sim_es6_eslintrc_review changed.

![image](https://user-images.githubusercontent.com/6396244/60311067-92f5d400-9923-11e9-848e-93f104679f0d.png)

@zepumph what do you think?

**Comment by jessegreenberg** [comment]
For #157.

**Comment by zepumph** [comment]
>I am wondering if this item should be removed or sim_es6_eslintrc_review changed.

I think that has been discussed before. To me I normally just think of the review rules as guidelines. We can bring it up at a dev meeting though if you feel strongly.

**Comment by jessegreenberg** [comment]
OK thanks, Ill create an issue in chipper because I don't really understand the purpose of sim_es6_eslintrc_review. Nothing is sim specific so I think this can be closed.
