### ISSUE TITLE
Disposal of PhET-iO objects

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/gravity-force-lab-basics#158]
From #156, I am not certain how to test this. This sim is listed as a phet-io sim so it should probably be considered. 

>  TANDEM: PhET-iO instrumented PhetioObject instances should be disposed.

@zepumph what should I be looking for for this?

**Comment by jessegreenberg** [comment]
Oh, I just saw his documentation in implementation-notes.md

>There are no dynamic pieces to this simulation, and as a result nothing is disposed.  As a result no listeners need to be unlinked or removed.

So maybe this can just be closed. But perhaps there are things to think about still, so would be helpful for @zepumph to comment.

**Comment by jessegreenberg** [comment]
I ran fuzz/memory tests with this sim in studio and saw similar memory profiles to https://github.com/phetsims/gravity-force-lab-basics/issues/139, so I don't see evidence of a leak.

**Comment by zepumph** [comment]
I think of tandem references as similar to axon listeners in terms of managing disposal. I don't think there is anything left here.
