### ISSUE TITLE
branch: describer-temp

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/gravity-force-lab-basics#160]
From the code review checklist, https://github.com/phetsims/gravity-force-lab-basics/issues/156

>  In GitHub, verify that all non-release branches have an associated issue that describes their purpose.

@zepumph can this branch be removed now? If not, can you describe why it is useful to keep?

**Comment by zepumph** [comment]
This branch has been deleted in all three repos. Closing

**Comment by zepumph** [comment]
Should be re-deleted as part of phetsims/special-ops#198

**Comment by zepumph** [comment]
Deleted
