### ISSUE TITLE
Tyepdoc for describers

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/gravity-force-lab-basics#161]
@zepumph could you please add typedoc for the files under gravity-force-lab-basics/view/describers?

For #156

**Comment by jessegreenberg** [comment]
Also GFLBAlertManager and the supertypes for a few of these are missing typedoc as well.

**Comment by zepumph** [comment]
How's that?

**Comment by jessegreenberg** [comment]
Typedoc was truly added this day. I added author annotations to ensure those props. Thanks!
