### ISSUE TITLE
How were the ranges for get*Index methods chosen?

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/gravity-force-lab-basics#162]
@zepumph can you add documentation for how these were chosen? The increments look like they are roughly the same but not quite. The set up for these seems a little bit fragile because if numberOfRegions or any of the region sizes change, all will likely need to be updated manually. I was trying to think if there was a way to calculate these empirically, but I don't know if that is possible if the ranges for each index need to be unique.

**Comment by jessegreenberg** [comment]
> if numberOfRegions or any of the region sizes change, all will likely need to be updated manually.

That is actually not true, since the conditionals use >= for each, they are independent. And the assertions will ensure that this receives work if the numberOfRegions change. So perhaps all that is needed is documentation about why values were chosen.  For instance, getForceVectorIndex sections things in a linear way, but getDistanceIndex is non-linear when the masses are close together.

**Comment by zepumph** [comment]
I actually added `numberOfRegions` to try to make sure that things would always fail loudly. We could remove that if the assertion is not really needed (because it may be obvious?). 

Otherwise, note that all of these values were manually designed, and empirically determined, largely from @terracoda playing with the sim. I'll link the design doc in these comments. 

Anything else here @jessegreenberg?

**Comment by jessegreenberg** [comment]
Great, I think failing loudly is a good thing. I think those lines of documentation are all that is needed, and the table in the design doc is nice to see! Thanks for adding this.

**Comment by terracoda** [comment]
@jessegreenberg and @zepumph, regarding:

> ...note that all of these values were manually designed, and empirically determined, largely from @terracoda playing with the sim. I'll link the design doc in these comments.

Generally, I like to play with the sim to get a rough estimate of ranges, but if there is a way to calculate the ranges using the model, and the end result still matches visually what is one the screen, I would go with calculated ranges.

When I play with the sim for ideas, I am not able to account for all possibilities and all parameters.

Also, @zepumph 
>  I'll link the design doc in these comments.

I think we should discuss this strategy (both for github issues and code), as I sometimes remove stuff from the design docs after implementation is working. Hmm, I haven't been treating the design doc like a lab book.

**Comment by zepumph** [comment]
I haven't linked to the design doc often, but I think it is reasonable for a case like this because of how "arbitrary" the number are, at least in terms of the model.

**Comment by terracoda** [comment]
@zepumph, ok good to know that there are not too many dead links to design docs ;-)
When there is "Holly Wooding" in the visuals, there will need to be a similar "Holly Wooding" in the description. At the beginning of the design of this sim, I was told that the "Holly Wooding" done on this sim was on the visual size of the force vectors.

Maybe it would be a good practice to more clearly define what visuals may not be driven directly by the model at the start of the A11y design process? I found it useful to review the model properties at the start of this sim.

**Comment by zepumph** [comment]
>I found it useful to review the model properties at the start of this sim.

I think this is relatively well understood by the a11y design team as a beneficial piece of information.

>Maybe it would be a good practice to define more clearly what visuals may not be driven directly by the model (i.e., have had some "Holly Wooding") at the start of the A11y design process?

That sounds like a great thing to formalize.


Are either of these written down in a checklist of some sort? I'm not sure what there, but perhaps they could work well in the "design" section of the a11y master checklist.

**Comment by terracoda** [comment]
> Are either of these written down in a checklist of some sort? I'm not sure what there, but perhaps they could work well in the "design" section of the a11y master checklist.

@zepumph, great idea, I will add these 2 points to the lessons learned section and make note to add to the check list template I am working on

**Comment by terracoda** [comment]
@zepumph, I updated the lessons learned and and made a TODO note for myself about the issue template. Please close this issue when ready.
