### ISSUE TITLE
Possible uneccessary constants in GravityForceLabAlertManager

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/gravity-force-lab-basics#163]
For #156, and possibly part of #147, can this constant be deleted now?

```js
  const { OBJECT_ONE, OBJECT_TWO } = ISLCObjectEnum;
```

**Comment by zepumph** [comment]
@jessegreenberg I was able to get rid of those constants through another access of the usage. I also added more assertions, which I think will help with maintainability. Anything else here?

**Comment by jessegreenberg** [comment]
Byoutiful.
