### ISSUE TITLE
Update to Keyboard Shortcuts dialog's A11y Content due to visual design change

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#171]
For GFL regular, see issue https://github.com/phetsims/gravity-force-lab/issues/139, I  requested a design change that also affected GFLB. 

Both new dialogs look fine, but the A11y content no longer matches the visual. Please see comment https://github.com/phetsims/gravity-force-lab/issues/139#issuecomment-521758304 for the requested content updates.

**Comment by zepumph** [comment]
Completed over in https://github.com/phetsims/gravity-force-lab/issues/139. Closing

**Comment by terracoda** [comment]
@zepumph, re-opening due to further visual changes to the keyboard dialog. As mentioned in the design doc, I think it would be great to have 3 common code options for providing instructions for sliders:

The three common-code options I see are:
1. include all functionality of the slider in the instructions
2. for pedagogical reasons only provide horizontal instructions
3. for pedagogical reason only provide vertical instructions

Hopefully, this is the right place for this issue.

**Comment by zepumph** [comment]
I'm not sure I understand what you would like to do here. Likely it deserves an new issue. Do you want to try to convert out custom keyboard help section ("Move Spheres") to be a general one?

**Comment by terracoda** [comment]
I think I put this issue in the wrong repo.

**Comment by terracoda** [comment]
I think this is supposed to be in the RaP repo.

**Comment by jessegreenberg** [comment]
@terracoda can this be re-closed? Was this moved to ratio-and-proportion?

**Comment by zepumph** [comment]
Yes rap was taken care of.

**Comment by terracoda** [comment]
Ok, sounds good closing.
I think I originally put it in this common code repo, so we could have a common shared set of possible options for for defining slider interactions in the keyboard help dialog. We tend to do different things depending on the actual sim and slider (show only left/right arrows, show only up/down arrows, or show all arrows).
