### ISSUE TITLE
Closer/Farther Away not always given

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-force-lab-basics#175]
For https://github.com/phetsims/QA/issues/429.  Noticed in NVDA, but it occurs in the a11y view.  If this is intentional please close.
Sometimes, often when interrupting a previous movement, the screen reader will skip the "Closer" or "Farther Away" part of the following type of alert.  I also wondered if it would be a good idea to include the exact distance in the alert.
> Farther away, force arrows get smaller, forces now 26.4 ‪newtons‬.

**Comment by KatieWoe** [comment]
Edit: Never mind about including the exact distance.  It does, but it doesn't seem to show up in the a11y view for some reason.

**Comment by terracoda** [comment]
@KatieWoe, nice that you noticed this. What is spoken out by the screen reader, the "alertive information" is actually a combination of two things:
1. the changed value on the slider, in this case the new value for distance, and 
2. a description of other important contextual changes, a description of the size of the force arrows and the new force value. When there is a change is a change in direction, you will also here "Closer" or "Farther away".

In the newly refined model of our descriptions we call
- Number 1 above an Object Response, and 
- Number 2 above a Context Response 

Currently, in the A11y View Object Responses are displayed over in the blue side near the sliders whereas what currently shows up in the Orange box is only the Context Response. 

So if you are only hearing "Close/Farther away" on directional changes, that is correct behaviour.

**Comment by terracoda** [comment]
@KatieWoe, I'll add, by directional change, I mean if you change from getting closer to getting farther away and you don't hear "Closer/Farther away" then there is an issue. 


Also at the edges, you get "Last stop left/right", and when distance is not checked you get qualitative descriptions of the distance, but you only get them when you cross a regional boundary. You don't get the qualitative changed distance on each step like you do with distance checked. The Distance checked option provides quantitative granularity whereas Distance not checked provides a rough description of the distance when that rough description changes.

**Comment by KatieWoe** [comment]
All looks good in that case.  Only thing I would note is that, if you change direction and continue moving, you won't hear "Closer/Farther away."  You only seem to hear it if you stop after changing direction.

**Comment by terracoda** [comment]
@KatieWoe, I don't understand. You should only hear "Closer" on your first step closer to the other sphere, and you should only hear "Farther away" on your first step away from the other sphere.

And then again when you change from going closer or farther away.
It's that first step that matters, and that first step happens on literally the first step and in all subsequent changes in direction.

On subsequent steps in the same direction we don't say "Closer/Farther away" again> This is by design to make the description shorter.
1. step closer - "Closer, force arrows get bigger ..."
2. step still closer - "Force arrows get bigger ..."
3.  step away - "Farther away, force arrows get smaller ..."
4. step still farther away - "Force arrows get smaller ..."

@KatieWoeAre, you should hear the above pattern consistently, are you hearing something different?

**Comment by KatieWoe** [comment]
Basically, if you do step 2 before words from step 1 start or you do step 4 before words from step 3 start you don't hear closer, farther away.  Does that make sence?

**Comment by terracoda** [comment]
@KatieWoe and I discussed and this is typical screen reader interruption.

**Comment by KatieWoe** [comment]
Closing

**Comment by terracoda** [comment]
No need to fix, it is not a bug. Removing label and closing.

**Comment by zepumph** [comment]
Thanks @terracoda! @KatieWoe is this a specific enough screen reader case to be documented as expected behavior somewhere?

**Comment by KatieWoe** [comment]
I think it's fairly specific to this sim, but I could be wrong.

**Comment by terracoda** [comment]
Good question @zepumph, this will happen more when we have really customized stepping descriptions like in this sim. It happens less so with the mass sliders as we do not describe directional changes.

Basically, it will happen when there are more than a few nuances trying to be conveyed. In previous sims, we used `aria-valuetext` to convey some of these nuances, but we will likely be using `aria-live` to convey these nuances going forward as `aria-valuetext` is not read out on mobile VoiceOver.
