### ISSUE TITLE
Investigate best min and max values for mass sliders

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#181]
From issue https://github.com/phetsims/QA/issues/429#issuecomment-537071949

JAWS screen reader reads out the `min `and `max` values for the mass sliders which sounds like 1 zero zero zero zero...

```html
min="1000000000" max="10000000000" step="1000000000"
```
VoiceOver only seems to read out the `aria-valuetext` of the current value which sounds like "4 billion kilograms"

Is it possible to use simplified values instead?
```html
min="1" max="10" step="1"
```

Of course the `aria-valuenow` attribute would also need to change to a single digit.

@zepumph, is this possible without messing up the numbers needed for the actual model?

**Comment by zepumph** [comment]
This thought adds another layer of complexity to AccessibleValueHandler. Currently here are the supported options that involve mapping a value to something in the PDOM:

* **a11yValuePattern**: // {string} if you want units or additional content, add to pattern
* **a11yDecimalPlaces**: // number of decimal places for the value when formatted and read by assistive technology
* **roundToStepSize**: // {boolean} - Whether or not to round the value to a multiple of the  keyboardStep.
* **a11yMapValue**: // Map the valueProperty value to another number that will be read by the assistive device on valueProperty changes. {function(number):number}
* **a11yRepeatEqualValueText**: // If true, the aria-valuetext will be spoken every value change, even if  the aria-valuetext doesn't actually change.
* **a11yCreateValueChangeAriaValueText**: // Custom aria-valuetext creation function, called when the valueProperty changes.
* **a11yCreateValueChangeAlert**: // Create content for an alert that will be sent to the utteranceQueue when the user interacts with the input.


I wanted to give an overview of current options in case we could try to co-opt some into something that could be supported for this case. I don't want to just add something else on top.

That said, it seems like what we need here is a `modelViewTransform` type thing, that maps from values in the PDOM slider to actual model values. Currently, `AccessibleValueHandler`, is taking the min/max and value directly from the valueProperty and rangeProperty. By "directly" I mean that the value passes through "a11yMapValue" but the min/max currently aren't. Perhaps that is the function we need.

**Comment by terracoda** [comment]
@zepumph, I think you are correct, we need something that says:
- 1 in the PDOM mass slider == 1 000 000 000 in the sim's model

In the options above, my first guess would be the **a11yMapValue** option, just as you have pointed out.

>  Map the valueProperty value to another number that will be read by the assistive device on valueProperty changes. {function(number):number}

So would that translate to:
- pdom number = sim number/1 000 000 000

**Comment by zepumph** [comment]
Over in https://github.com/phetsims/sun/issues/530 we worked on a11yMapValue, and were able to get things working for this issue. This is now what the input looks like:

https://github.com/phetsims/sun/issues/530
![image](https://user-images.githubusercontent.com/6856943/66011584-27fef080-e470-11e9-9af8-6384ce94cd4a.png)


There is some concern that to get the `step` like this, we used a pretty sim-specific implementation, but I think that will be sorted out as part of https://github.com/phetsims/sun/issues/530#issuecomment-537298651

@terracoda can you please review master before we merge changes over to the rc branch?

**Comment by terracoda** [comment]
I hadn't actually experienced this read out (recently anyways) until today before I emptied my caches:
<img width="1161" alt="Screen Shot 2019-10-02 at 2 04 32 PM" src="https://user-images.githubusercontent.com/1902116/66063760-9ef2c280-e51e-11e9-8778-2f23423ee2c4.png">

Happily, after I emptied my caches and reloaded from master, I got the beautiful `aria-valuetext` and no more 2000000000:
<img width="1161" alt="Screen Shot 2019-10-02 at 2 08 12 PM" src="https://user-images.githubusercontent.com/1902116/66063903-e711e500-e51e-11e9-9f53-dc5d7bf134c1.png">

Nice work! I think you can move to RC branch! Assigning back to you @zepumph!

**Comment by zepumph** [comment]
Yes I think there is more work to be done, but that will be over in https://github.com/phetsims/sun/issues/530.

**Comment by terracoda** [comment]
Ok, closing ;-)

**Comment by zepumph** [comment]
Sorry I'm a liar. We should keep this open for QA to ensure the fix makes it successfully into the release branch.

**Comment by zepumph** [comment]
I will commit the following commits to branches over in phetsims/gravity-force-lab-basics#179, in order:

From https://github.com/phetsims/sun/issues/530:
ISLC:
https://github.com/phetsims/inverse-square-law-common/commit/1d370943cbb0546246564a8545a88ea32c70fc03
https://github.com/phetsims/inverse-square-law-common/commit/b2132e76060f58f52e729ca044c4671b9828b620

GFLB:
https://github.com/phetsims/gravity-force-lab-basics/commit/a95d67911e8544be2f9b76dcdcb3f8996a9c1b94

GFL:
https://github.com/phetsims/gravity-force-lab/commit/01b59adf8b3e5735b0f81340b33533767aad4c8f

SUN:
https://github.com/phetsims/sun/commit/f0365368ded7655d0bb4c627e269121e69a90cbd
https://github.com/phetsims/sun/commit/b365934979769a55176655930e892ec921b21ccf

https://github.com/phetsims/sun/commit/f65e4de81bfd082e4354135fc45f833e80f33e85
https://github.com/phetsims/sun/commit/3667e406afaeba0962a5ffdd8bd5d4d0e8bf6f88
https://github.com/phetsims/sun/commit/4e588f4eb1bbcf8a6cd368f7e02b3e6cd2f3252d
https://github.com/phetsims/sun/commit/7006f9f2e2f1d860cf30504a9da2416ee9b53d10
https://github.com/phetsims/sun/commit/40ab4e669818cb631bf2784c2e5512425f061097

Then these:
SUN: https://github.com/phetsims/sun/commit/3667e406afaeba0962a5ffdd8bd5d4d0e8bf6f88
GFLB: https://github.com/phetsims/gravity-force-lab-basics/commit/477075b9366e6bae8634c8da7895e2d486919c39

**Comment by zepumph** [comment]
QA: to tests, the bug is described in https://github.com/phetsims/gravity-force-lab-basics/issues/181#issue-500964619, basically there shouldn't be many zeros read out for the min/max values. I think this was only present for JAWS.

**Comment by loganbraywork** [comment]
Issue fixed
