### ISSUE TITLE
Should get "closest" alert when closest with a constant radius

### ISSUE THREAD

**Issue by zepumph** [phetsims/gravity-force-lab-basics#183]
Will be needed for https://github.com/phetsims/gravity-force-lab-basics/issues/179

**Comment by zepumph** [comment]
This was added to master in the above commit by making the constant sized radius the same as the min mass radius in GFLB. I should add this to the release branch.

QA when you get to this, the way to make sure that this made it into the rc is to make sure that when the masses are closest to each other, and you try to move one step closer (but you can't), the alert should start with "Closest" and not "Extremely close". This should be the case with or without constant sized checked.

**Comment by zepumph** [comment]
Cherrypick
https://github.com/phetsims/gravity-force-lab/commit/dbc5b5b2d7e31eaa58c4c7ee70ebabadf0e9fce2
https://github.com/phetsims/gravity-force-lab-basics/commit/f539a487c70a7662326b68f7f9f5ced108ad08f4
https://github.com/phetsims/inverse-square-law-common/commit/6c3c3a0289ab594aa586c7b24961239c356f11eb

**Comment by zepumph** [comment]
QA: to test this, make the masses have a constant radius and the smallest mass, and then move them as close as possible. Afterward, try to move them one step closer, and the alert you get should start with "closest" instead of "extremely close" as would happen if the masses were  a bit larger (without constant size checked).

**Comment by KatieWoe** [comment]
When testing at least NVDA that there could be a noticeable pause before the dialog was read out, but it seemed to work well beyond that.

**Comment by zepumph** [comment]
That is expected and purposeful. We create that pause artificially to make sure there aren't too many alerts. This has be put in front of users and tested. We can open up new issues if we find that is problematic. Thanks @KatieWoe
