### ISSUE TITLE
Ready rc.3

### ISSUE THREAD

**Issue by zepumph** [phetsims/gravity-force-lab-basics#184]
It will be good to keep track of work done in between rc.2 and rc.3. I can do that here

* Over in https://github.com/phetsims/gravity-force-lab-basics/issues/182 there were two bug fixes committed to master and the branch. Nothing more should be needed for them.

**Comment by jonathanolson** [comment]
It looks like the patch for https://github.com/phetsims/phet-core/commit/b9b67611be6138642d25b2c67cbc70ff432fd83d was not applied in the release branch. It should be included somehow.

**Comment by zepumph** [comment]
Alright thanks @jonathanolson, I'll publish a new rc hopefully today with that in it.

**Comment by zepumph** [comment]
So long as we get the all-clear on screen shot over in #24 we will be ready for this final (?) RC.

**Comment by zepumph** [comment]
https://github.com/phetsims/QA/issues/441
