### ISSUE TITLE
Maintenance patches applied to branch 1.0

### ISSUE THREAD

**Issue by phet-dev** [phetsims/gravity-force-lab-basics#186]
This branch (1.0) had changes related to the following applied:

- fix for iOS 13 Full Screen, see https://github.com/phetsims/phet-core/issues/64
- https://github.com/phetsims/scenery/issues/1006

Presumably one or more of these changes is likely to have been applied after the last RC version, and should be spot-checked by QA in the next RC (or if it was ready for a production release, an additional spot-check RC should be created).

**Comment by loganbraywork** [comment]
Both issues seem to be fixed
