### ISSUE TITLE
Hold a postmortem?

### ISSUE THREAD

**Issue by zepumph** [phetsims/gravity-force-lab-basics#187]
@emily-phet @terracoda now that this simulation is published, would you like to hold a postmortem about anything?

**Comment by arouinfar** [comment]
@zepumph we rarely hold postmortems these days. That said, the trajectory has been somewhat unusual for a simulation and it's also the first accessible sim with PhET-iO. There may be some value in holding a postmortem, so I'll also assign @ariel-phet to weigh-in.

**Comment by emily-phet** [comment]
@zepumph Thanks for the reminder! Let's do it!

Since status is canceled for Nov. 7th, perhaps that's an opportune time to gather folks. I'll send out a calendar invite shortly.

**Comment by terracoda** [comment]
For reference we noted a few things in the [lessons learned](https://docs.google.com/document/d/1HdDG9ds2MdbCb21l9qk3cI8yBQxK6-wBWNXC4Tloji8/edit#heading=h.q6eaeefw61wt) section of the design doc

**Comment by emily-phet** [comment]
I just sent out a calendar invite for next Thursday during the status meeting time window. Please let me know if you didn't receive the calendar invite, or if others should be added to the invite list. Looks like Amy is out of town at that time, her invite was auto-declined. Let me know if should not meet without her.
@terracoda @zepumph @jessegreenberg @jbphet @Ashton-Morris

**Comment by terracoda** [comment]
The note from the [Post Mortem meeting](https://docs.google.com/document/d/1HdDG9ds2MdbCb21l9qk3cI8yBQxK6-wBWNXC4Tloji8/edit#heading=h.c3ohqtxoywd) are in the design doc.

**Comment by zepumph** [comment]
Thanks @terracoda. Here is a snapshot of what that section currently looks like for the issue:
History: 
* October 2017 - Considered for a11y stuff
* Dec 2017 - Outfitted for PhET-io and consider for a11y stuff
* March 2018 - Github issue initiating static description work
* July 2018 - Mike Winters some initial setup
* Nov 2018 - Description Design Doc
* Nov 2018 - Producing prototypes
* January 11, 2019 TS opened the description issue: https://github.com/phetsims/gravity-force-lab-basics/issues/84
* July 2019 - Sound design done, not implemented
* October 25, 2019 published

Success:
* TS: Great to work with Amy on the description
* TS: Beneficial to work across multiple related sims (GFL:B/GFLreg). Feeling like there was ‘extra time’ to reflect on the sim since time was shared across multiple related sims.
* MK: Synchronous meeting times really helpful for the process.
* AshM: First sim ‘owned’ sound for - liked to expand sounds without pre-conceived ideas. 
* AshM: Liked “options” feature to help streamline the process. Easier to get feedback from multiple people, good to get feedback on a batch of sound at once.
* JB: Iterative process for the sound design - regular meetings and quick turnarounds on prototypes.
* TS: (comment on github issue checklist usage) I think this was the…
    * MK: It was nice to see this to get an overall idea, but I didn’t look at it closely.

Challenges:
* JB: Sound wasn’t implemented when sim first ready for RC
    * This problem may be improved by new process of prototyping sound on master
* TS: User testing sounds with wrapper added extra step to make sure users were getting latest sound and description
    * Prototyping sound on master addresses this as well
* MK: Descriptions didn’t have strong design pattern base - early discussions recognizing that a 
    * Parallels with sound 
    * TS: example of parallels between sound and description challenges currently being worked on of too much sound when moving slider with mouse, and too much description when moving draggable object with gesture.
    * TS: Emerging structures in description framework - a description component was added in early (by MB) and then later removed (by MK), could have contributed to structural confusion
* MK: Transitioning developers mid-description work, working within existing structures was problematic.
    * MK: complexity from evolving descriptions increased the difficulty here
* MK: Descriptions (?) spans more than one repo, sometimes had to guess at what would be used across multiple sims versus one. Especially when things would change in the design part way through implementation.
* MK: Maintainability - concerns for future work on Coloumb’s Law because they share description code in ISLC (and maybe future work in general across this set of sims).
* AshM: Considering timing of description as part of sound design 

Ideas:
* Demo sims with sound + description in status meetings (and others?) more to increase familiarity with timing/overlaps, etc.
* Could share video from Molarity interview as a general example

Next Steps:
* Dedicated Dev Meeting - (like config and options meeting) 
* JB & MK to discuss if useful: Possible use case example to put to broader team -  too much sound when moving slider with mouse, and too much description when moving draggable object with gesture.
* Conceptual work /discussion needed here, and to try in the next sims.



@emily-phet is there anything else here before closing?

**Comment by emily-phet** [comment]
Looks good to me! I'll mention that we're doing postmortems in the next status meeting, as we talked about today. Closing.
