### ISSUE TITLE
GFL:B Sound Feature Video Script & Recording

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/gravity-force-lab-basics#192]
Make sound features video script and review with team

https://drive.google.com/open?id=1htkNZdHhXRW9xVZGoF_3gfzcnOSedYtR45SvVclNFmc

Recording will happen after.

**Comment by BLFiedler** [comment]
Script completed including relevant updates to GFL script.

https://docs.google.com/document/d/1htkNZdHhXRW9xVZGoF_3gfzcnOSedYtR45SvVclNFmc/edit?usp=sharing

**Comment by emily-phet** [comment]
Made a small tweak and a comment - looks good to go!

**Comment by BLFiedler** [comment]
Draft 1 complete (no intro/outro, might need some sound quality finesse): https://drive.google.com/file/d/1KGXuQwbWbaJ2gP6KVdws-yG2ZXZWwJzG/view?usp=sharing

**Comment by emily-phet** [comment]
@BLFiedler - Very nice! I think it's good to go for publication.

**Comment by BLFiedler** [comment]
Re-recorded for audio and change to pitch language ( "deeper" similar to GFL). Next steps (by end of day tomorrow): Adding intro & outro, uploading to YouTube, Captions, and addition to For Teachers section of simulation webpage.

**Comment by BLFiedler** [comment]
Published

https://www.youtube.com/embed/9KINQMwF2aA
