### ISSUE TITLE
Self-Voicing: Verbose and Brief Explore Modes

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#193]
@jessegreenberg, as I mentioned on slack:

> I sketched out verbose and brief options for the explore mode

The details are here in the Slef-Voicing draft design doc
https://docs.google.com/document/d/1XFTD2HTcGCEOP2yQ9_2SkEeXmCceZYUCmNeyiJfcCHs/edit#heading=h.5id9vnkzd67y

Note that sometimes I have 2 options. If there are two options for a mode, just go with option 1 for now.

Hopefully, I will have more for you by Monday.

**Comment by terracoda** [comment]
The design ideas are a little different than what we discussed doing at last Tuesday meeting. I came up with a verbose version and a brief version.

In neither case do all the string perfectly match what is currently in the Interactive Descriptions. Some verbose ones match and some brief ones match.

The differences in strings are highlighted in red.

If we are not yet set up to a verbose mode and a brief mode, we can choose one and go with that.

**Comment by terracoda** [comment]
@jessegreenberg, I think I am done a first draft of the verbose and brief options for Interactive mode. Let me know if you have any questions.

**Comment by terracoda** [comment]
Actually, I'll start a new issue.

**Comment by terracoda** [comment]
oops didn't mean to close this.

**Comment by jessegreenberg** [comment]
OK thanks! Commits for first pass at prototype made above. Closing this and I wil continue in new issue.
