### ISSUE TITLE
CT testing not being done

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-force-lab-basics#194]
On 3/3/20 most of the CT tests for GFLB stopped being done. See bellow. White spaces are tests not done. Since so many go for such long time without being done consistently, this indicates that something is going wrong.
![notdone](https://user-images.githubusercontent.com/41024075/76002394-c5e56400-5ec3-11ea-980c-21d6f279c8dd.png)
![notdone2](https://user-images.githubusercontent.com/41024075/76002395-c67dfa80-5ec3-11ea-9490-0b50d62ecfc5.png)

**Comment by jonathanolson** [comment]
Tested out a manual test link (https://bayes.colorado.edu/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fsnapshot-1583409094243%2Fgravity-force-lab-basics%2Fgravity-force-lab-basics_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26memoryLimit%3D1000), and it looks like it failed with this:

<img width="1678" alt="Screen Shot 2020-03-05 at 10 15 03 AM" src="https://user-images.githubusercontent.com/480878/76006781-38594280-5eca-11ea-87a4-371977d64017.png">

Looks like gravity-force-lab-basics-main.js has some incorrect imports with too many `../` in it.

**Comment by jonathanolson** [comment]
@jessegreenberg it looks like some incorrect imports were added in https://github.com/phetsims/gravity-force-lab-basics/commit/c580d82df4d146e057cbc200ecd0743c83fc8d7b, and I'm seeing more with inverse-square-law-common's webSpeaker.js. Can you look into this?

**Comment by jonathanolson** [comment]
I believe I fixed the imports issues, can you let me know if this problem continues for the future columns?

**Comment by jessegreenberg** [comment]
Thanks @jonathanolson, new columns have tests running and passing again.
