### ISSUE TITLE
Density and scaling

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/gravity-force-lab-basics#2]
The radii of the bodies are calculated by 

```js
      var sphereVolume = mass / DENSITY;
      var sphereRadius = Math.pow( ( 3 * sphereVolume ) / ( 4 * Math.PI ), 1 / 3 );
```

With a density of ~150 kg/m^3, the radii are much smaller (relative to their 4km gap in between them) than they appear in the mockup:

![capture2](https://cloud.githubusercontent.com/assets/6396244/21231992/630411ee-c2a7-11e6-9b88-7d63c6127d4c.PNG)

The radius of each body in the above is ~150 m.  In order to look like the mockup, the density needs to be ~1kg/m^3.

@arouinfar  how would you like to handle this?  Is a very low densityOK or would you rather change other values? Or maybe the small bodies are fine here.

**Comment by arouinfar** [comment]
@jessegreenberg looks like my original calculations were off by one order of magnitude. For the masses to remain the same size as they are in GFL, the density needs to be ~1.5kg/m^3 which is roughly the density of air. 

In earlier discussions, @ariel-phet and I weren't too keen on having such a low density. However, we've also removed the ruler, which makes it unlikely that the density would be measured. We could also make a note in the teacher tips that the masses are like air-filled balloons.

Alternatively, we could do some re-scaling to the distances. A quick approach would be to double the distances (by relabeling). In the screenshot below, imagine the ruler ticks are marked 0, 2, 4, ... 20. The radius of the blue mass would now be 2km, and the distance between the masses would be 8km (but the physical size of the masses would not change). The density of the masses would then be ~200kg/m^3. Some side effects of this change would be
* At 10 billion kg, the closest the masses could get would be ~5km, meaning the maximum force would be ~267N (down from ~1067N).
* The largest distance between the masses would now be 20 km, so the mimim force would be ~0.2 (down from ~0.67N).

<img width="808" alt="screen shot 2016-12-15 at 10 36 34 am" src="https://cloud.githubusercontent.com/assets/8419308/21235053/70a9f42a-c2b2-11e6-9733-797e42f888bd.png">

To maintain a reasonable size, we'll either need to have a somewhat unrealistic density, or we'll lose some range from the force. My worry with reducing the range of force is that the values will get shifted more towards decimal values, which may be harder for middle school students to interpret. That being said, I could go either way. @ariel-phet what do you think?

**Comment by ariel-phet** [comment]
@arouinfar @jessegreenberg I actually think in this case a density on the order of air is not too big a deal. We are now talking about objects on the km range, that are km apart, so big balls of gas are pretty common out there in the universe (comets and such), and I don't think people will be very focused on the density of the objects for the basics version.

**Comment by arouinfar** [comment]
Thanks @ariel-phet!  We'll be going with the low density option @jessegreenberg. The mix/max sizes will match those used in GFL.

**Comment by jessegreenberg** [comment]
Sounds good, I put 1.5 kg/m^3 in there now, and it looks very similar to the mockups, but we can tweak this value if needed.   Closing.
