### ISSUE TITLE
Masses push too far away

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/gravity-force-lab-basics#20]
If the mass is increased such that the masses need to adjust their positions, one of the mass is pushed to far away. After adjusting its position, it can be dragged closer to the other mass.

**Comment by jessegreenberg** [comment]
Looks like the same is true in gravity-force-lab.

**Comment by jessegreenberg** [comment]
Not noticable in coulombs-law because radii don't change.

**Comment by jessegreenberg** [comment]
Discussed with @mbarlow12, the reason this is happening is because both masses push apart when the radius grows, so it pushes apart by two grid positions.  @mbarlow12 suggested that one solution could be to tack which mass grew and make the other one move.

**Comment by mbarlow12** [comment]
Behavior is fixed; however, I'm not overly excited about the convoluted series of if statements. May require another review.
