### ISSUE TITLE
Self-voicing Options menu

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#203]
@jessegreenberg, when you get a chance, could you change the text in the options dialog?
I realized after our meeting that if we combine Level 0 and Level 1 into one level, the options would look more like this:

Speech Output Levels 
- [ ] Voice Screen Text & Object Changes
- [ ] Voice Context Changes
- [ ] Voice Helpful Hints

We will find out in research if we need to split off object changes.

**Comment by jessegreenberg** [comment]
Done in https://github.com/phetsims/gravity-force-lab-basics/commit/06d0f7feb7f4c6fb34742f63261fef9e7e2c9f6c and https://github.com/phetsims/inverse-square-law-common/commit/f7cd5f2cdfeab8b975e964047092ca6024fa964b

![image](https://user-images.githubusercontent.com/6396244/84826643-3cc8e780-aff1-11ea-8a25-19c170294550.png)
