### ISSUE TITLE
Paradigm 3 Level 0-1 ready for implementation

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#204]
From #202 , @jessegreenberg I have a walk-through complete for Level 0-1 for Paradigm 3.

The design doc notes are now mostly in reverse chronological order with Paradigm 3 closer to the top. I hope this is not confusing.

Here's a link to [Paradigm 3 in the design document](https://docs.google.com/document/d/1XFTD2HTcGCEOP2yQ9_2SkEeXmCceZYUCmNeyiJfcCHs/edit#heading=h.5rzmyz3vgtza)

You will need the updated [Table: P3 Level 0-1 Screen Text & Object Changes](https://docs.google.com/document/d/1XFTD2HTcGCEOP2yQ9_2SkEeXmCceZYUCmNeyiJfcCHs/edit#heading=h.4lnncr9c3u5l)

Let me know if you have any questions.

**Comment by jessegreenberg** [comment]
OK, thanks @terracoda - A new paradigm was added with these changes called `minimalLevels`.

https://phet-dev.colorado.edu/html/gravity-force-lab-basics/1.1.0-dev.8/phet/gravity-force-lab-basics_en_phet.html?selfVoicing=minimalLevels

Ready for dicsussion today.
