### ISSUE TITLE
(Self-Voicing) Incorrect force value read

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/gravity-force-lab-basics#207]
@terracoda  mentioned that occasionally the incorrect force value is read. Seems to happen from all forms of input. Seems to be related to when mass changes and causes another mass to move.

Unclear if it is from new functions added for self-voicing, or if it is a potential issue with the existing PDOM descriptions.

**Comment by terracoda** [comment]
Link to screen capture on google drive
https://drive.google.com/drive/folders/158Oh4eYGJCprqc7RdTD8Oeuws6rfHCFc

**Comment by terracoda** [comment]
@jessegreenberg, the force value is only spoken incorrectly in the context response. The value read out in the reading block is read out correctly.

**Comment by jessegreenberg** [comment]
In the video the force value is larger than what it actually is, so I suspect it is reading the value that it would be if the masses were not pushed apart.

**Comment by jessegreenberg** [comment]
I confirmed that this is NOT happening in the alerts in the a11y view:
![image](https://user-images.githubusercontent.com/6396244/88213308-8dea7d80-cc26-11ea-99b0-944e0dc7aca2.png)

But had self-voicing enabled during the above capture and it read a force that was too large.

**Comment by jessegreenberg** [comment]
OK, this should be fixed @terracoda, can you please verify?

**Comment by terracoda** [comment]
Looks and sounds correct @jessegreenberg. Thanks.
