### ISSUE TITLE
(Self-voicing) - need qualitative force information in reading block when Force Values not checked

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#208]
@jessegreenberg, sorry, I missed this detail. When Force Value is not checked, we will need qualitative details about the force arrows, rather than the raw value for newtons.

I don't think I should describe the size of the force. We explicitly did not do that in the non-visual experience. We described the size of the "force arrows" instead.

Given that background, I think we should go with the content in the first bullet o the each of the masses as the reading block content when force value sis not checked.

Here is two example:
Reading block for Red sphere's force:
- Force arrow is {{very small}}, and points directly at mass 1.

Reading block for Blue Sphere's force:
- Force arrow is {{very small}}, and points directly at mass 2.

When this is the visual situation:
![Screen Shot 2020-07-20 at 12 13 56 PM](https://user-images.githubusercontent.com/1902116/87950989-9904a880-ca82-11ea-8d42-5a285793e66f.png)

I realize that the wording is quite different from the on-screen text, so I might need to design a custom string. That said, this is the best option I have for initial implementation.

**Comment by terracoda** [comment]
And here's another screenshot
![Screen Shot 2020-07-20 at 12 25 24 PM](https://user-images.githubusercontent.com/1902116/87952259-2dbbd600-ca84-11ea-881c-3923e70710be.png)

**Comment by jessegreenberg** [comment]
OK, I think this is done in the above commit @terracoda. The logic is like:
- for paradigm 2 and paradigm 3:
  - if showing force values
    - if selfVoicingVersion === 1
      -  "Force on mass 1 by mass 2 equals 33.4 newtons." 
    - if selfVoicingVersion === 2
      - "Size of force on mass 1 by mass 2 is 33.4 newtons."
  - else
    - "Force arrow is tiny, and points directly at mass 2."


@terracoda can you please review?

**Comment by terracoda** [comment]
Sounds great! Thanks @jessegreenberg.
