### ISSUE TITLE
Range is incorrect

### ISSUE THREAD

**Issue by samreid** [phetsims/gravity-force-lab-basics#21]
From https://github.com/phetsims/axon/issues/137 the initial position is being set to -2000 but the range is -5 to 5.  Assigned to @jessegreenberg.

![image](https://user-images.githubusercontent.com/679486/30253826-22e237fe-964a-11e7-8d0d-038b1645eac8.png)

**Comment by jessegreenberg** [comment]
Thanks @samreid, fixed in the above commit. Closing.
