### ISSUE TITLE
(Self-Voicing) - when focus highlight is on item, mouse over voices content

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#210]
I am getting voiced text with mouse hover when the pink keyboard focus highlight is activated on some hovered items. The check boxes and the mass controls. This doe snot happen with the sphere's themselves.

To reproduce, activate highlight on a checkbox, then hover with the mouse.

@jessegreenberg, I don't remember this being an intentional design request. Is it possible to make sure a learner does not get unintentional reading while hovering focused items?

**Comment by terracoda** [comment]
Actually, this happens on all interactive objects, including the mass spheres (distance/position sliders).

**Comment by terracoda** [comment]
Reading blocks, self-voice as expected, it is the regular interactive items when keyboard highlight is activated that is the issue.

**Comment by jessegreenberg** [comment]
This ended up being tricky but a fix has been pushed in the above commit. @terracoda
