### ISSUE TITLE
(Self Voicing) Possible for highlight to indicate wrong thing is being described

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/gravity-force-lab-basics#216]
Steps:

- Put focus on mass 2
- Quickly shift tab back to Mass 1 **force arrow**
- We will read about the Mass 1, even thought the reading highlihgt is on the arrow. And the reading highlight will be incorrectly yellow.

**Comment by terracoda** [comment]
Nice catch.

**Comment by jessegreenberg** [comment]
OK, I believe this is fixed, closing.
