### ISSUE TITLE
(Self-Voicing) Options menu - make description text larger

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#222]
In an interview, the descriptive text in the options menu was too small for a participant to read. The participant used magnification software to red the text.

We may need to consider making the text a little bigger when we make design  changes to the Options Menu, or naturally leave this to handled with the zoom and magnification feature, once available for this simulation.

**Comment by terracoda** [comment]
@jessegreenberg, do you agree that the best way forward for this issue is to wait for zoom and magnification to be available on this sim?

**Comment by jessegreenberg** [comment]
I agree the current text is a bit small, we could certainly make it bigger.

Alternatively, we could enable zoom in this sim for prototyping. Zoom works in this sim already, thought the self-voicing prototype may not work well in combination with it yet.

**Comment by terracoda** [comment]
Let's make a little bigger by default, and leave the rest to the Zoom feature.

**Comment by terracoda** [comment]
@jessegreenberg, we can also defer this issue because the design of the Options Menu will change when we generalize it.

**Comment by jessegreenberg** [comment]
OK sounds good @terracoda - can this be closed then?

**Comment by terracoda** [comment]
Sure, closing.
