### ISSUE TITLE
(Self-Voicing) - Tweak to Options Menu 

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#226]
Change level 1 from:
- Voice Screen Text & Object Changes
to:
- Voice Object Changes & Screen Text

**Comment by terracoda** [comment]
Based on feedback from Team Survey.

**Comment by jessegreenberg** [comment]
Done in the commit, back to @terracoda to verify.

**Comment by terracoda** [comment]
Verified and closing. Thanks @jessegreenberg.
