### ISSUE TITLE
(Self-Vocing) When Distance is unchecked, reading block appears on hover

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#233]
During an interview, I noticed that when Distance was unchecked and the arrow and kilometers were not shown, the learner still got a reading highlight on the blank space between the centers of the spheres.

In that blank space, 4 kilometers will voice if one clicks on the reading block.

Please remove reading block when Distance is not checked.

Reading access to the qualitative information is not necessary as the words to not appear on the screen. That information is available through interaction and through the Read-Me buttons.

**Comment by jessegreenberg** [comment]
The above commits fix this problem

**Comment by terracoda** [comment]
In my most recent interview (March 5th), this issue reappeared.
With distance not checked the reading highlight still showed up where the distance and distance arrow would be.

**Comment by terracoda** [comment]
The highlight is not showing now in the latest version
https://phet-dev.colorado.edu/html/gravity-force-lab-basics/1.1.0-dev.31/phet/gravity-force-lab-basics_en_phet.html

Marking as resolved.
