### ISSUE TITLE
branch: selfVoicingParadigm1

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/gravity-force-lab-basics#234]
This one-off branch holds our first prototype for the self-voicing. It speaks a lot of content on `over` events, and does not include
any highlighting. The self-voicing feature has deviated from this prototype substantially. But we would like to keep this prototype as a record and may come back to reference it. The one-off branch keeps the SHAs for this build in case we ever want to come back to them.

**Comment by jessegreenberg** [comment]
A build was prepared with these SHAs at https://phet-dev.colorado.edu/html/gravity-force-lab-basics/1.1.0-selfVoicingParadigm1.1/phet/gravity-force-lab-basics_en_phet.html, and that is likely sufficient for reference/documentation. This branch can probably be deleted in the near future.

**Comment by jessegreenberg** [comment]
Yes, this branch can be deleted.

**Comment by jessegreenberg** [comment]
Removed.

**Comment by zepumph** [comment]
Should be re-deleted as part of phetsims/special-ops#198

**Comment by zepumph** [comment]
Deleted
