### ISSUE TITLE
Add a screenshot

### ISSUE THREAD

**Issue by samreid** [phetsims/gravity-force-lab-basics#24]
In attempt to work around https://github.com/phetsims/perennial/issues/64 I'm copying the gravity force lab screenshot to assets/ for a build.  But we will need to generate an accurate screenshot for this sim.  I'm not sure if the sim is ready for that yet, so I'll mark this as high priority (so it isn't neglected) but leave unassigned for now.

**Comment by samreid** [comment]
We can remove the placeholder image if/when https://github.com/phetsims/perennial/issues/64 is resolved

**Comment by arouinfar** [comment]
Let's go with something like this @phet-steele 
![image](https://user-images.githubusercontent.com/8419308/35244047-0fe69820-ff7c-11e7-9eb5-baf54629350a.png)

Alternates:
![image](https://user-images.githubusercontent.com/8419308/35244186-9242f8b8-ff7c-11e7-8a7b-86341781ac0b.png)


<img width="1091" alt="screen shot 2018-01-22 at 1 57 49 pm" src="https://user-images.githubusercontent.com/8419308/35244108-50092ad0-ff7c-11e7-91db-b4f1c444dfa7.png">

**Comment by jessegreenberg** [comment]
@phet-steele @lmulhall-phet do you know why this is on hold? Maybe because the mass colors have changed since https://github.com/phetsims/gravity-force-lab-basics/issues/24#issuecomment-359563000?

**Comment by arouinfar** [comment]
@jessegreenberg my guess is that screenshot issues are generally put `on-hold` until a sim reaches RC, at which point there aren't likely to be any further design tweaks. 

That said, I would still go with these screenshots, albeit taken from the latest version.

**Comment by lmulhall-phet** [comment]
Yeah, we usually try to take screenshots right after we're done with the last round of RC.

**Comment by zepumph** [comment]
>Yeah, we usually try to take screenshots right after we're done with the last round of RC.

We are around that time, as RC.2 is in QA right now. I'm going to remove the on-hold label, though it may not be necessary just this second.

**Comment by KatieWoe** [comment]
Screenshots updated using https://github.com/phetsims/QA/issues/438.  @arouinfar please close if you are happy with results.

**Comment by arouinfar** [comment]
Thanks @KatieWoe. Looks good.
