### ISSUE TITLE
Add swipe gestures to this sim for upcoming interviews

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/gravity-force-lab-basics#241]
We need the SwipeListener to be used in this sim to support non-visual access when used in combination with self-voicing and vibration features.

**Comment by jessegreenberg** [comment]
A version was produced with swipe gestures, closing.

**Comment by terracoda** [comment]
Related to research on haptics and non-visual access, we want the gesture to allow for the finger to be on the screen.
