### ISSUE TITLE
Add "Enable Swipe Gesture" to options menu 

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#243]
Opening this issue, so the idea of swipe gesture with Self-Voicing is not forgotten.

It will be interesting to see if enabling swipe gesture has any specific or general impacts on the self-voicing content.

**Comment by jessegreenberg** [comment]
The option has been added to the options dialog @terracoda, currently enabled by default for interviews coming up in November. Would you like to keep this open or can it be closed?

**Comment by jessegreenberg** [comment]
THis has been added, closing.
