### ISSUE TITLE
(Self-Voicing) Not hearing anything when focus falls on either mass sphere

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#244]
I was just testing the Self-Voicing feature on PhET Marks and I do not hear any thing when focus is moved to a mass sphere.

Mass controls seem to be working fine.

Maybe something happened when we moved to using utterance queue?

**Comment by jessegreenberg** [comment]
Sorry about that, silly mistake - fixed in https://github.com/phetsims/gravity-force-lab-basics/commit/0fed28b763f7fa2fc002812a60ada0ae5ae14208.
