### ISSUE TITLE
(Self-Voicing) Got stuck in Options/Preferences dialog

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#258]
While testing latest version of GFLB with haptics & self-voicing, I went to the "Preferences" button to open the dialog.

While in the dialog, I checked a check box and then tried to uncheck it, but my focus highlights disappeared.
I could get a focus highlight on the Close button, the X button, but I was not able to close the dialog with a double tap.

Since I couldn't close the dialog, I wasn't able to do anything because with gesture control enabled, other types of input do not work.

I pressed the App Back but to go back to the home page and start again.

I can reproduce this issue.
It seems after checking a checkbox or unchecking a checked checkbox, something happens to focus and nothing works.

**Comment by jessegreenberg** [comment]
This was fixed in https://github.com/phetsims/scenery-phet/commit/3b5c7bfb5cf0e399f3f37fdb30423ca031474805.

**Comment by terracoda** [comment]
I thought I was having issues, but I realized that I had accidentally unchecked gestures! Closing again.
