### ISSUE TITLE
Unify text for "show values" vs "force values"

### ISSUE THREAD

**Issue by samreid** [phetsims/gravity-force-lab-basics#26]
Coulomb's Law and Gravity Force Lab have a "Show Values" checkbox whereas Gravity Force Lab: Basics has a "Force Values" checkbox.  While different strings are supplied by the different sims, the same tandem is hard coded in common code (and would be unconventional to pass in).  I recommend unifying the naming for this property, either as "Force Values" or "Show Values".  I suspect that having similar terminology across our sims will also be helpful for students and teachers.  Assigned to @jessegreenberg to discuss with the sim design teams and come up with a plan. 

Should be completed before #22, so I'll mark it with the same priority.

**Comment by jessegreenberg** [comment]
Checking mockups, it looks like the string in the strings.json file is just wrong. It should be "Show values" not "Show Forces".

**Comment by jessegreenberg** [comment]
We are going to manage how to  share strings between sims using the inverse-square-law-common repo in  https://github.com/phetsims/inverse-square-law-common/issues/26.

**Comment by jessegreenberg** [comment]
I changed the string in gravity-force-lab-basics-strings_en.json to be 'Show Values' for now, but this string should be maintained in inverse-square-law-common, see https://github.com/phetsims/inverse-square-law-common/issues/26. Hey this issue and the one in inverse-square-law-common have the same number :D

This one can be closed.
