### ISSUE TITLE
(Haptics/ Self-Voicing) Possible inconsistency in single tap, hold & drag to activate force vibration

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#260]
I haven't tested the latest version (1.1.0-dev.29) in Test Flight, but in the previous version on my iPhone8 iOS 13.5.1 I consistently get vibrations when I double tap & hold (then drag) a sphere. When I do a single tap & hold (then drag), I sometimes do not get vibrations on grab.

This inconsistency only happens with "supportsGestureControl" is enabled.

Since I am the only person noticing this issue, it may not need to be investigated before the upcoming haptics research interviews.

Also, since double tap & hold is the native VO gesture to activate dragging a slider, blind users using our custom gestures may intuitively do a double tap & hold to grab and drag, and thus not experience the inconsistency that I have felt with a single tap & hold.

I'll mention @jessegreenberg, @emily-phet, @Ashton-Morris so this issue is on people's radar for the next round of testing in Test Flight.

**Comment by terracoda** [comment]
Using the question label:
Is this is an actual bug or possible feature?

**Comment by jessegreenberg** [comment]
OK, I was able to reproduce this on my phone as well. This is a bug, vibration should start in this case.

**Comment by jessegreenberg** [comment]
When this happens I can see the request to start vibration and change its intensity reaching the phone, but it isn't vibrating.

**Comment by jessegreenberg** [comment]
I am not seeing anywhere in code that is stopping vibration from happening in this case. I think it may be related to the finger movement. If my finger moves ever so slightly while holding down, vibration occurs consistently. But if I try hard to keep my finger as still as possible, that is when the bug seems to happen.

**Comment by jessegreenberg** [comment]
OK, I have a theory that there is a bug where vibration won't start if requested before the Safari "single-tap and hold" vibration, for that gesture specifically. Double tap and hold doesn't cause that default vibration, nor does "press and slight drag". So I am wondering if we can fix this by either preventing that default vibration or by making the hold time for "press and hold" gesture longer than Safari's time.

**Comment by jessegreenberg** [comment]
Yes, I think thats it! After increasing the hold time to 1 second, I haven't been able to get it to start dragging without vibrating.

**Comment by jessegreenberg** [comment]
A new version was deployed to TestFlight with the fix, @terracoda can you please verify it is fixed there?

**Comment by terracoda** [comment]
@jessegreenberg, I just tested the updated version on Test Flight. It's working nicely now. I consistently get vibrations on single tap & hold and vibrations continue as I drag.

Nice work. I'm closing this issue.
