### ISSUE TITLE
(Self-Voicing) Remove "grabbed" when interacting with the mass spheres

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#263]
During my review of Self-Voicing for GFLB, I'd like to revisit my decision on providing the word "grabbed" when the dragging of a mass sphere starts.

I added it for non-visual access, but I feel it gets in the way for non-visual users.
I'd like to review with the team. Maybe visual and non-visual learners can live without this tiny string.

**Comment by terracoda** [comment]
Details coming soon. I am pretty sure we can remove the grabbed and release states for all input on sliders.

**Comment by terracoda** [comment]
@jessegreenberg, I can't get custom gestures to work for GFLB or JT.

**Comment by jessegreenberg** [comment]
It looks like gesture control requires self-voicing to work at the moment. Are you able to get it to work with `?supportsSelfVoicing&supportsGestureControl`?

**Comment by terracoda** [comment]
ok :-)

**Comment by terracoda** [comment]
Double tapping is not working.
I'll mark for meeting.

**Comment by jessegreenberg** [comment]
OK I found the issue, thanks @terracoda! Hopefully fixed above, can you please try again after updating the scenery repo?

**Comment by jessegreenberg** [comment]
These parts of the utterances have not been in use for some time, closing this issue.
