### ISSUE TITLE
(Voicing) Design of reading block highlight - change little speech bubble

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#264]
This is a general Self-Voicing issue, but currently, reading blocks are only in the GFLB sim.

We would like to adjust the R to match the T in the Self-Voicing icon.

![Screen Shot 2021-01-13 at 4 29 41 PM](https://user-images.githubusercontent.com/1902116/104644746-c2e10580-5688-11eb-9300-51c8436ebc46.png)
![Screen Shot 2021-01-13 at 4 26 15 PM](https://user-images.githubusercontent.com/1902116/104644759-c6748c80-5688-11eb-85fc-d8075fa8ef6f.png)
![Screen Shot 2021-01-13 at 4 26 50 PM](https://user-images.githubusercontent.com/1902116/104644763-c83e5000-5688-11eb-857a-9775fc672c22.png)

Will look like this instead:
![image](https://user-images.githubusercontent.com/1902116/104644802-d55b3f00-5688-11eb-94c9-6857eac8970c.png)

@jessegreenberg, @amanda-phet asked if you need a png or an svg?

**Comment by jessegreenberg** [comment]
The bubble has been removed, and we are moving forward with that currently. @terracoda OK to close this older issue?

**Comment by terracoda** [comment]
Oh, I didn't realize we had decided to remove it all together. One of the reasons it is there is so we are not using color alone to indicate the different kinds of highlights. 

The speech bubble wasn't the best design, so I'll mark this as on hold and for our next meeting.

**Comment by jessegreenberg** [comment]
Discussed 7/20/21:

We agreed that it is OK that using color alone to convey this state. The icon is useful, but there are cases where it could occlude important content. CLosing.
