### ISSUE TITLE
(Voicing) Design change on force arrow description when Force Values not checked

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#265]
When forces is not checked, the self-voicing description is not at all similar to the on screen text.

- On screen text: 
    - Force on mass 2 by mass 1
    - Force on mass 1 by mass 2
- Self-voiced content (same as PDOM)
    - Force arrow is tiny and points directly at mass 1
    - Force arrow is tiny and points directly at mass 2

I didn't have force described in my initial interview. I added it afterwards, and then I don't think I thought too hard on this scenario when Force Values are unchecked.

I think the PDOM description captures the concept nicely, and is perfect for non-visual learners as it has the size and direction of the force arrow included. The words, however are quite different from what is on the screen, and may be confusing to visual users. 

I don't want to say the force is tiny, so I don't see an easy way around this.
@emily-phet, shall I wait for interview feedback on this one?

**Comment by emily-phet** [comment]
@terracoda 
My first thought - regarding what we might want the self-voicing to stay - is:
- The text on the screen (or something very similar). So "Force on mass 2 by mass 1" and "Force on mass 1 by mass 2) or just the slightest variant fo these. This would be good for the least verbose preference setting.
- In a more verbose preference setting, the addition of a description of the vector arrow. 

That way, the self-voicing has a setting where those making use of the visual display do not have to have a description of the force arrow, but there is a way to have access to this information (for those not using the visual display). 

Can you think of a way to make something like this work? 

If you can think of a straightforward way to do something like this, we might want to go ahead and add it to the list to do before interviews. If not, we might wait until after at least a first round of interviews, so we have more information to brainstorm with.

**Comment by terracoda** [comment]
Note to self:
Object changes & on-screen text
 - optimized for reading
 - optimized for concepts

**Comment by terracoda** [comment]
I have thought about this description. 

Here is the full dynamic state descriptions of mass spheres in the PDOM with Force Values not checked:
**mass 1, Blue Sphere**
- Force arrow is tiny, and points directly at mass 2.
- mass 1 is 2 billion kilograms, half the size of mass 2, and also 4 kilometers from mass 2.

**mass 2, Red Sphere**
- Force arrow is tiny, and points directly at mass 1.
- mass 2 is 4 billion kilograms, twice the size of mass 1, and also 4 kilometers from mass 1.

**Here's the visual for the above:**
<img width="420" alt="Screen Shot 2021-04-15 at 3 09 46 PM" src="https://user-images.githubusercontent.com/1902116/114914661-28b26a00-9dfd-11eb-8837-57099b42a589.png">

In the Voicing design we are currently using the first bullet straight from the PDOM: 
- Force arrow is tiny, and points directly at mass 2.

This text is quite different from the text on the screen. It describes what is not available to non-visual learners (both size and direction of the force arrow).

I feel for the Voicing design, it would be better to focus on the actual text on the screen, and just add the size of the force arrow which is also in the box. The direction of the arrow is described in the Details, so it's available there if it is needed.

**_Here's my new design for the Force Arrow reading block when Force Values is not checked:_**
- Force on mass 1 by mass 2. Force arrow tiny. 
- Force on mass 2 by mass 1. Force arrow tiny.

The content for the Force Arrow reading block when Force Values is checked is already a custom string, and it sounds like this:
- Force on mass 1 by mass 2 equals 33.4 newtons. Force arrow tiny. 
- Force on mass 2 by mass 1 equals 33.4 newtons. Force arrow tiny.

...though I am not sure of the exact punctuation and capitalization.

Please use the same capitalization and punctuation in both sets of custom strings. Any of the followings strings would work:

Force Values checked:
- Force on mass 1 by mass 2 equals 33.4 newtons, force arrow tiny. 
- Force on mass 2 by mass 1 equals 33.4 newtons, force arrow tiny.

Force Values NOT checked
- Force on mass 1 by mass 2, force arrow tiny. 
- Force on mass 2 by mass 1, force arrow tiny.

***

Force Values checked:
- Force on mass 1 by mass 2 equals 33.4 newtons, Force arrow tiny
- Force on mass 2 by mass 1 equals 33.4 newtons, Force arrow tiny

Force Values NOT checked
- Force on mass 1 by mass 2, Force arrow tiny
- Force on mass 2 by mass 1, Force arrow tiny

***

Force Values checked:
- force on mass 1 by mass 2 equals 33.4 newtons, force arrow tiny
- force on mass 2 by mass 1 equals 33.4 newtons, force arrow tiny

Force Values NOT checked
- force on mass 1 by mass 2, force arrow tiny
- force on mass 2 by mass 1, force arrow tiny

**Comment by jessegreenberg** [comment]
@terracoda does this issue still require work, or were these things in the updated Voicing design doc?

**Comment by terracoda** [comment]
This was indeed in the design doc and has been taken care of.
