### ISSUE TITLE
(Voicing) Tweaking of progress indicators

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#266]
In my review of Self-Voicing I found I might need to tweak the way the progress indicators are working.

I'd like to review the design after #263 is completed.

**Comment by terracoda** [comment]
Changes to how the Progress and Landmark strings should work is now documented in the design doc.
Please see the tables for mass spheres:
- [Distance checked](https://docs.google.com/document/d/1XFTD2HTcGCEOP2yQ9_2SkEeXmCceZYUCmNeyiJfcCHs/edit#heading=h.eqtuhm8zcsy), and 
- [Distance not checked](https://docs.google.com/document/d/1XFTD2HTcGCEOP2yQ9_2SkEeXmCceZYUCmNeyiJfcCHs/edit#heading=h.ovgzcntw19lm)

Some things in red may still need final-final decision.

**Comment by jessegreenberg** [comment]
@terracoda is this issue something that still requires work or was this reflected in the updated voicing design document?

**Comment by terracoda** [comment]
I think this has been resolved during re-implementation with name response, etc., but I will check.

**Comment by terracoda** [comment]
The progress indicators are working well. Closing.
