### ISSUE TITLE
(Preferences) Mouse exploration breaks keyboard navigation

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#269]
While using Preferences menu in GFLB, an interview participant would switch back and for the between using keyboard and mouse exploration, and keyboard navigation would stop working.

During interview we determined that mouse exploration in Preferences dialog would break keyboard navigation in Preferences dialog.

This may be a general issue.

System: MacOS 10.15.7 
Browser: Safari

**Comment by terracoda** [comment]
I just reviewed the interview data for some extra details:
- The learner opened the dialog with a mouse click, and could use the tab key when first opened, but was having trouble because there was very little self-voicing.
- Then he switches to mouse, clicks Visual tab, clicks interactive highlights checkbox, clicks Audio tab. Learner is now getting highlights on mouse hover  but is not getting voicing on hover. Learner clicks on Input tab then clicks back on Audio tab. 
- I suggest using the keyboard and he can't. I hear him hit the tab key hard 3 times - nothing happens. The dialog closes unexpectedly and keyboard interaction doesn't work in the sim. 
- Learner re-loads and clicks the Preferences button again to open the dialog. 
- After reloading/and re-opening learner can use the keyboard. They Tab to Audio tab and start exploring the Audio preferences with the keyboard, the focusable content is voiced, and the learner mentions a delay between tabbing and voicing.
- On this second go, he hasn't activated Interactive Highlights.
- KB nav does, indeed break again after he hovers over areas explaining it would be nice to have a Voice heading here and a Simulation Sound heading here. The learner may have clicked while they pointed to those areas but I can't tell from the video. They hit tab and focus goes to the browser bar.
- They reload the sim for a third go at the Preferences dialog. Unless the sim remembered the setting, Interactive Highlights was not enabled on the second go.

Those are the interaction details.

**Comment by jessegreenberg** [comment]
Thanks for the detailed walkthrough @terracoda, that is really helpful. I have been trying for a while and haven't been able to get it to break yet. Ive been trying on a Windows 10 device with Chrome and on macOS 11.2 Big Sur with Safari. Note that user was testing with 10.15.7 (an older version now) and I am not able to test on that.

Also, I am testing in a version that *does* have self-voicing content for the dialog tabs, so maybe the fact that they are instrumented is changing things. But I tried removing the instrumentation and still wasn't able to break keyboard navigation.

@terracoda Is there anything else you would like to do to try to reproduce and debug this?

**Comment by terracoda** [comment]
@jessegreenberg, that's all good news that you can't reproduce the bug.
Let's move on. 

It could be something that was part of the initial implementation that has now changed. It could be platform specific.

I'll close this issue for now and re-open if it pops up again.

I also cannot reproduce on my system MacOs 10.13.6
