### ISSUE TITLE
(Self-Voicing Preferences) Voice Tabs in Preferences menu 

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#270]
If possible, it would be great of the Tabs in the Preferences menu could voice by Thursday March 11.

- General Preferences
- Visual Preferences
- Audio Preferences
- Input Preferences

See Preferences design doc:
https://docs.google.com/document/d/1Qu3U8IsFYn486oJUzQ71BXs_lBKZTVS5NVdLJlTK7gw/edit

But if it is not possible, we will carry on.

**Comment by jessegreenberg** [comment]
During a zoom call today @terracoda requested that the content be
Preferences, General tab
Preferences, Visual tab
Preferences, Audio tab
Preferences, Input tab

for each tab button.

**Comment by jessegreenberg** [comment]
I have a change for this that isn't ready for commit but is potentially ready for interviews starting tomorrow, @terracoda can you please verify 
https://phet-dev.colorado.edu/html/jg-tests/gravity-force-lab-basics_en_phet.html?supportsSelfVoicing
https://phet-dev.colorado.edu/html/jg-tests/john-travoltage_en_phet.html?supportsSelfVoicing

**Comment by terracoda** [comment]
The Tabs are working great with both keyboard and mouse for both GFLB and John Travoltage.

@jessegreenberg, I feel comfortable closing this issue. We have a working feature that will need further refinement as the design and code implementation advances.  

Does that sound good @jessegreenberg, if so, please close.

**Comment by terracoda** [comment]
@jessegreenberg, I'll go ahead and close since the immediate issue is addressed. Further work will continue as we gather more information from learners.
