### ISSUE TITLE
(Self-Voicing Navbar) Voice buttons in Navbar

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#271]
If possible, please voice buttons in navbar for next interviews.
If not possible we will carry on.

- Preferences
- All Audio
- Keyboard Shortcuts
- PhET Menu

**Comment by terracoda** [comment]
This is common code, so not sure this is the correct repo. Also, @zepumph might be helping with this issue as he starts self-voicing for ratio and proportion.

**Comment by jessegreenberg** [comment]
I have a working change that ins't ready for a commit but is potentially ready for interviews starting tomorrow. @terracoda can you please verify this is working in 
https://phet-dev.colorado.edu/html/jg-tests/gravity-force-lab-basics_en_phet.html?supportsSelfVoicing
https://phet-dev.colorado.edu/html/jg-tests/john-travoltage_en_phet.html?supportsSelfVoicing

**Comment by terracoda** [comment]
Like #270, this is working as requested for both GFLB and JT. We are ready for next interviews this week (today and tomorrow). 

We can close this issue as immediate voice access is available for the navbar buttons. 
Work on this will continue as we gather information, but the immediate issue is resolved.
