### ISSUE TITLE
Publish with PhET-iO when publishing with Voicing

### ISSUE THREAD

**Issue by zepumph** [phetsims/gravity-force-lab-basics#273]
From quarterly planning today, it seems like it would be nice to publish this with PhET-iO as well since it is going through the QA process. It already has PhET-iO implementation, and (I believe) would only need client guides and a minor review to get this ready for publication. With recent PhET-iO versions already going through QA, phet-io is relatively stable on master right now, so I don't see a large burden to adding this brand in to the publication.

@arouinfar to review and add client guides to this sim.

**Comment by arouinfar** [comment]
I've created issues for the PhET-iO design review and client guide, so back to @zepumph.

**Comment by zepumph** [comment]
@jessegreenberg, presumably this will get dev tested with Voicing, can you please include PhET-iO brand in that test?

**Comment by jessegreenberg** [comment]
Sure, sounds good. That will presumably happen in 3-4 weeks, is that timeline OK?

**Comment by zepumph** [comment]
This is no longer a Q2 goal.

**Comment by zepumph** [comment]
Since @arouinfar removed the blocking label in https://github.com/phetsims/gravity-force-lab-basics/issues/276, let's do that here too.

**Comment by jessegreenberg** [comment]
We are getting ready to republish this sim with Voicing and it will not include PhET-iO. @zepumph OK to close this issue?

**Comment by zepumph** [comment]
Yes thanks.
