### ISSUE TITLE
(PDOM & Voicing) Static Scene/Screen Summary Change

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#277]
Based on feedback from interviews, I feel it will benefit some learners to explicitly indicate that the track described in the scene/screen summary is actually invisible. 

I would like this change to be in both the PDOM and in Voicing.
![Screen Shot 2021-06-15 at 10 27 19 AM](https://user-images.githubusercontent.com/1902116/122056577-4a5fab80-cdc4-11eb-9855-ffa4b8c87d01.png)

In PDOM and Voicing Overview, please change "along a track" in the the end of the first sentence in the second paragraph to:
- "an invisible track"

**Comment by jessegreenberg** [comment]
Done in the above commit. Here is the content spoken from "Details" buton
![image](https://user-images.githubusercontent.com/6396244/125519346-a4564739-23b4-49d1-ba82-5a4772a80467.png)


And in the PDOM:
![image](https://user-images.githubusercontent.com/6396244/125519455-9a309ade-ab56-4a59-a23f-3d69cc072dc7.png)

**Comment by jessegreenberg** [comment]
@terracoda can you please verify this was done correctly in https://phet-dev.colorado.edu/html/gravity-force-lab-basics/1.1.0-dev.34/phet/gravity-force-lab-basics_en_phet.html?

**Comment by terracoda** [comment]
Yes, this sounds great, too, in both Voicing and the PDOM. Thanks @jessegreenberg.
