### ISSUE TITLE
(PDOM & Voicing) Change word in dynamic part of scene/screen summary

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#278]
Continuing from  #277, please change "pointing" to "points" so that the dynamic part of the scene/screen summary and the Voicing "Play Details" button reads as:

- "Currently, force on mass 1 by mass 2 is of equal size and points directly opposite to the force on mass 2 by mass 1."

In addition, for the Voicing Details button, please ensure that bullet points have their commas and periods as shown below. I think they do, but I just want to be sure.
- Force arrows are tiny at 33.4 newtons.
- mass 1 and mass 2 are close to each other, centers exactly 4 kilometers apart.
- Mass of mass 1 is 2 billion kilograms, half the size of mass 2 at 4 billion kilograms.
- Robots pull very little keeping spheres in place.

**Comment by jessegreenberg** [comment]
> please change "pointing" to "points"

Done.

> please ensure that bullet points have their commas and periods as shown below

Here is the full string used when pressing the "Details" button:
![image](https://user-images.githubusercontent.com/6396244/125518830-33cb448c-9b75-48f7-b3d8-24563f0c34f7.png)

Punctuation looks like it matches.

**Comment by jessegreenberg** [comment]
@terracoda can you please verify this issue was done correctly in https://phet-dev.colorado.edu/html/gravity-force-lab-basics/1.1.0-dev.34/phet/gravity-force-lab-basics_en_phet.html?

**Comment by terracoda** [comment]
Yes, this sounds great. Thanks.
