### ISSUE TITLE
up/down keys do not increase/decrease mass in Edge

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/gravity-force-lab-basics#28]
**Test device:**

Hanson

**Operating System:**

Windows 10

**Browser:**

Microsoft Edge 41.16299.15.0

**Problem description:**

See title. This is for phetsims/QA/issues/83.

**Steps to reproduce:**

Use query parameter ?accessibility and tab to the mass adjuster things.

**Troubleshooting information (do not edit):**

Name: ‪Gravity Force Lab: Basics‬
URL: https://www.colorado.edu/physics/phet/dev/html/gravity-force-lab-basics/1.0.0-dev.12/phet/gravity-force-lab-basics_all_phet.html?accessibility
Version: 1.0.0-dev.12 2018-01-10 18:13:45 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
Language: en-US
Window: 1440x700
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"18b4cd9d","branch":"master"},"brand":{"sha":"53cf227b","branch":"master"},"chipper":{"sha":"bccc2bdc","branch":"2.0"},"dot":{"sha":"ee4d0e25","branch":"master"},"gravity-force-lab":{"sha":"40133946","branch":"master"},"gravity-force-lab-basics":{"sha":"22fcdf78","branch":"master"},"inverse-square-law-common":{"sha":"350f0e28","branch":"master"},"joist":{"sha":"31bec118","branch":"master"},"kite":{"sha":"e46f990e","branch":"master"},"phet-core":{"sha":"88a51822","branch":"master"},"phet-io":{"sha":"e31dae9a","branch":"master"},"phet-io-website":{"sha":"7440f48b","branch":"master"},"phet-io-wrapper-classroom-activity":{"sha":"c84e3046","branch":"master"},"phet-io-wrapper-lab-book":{"sha":"c57fc202","branch":"master"},"phet-io-wrapper-sonification":{"sha":"4ac6e820","branch":"master"},"phet-io-wrappers":{"sha":"26d5a646","branch":"chipper2.0"},"phetcommon":{"sha":"85d72626","branch":"master"},"query-string-machine":{"sha":"b8bdcc28","branch":"master"},"scenery":{"sha":"ed9aae25","branch":"master"},"scenery-phet":{"sha":"7f2ddfbf","branch":"master"},"sherpa":{"sha":"9ca67479","branch":"master"},"sun":{"sha":"8b6250c0","branch":"master"},"tandem":{"sha":"b77a8102","branch":"master"}}

**Comment by jessegreenberg** [comment]
Thanks @lmulhall-phet, it appears that Edge and IE11 do not trigger `change` or  `input` events when numbers are incremented with arrow keys. We will need to go entirely through keydown and make sure that the input still works when AT are enabled.

**Comment by jessegreenberg** [comment]
Fixed with the above commit and https://github.com/phetsims/scenery-phet/commit/a22423523a62116681bf175de32ca8705a9d60ab. Closing.
