### ISSUE TITLE
GFLB version with voicing for survey

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/gravity-force-lab-basics#281]
For our second voicing survey, we would like to re-run the first survey using another simulation with a distinct interaction scheme from JT. This will give us a good comparison to run against each other.

We will need a version of GFLB that is ready to go to participants, but not necessarily completely bug free. The plan will be to tack on the same three query parameters from (https://github.com/phetsims/john-travoltage/issues/419) to create three distinct sim versions.

Ideally this is ready for distribution on July 5th, but let me know if this is not possible or just slightly too soon :) 

Tagging @terracoda, assigning @jessegreenberg

**Comment by BLFiedler** [comment]
Additionally, we will need to have the simulation open with the Preferences menu visible and opened to the Audio tab! (thanks for the catch @jessegreenberg )

**Comment by terracoda** [comment]
@jessegreenberg, when you have a version, I'd like to test it, if possible.

**Comment by jessegreenberg** [comment]
@BLFiedler here is a link to the latest version for the survey. Version was reviewed and issues double checked by @terracoda, this version is much improved from the version shown on Friday.  Sorry it is coming to you a bit last minute. Reassigning the issue to you. 

https://phet-dev.colorado.edu/html/gravity-force-lab-basics/1.1.0-dev.33/phet/gravity-force-lab-basics_en_phet.html?voicingSurvey=true

Query parameters for initial configuration:
```
  ?voicingObjectResponsesInitiallyEnabled=true
  ?voicingContextResponsesInitiallyEnabled=true
  ?voicingHintResponsesInitiallyEnabled=false
```

**Comment by BLFiedler** [comment]
Implemented. Thanks, Jesse! I'll leave this open until the end of the survey, but nothing more is currently needed.

**Comment by jessegreenberg** [comment]
In the above commits I removed the sim specific code that was added for this survey.
