### ISSUE TITLE
(Voicing) - Not getting changes distance during mouse drag?

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#284]
@jessegreenberg, did we have a system for intermittent distance updates during mouse drag before this version? 

Currently, I only get an object and context response (with progress) upon end of drag when I stop clicking the mouse. 

That means, I don't hear any intermittent progress during drag and I get the "closer" string after I stop moving.

What we had before sounded better. Is there are way to have intermittent context responses?

Ideally, we would hear "closer and "farther away" during the drag and we wouldn't hear those strings when dragging is done.

Is there any logic we can save from the last version, or are the systems too different?

**Comment by terracoda** [comment]
Marking this as both design and dev a11y labels, and I will look at the design doc to see if what I want is feasible.

**Comment by terracoda** [comment]
This issue is less important than #283

**Comment by jessegreenberg** [comment]
@terracoda and I met over zoom to discuss this. We changed the behavior so that it speaks the alert every drag instead of just on release. Done in the above commit.

**Comment by jessegreenberg** [comment]
Here is a new version with this fix, @terracoda can you please verify? https://phet-dev.colorado.edu/html/gravity-force-lab-basics/1.1.0-dev.32/phet/gravity-force-lab-basics_en_phet.html?voicingSurvey=true

**Comment by terracoda** [comment]
This sounds good now. I like it.
