### ISSUE TITLE
(PDOM) Home and End shortcuts on macOS moves values to max and min and can move focus, too

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#288]
I think this issue might be related to https://github.com/phetsims/a11y-research/issues/164

When using VoiceOver I jump the sphere to max using the End (function right arrow) shortcut, the sphere jumps to end, and my focus moves to the next focusable item. For the spheres this only happens with function and right arrow.

With the mass controls the behaviour is different. For the Mass 1 control, the End shortcut moves focus forward (same as for the distance sliders), but for Mass 2 control its the Home shortcut that is wonky and it moves focus back to the Mass 1 control after moving the mass to minimum.

I am using macOS Big Sur 11.4 on new MacBook pro (M1 chip).

This weird focus moving only happens when using VoiceOver.

**Comment by terracoda** [comment]
Not this movement of focus also happens in John Travoltage, so maybe it is a known bug.

**Comment by jessegreenberg** [comment]
Yes, it sounds like this is the same issue as https://github.com/phetsims/a11y-research/issues/164. In that issue we found that Home/End moves the virtual cursor AND changes the slider value. We submitted a bug report to Apple about it.

**Comment by terracoda** [comment]
This is a duplicate issue. Closing.
