### ISSUE TITLE
(Voicing) Changes to the voicing of checkboxes

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#290]
I have reviewed the checkbox interactions. 

I have two changes that affect all 3 checkboxes in GFLB.
- [x] Please remove the hint responses when toggling the checkbox sates.
**Reasoning:** 
Since the checkbox interaction is successful when it is toggled between a visually checked and unchecked state with any input, it's not necessary to provide an hint response when activated between checked and unchecked states.

- [x] Please use new custom voicing hints for the focus events when using a keyboard (alternative input).
**Reasoning:** 
Since the learner does not hear the checked and unchecked states when arriving at the checkbox, Emily and I feel it is best to fully reflect the possibilities of the outcomes when the checkbox is toggled. Describing both possible outcomes can help learners with decision making. The PDOM help text only reflects one outcome. 

**New general hints:**
1. For Force Values: Explore force changes with or without values.
2. For Distance: Explore sphere positions with or without exact distance.
3. Constant Size: Explore mass changes with or without changing size of spheres.

Over to you @jessegreenberg for implementation.

**Comment by jessegreenberg** [comment]
Done in the above commits, will have a version built for review shortly.

**Comment by jessegreenberg** [comment]
@terracoda can you please review in tis version? https://phet-dev.colorado.edu/html/gravity-force-lab-basics/1.1.0-dev.36/phet/gravity-force-lab-basics_en_phet.html

**Comment by terracoda** [comment]
The checkboxes sound great now. Thanks @jessegreenberg !
