### ISSUE TITLE
(Voicing) Voice does not match text in Keyboard Shortcuts menu

### ISSUE THREAD

**Issue by stemilymill** [phetsims/gravity-force-lab-basics#298]
https://github.com/phetsims/qa/issues/702
Win10 Firefox

Voicing reads the heading of the "Change Mass" section of the Keyboard Shortcuts menu as "Change Massachusetts"

There is also no pause in between this utterance and the next.

![change mass reads change massachussetts](https://user-images.githubusercontent.com/85511101/131729749-ff8e1c86-0fa9-4548-87ed-2f1a250d1e70.jpg)

**Comment by jessegreenberg** [comment]
Thanks for making an issue, this is kind of funny. But certainly not what we want. I was able to see this in Firefox as well. There isn't a way to change the voicing interpretation of the string. I am not sure why Voicing is interpreting "Massachusetts" for the bold and not for other strings. "Change Mass" label next to the arrow keys is read correctly by speech synthesis.

**Comment by jessegreenberg** [comment]
@terracoda suggested that we make sure there is no punctuation that could trigger this. @emily-phet suggested to see what happens when we do not capitalize the "M".

**Comment by stemilymill** [comment]
This is kind of unrelated but I don't know who to tell separately- the "Change Mass" label next to the arrow keys should not have "Mass" capitalized, in order to match the rest of the dialog.

**Comment by jessegreenberg** [comment]
Thanks @stemilymill , Ill make a new issue for that.

**Comment by jessegreenberg** [comment]
It is broken up into sentences for Voicing. So It looks like "Change Mass." which I could see being interpreted as an abbreviation for the state.

**Comment by jessegreenberg** [comment]
Yes, changing to a comma fixes this.

**Comment by jessegreenberg** [comment]
Change committed and cherry-picked to the 1.1 SHAs.

**Comment by terracoda** [comment]
Good catch @jessegreenberg. We'll have to keep this capitalization and punctuation in mind for auditory description displays :-)

**Comment by KatieWoe** [comment]
Looks ok on Win 11 Firefox+NVDA
