### ISSUE TITLE
Voicing stops with end/home keyboard nav

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/gravity-force-lab-basics#300]
**Test device**
chromebook 

**Operating System**
92.0.4515.157

**Browser**
chrome

**Problem description**
https://github.com/phetsims/qa/issues/702

Similar to https://github.com/phetsims/gravity-force-lab-basics/issues/295 but this is occurring with voicing, not a screen reader. 
When using the home/end keys to jump to min/max mass, there is either a very long delay in the voicing or it doesn't occur at all. This was NOT seen using the Mac11 + chrome. 

**Steps to reproduce**
1. Enable voicing in preferences
2. Tab over to either vertical spinner
3. On the chromebook use control + alt + up/down arrows to jump to min/max masses

**Visuals**

https://drive.google.com/file/d/1qOc7gGJKPKTF9_KxgrudEYONGl-PsDUz/view?usp=sharing

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Gravity Force Lab: Basics‬
URL: https://phet-dev.colorado.edu/html/gravity-force-lab-basics/1.1.0-rc.2/phet/gravity-force-lab-basics_all_phet.html
Version: 1.1.0-rc.2 2021-08-30 16:27:03 UTC
Features missing: applicationcache, applicationcache, touch
User Agent: Mozilla/5.0 (X11; CrOS x86_64 13982.82.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.157 Safari/537.36
Language: en-US
Window: 1357x609
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 4096
Texture: size: 16384 imageUnits: 32 (vertex: 32, combined: 192)
Max viewport: 16384x16384
OES_texture_float: true

**Comment by stemilymill** [comment]
Unable to reproduce on win10 chrome, firefox, or edge.

**Comment by jessegreenberg** [comment]
Thanks @Nancy-Salpepi and @stemilymill. It is starting to look like there are performance problems with Voicing and Chromebooks. And I am starting to wonder if #303 is similar to this issue, voicing is just being slow.

**Comment by jessegreenberg** [comment]
@emily-phet mentioned that for sound there were cases where certain components more readily enabled/supported sound than others. That could be happening here.
@terracoda mentioned that if there are no issues with keyboard input, it could be more of an input bug than a performance bug.
