### ISSUE TITLE
Update capitalization of "Move Mass" label to "Move mass"

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/gravity-force-lab-basics#306]
Suggested by @stemilymill in https://github.com/phetsims/gravity-force-lab-basics/issues/298.

> This is kind of unrelated but I don't know who to tell separately - the "Change Mass" label next to the arrow keys should not have "Mass" capitalized, in order to match the rest of the dialog.

**Comment by jessegreenberg** [comment]
Done in the above commit. Needs a cherry pick for https://github.com/phetsims/qa/issues/702

**Comment by jessegreenberg** [comment]
Cherry pick done.

**Comment by stemilymill** [comment]
Looks fixed in win10 chrome and firefox
