### ISSUE TITLE
Update ScreenShots to include preferences navbar icon

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#315]
This sim needs screenshots on the website. It now has the "Preferences" menu in the navbar. We forgot to this before publication with Voicing.

@arouinfar, who would normally take care of this? Is this something I should know how to do?

**Comment by arouinfar** [comment]
@terracoda screenshots on the website get updated when the sim is built/deployed. It will require a maintenance release to update the screenshots on the website post-publication. Generally, you can ask QA to retake screenshots while a sim is in RC testing. If you want to make any changes to the screenshots, you can include a screenshot in the issue for them to recreate at the correct size/aspect ratio (1536x1008).

I can go ahead and retake the screenshots for GLFB and commit them. Sims can have up to 4 screenshots (1 main & 3 alts). GFLB currently only has 2 alts so we could add a 3rd if you would like to show off the Voicing feature. Maybe something like this? Let me know what you think @terracoda.
<img width="958" alt="Screen Shot 2021-11-11 at 3 55 07 PM" src="https://user-images.githubusercontent.com/8419308/141380744-12a7da72-0c42-4110-9329-a902da1b1fd1.png">

**Comment by arouinfar** [comment]
I updated the screenshots in master and the 1.1 branch in the commits referenced above.

@terracoda please let me know if you would like an additional screenshot that demonstrates the Voicing feature or the Preferences dialog in action.

Assigning to @terracoda @jessegreenberg and responsible-dev @zepumph to decide on the priority of a maintenance release.

**Comment by jessegreenberg** [comment]
Looks good to me, I am happy to do a MR with the screenshot changes when ready. Would probably be me since I saw through the 1.1 publication let me know if you feel differently @zepumph.

@terracoda handing over to @terracoda for https://github.com/phetsims/gravity-force-lab-basics/issues/315#issuecomment-966683686, feel free to reassign to me when published.

**Comment by terracoda** [comment]
I think a screen shot that shows the voicing feature is a great idea.

**Comment by terracoda** [comment]
@jessegreenberg, please include one screen shot of the voicing, like the one in [comment](https://github.com/phetsims/gravity-force-lab-basics/issues/315#issuecomment-966683686)

**Comment by arouinfar** [comment]
@jessegreenberg I can take care of the screenshot. I'll get it committed shortly.

**Comment by arouinfar** [comment]
@jessegreenberg I added an additional screenshot that shows the Voicing feature. The commits to master and 1.1 are referenced above. 

<img width="768" alt="gravity-force-lab-basics-screenshot-alt3" src="https://user-images.githubusercontent.com/8419308/142480475-fec9dec7-b616-4eb9-9f24-74a41d924b62.png">

**Comment by arouinfar** [comment]
> screenshots on the website get updated when the sim is built/deployed.

This is not actually true. The website pulls the screenshots directly from master. Regardless, the updated screenshots have been visible on the website for some time now. Closing.
