### ISSUE TITLE
Update QA credits

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-force-lab-basics#318]
Thanks to @Nancy-Salpepi for catching this. When https://github.com/phetsims/qa/issues/729 there were some QA testers that should have been added to the credits. These include: Emily Miller, Nancy Salpepi, and Brooklyn Lash.

**Comment by jessegreenberg** [comment]
I updated QA credits in https://github.com/phetsims/gravity-force-lab-basics/commit/2f3f317e0f384e314a91cf62df0614445376437b and @KatieWoe confirmed over slack that they look good. There is a batch MR in progress right now and I am not sure if that blocks publications. I already committed the change to the branch. I will deploy either when the batch MR is done or I hear from the responsible dev.

**Comment by jessegreenberg** [comment]
The MR was completed and the republication picked up this change. This is now done, closing.
