### ISSUE TITLE
Issues related to object and context responses for mass sphere sliders 

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#319]
**Voicing Issue (GFLB Only)**
- [ ] Not hearing distance changes or force changes when using keyboard when Voicing is enabled. I do hear distance value on keyboard focus, just not when moving the spheres with any step size (default, small, large, home and end keys). 

**Interactive Description Issues (GFLB and GFL):**
- I hear object and context responses when using the keyboard with VoiceOver and Interactive Description
- [ ] Not hearing the correct context response when I try to go beyond the edge. I hear the context response that describes the forces get bigger, when they actually don't because the distance didn't change. If I try to go beyond the "last stop", I should hear the context response that provides current state information - not the response that is about the changing force arrows. We call these responses "go-beyond edge" responses and we have worked on them before:
    -  https://github.com/phetsims/gravity-force-lab-basics/issues/137
    - https://github.com/phetsims/gravity-force-lab-basics/issues/185#event-2735016053. They won't fire on touch devices, but they should fire when using the keyboard.
    - Here's an example: {{Very close to}} {{mass 2}},  force arrows {{medium size}}, forces {{184.7}} ‪newtons‬.
    - These responses are working in the published version GFLB
    - These responses are working on the number spinners on Phettest and in the published version
    - These responses are NOT working on any of the sliders in GFL (regular)

This might all be related to recent work on the sliders in common code.
@jessegreenberg and @zepumph plase re-assign as you see fit.

**Comment by zepumph** [comment]
Fixed, see https://github.com/phetsims/scenery/issues/1340#issuecomment-1030410527
