### ISSUE TITLE
Force arrow is not instrumented

### ISSUE THREAD

**Issue by phet-steele** [phetsims/gravity-force-lab-basics#32]
Cannot be disabled in instance proxies:

<img width="808" alt="screen shot 2018-01-11 at 2 08 06 pm" src="https://user-images.githubusercontent.com/5863899/34847954-498276f8-f6da-11e7-963e-202d93b43c18.png">

Seen on macOS 10.13.2 Chrome. For phetsims/QA#83.

**Comment by mbarlow12** [comment]
Fixed in master.

**Comment by phet-steele** [comment]
Fixed indeed.
