### ISSUE TITLE
No longer hearing voiced context responses on checkboxes

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#324]
I think something happened in Voicing common code. I am no longer hearing context responses on the checkboxes.

**Comment by terracoda** [comment]
Maybe this is a known issue?

**Comment by terracoda** [comment]
I would not like this bug to accidentally be published. Is it appropriate to add blocks simulation publication label?

**Comment by jessegreenberg** [comment]
Yes, that is appropriate. Thanks!

**Comment by jessegreenberg** [comment]
I am guessing that when common code support was added to Checkbox for Voicing, these usages were not updated. So the common code Voicing (not used and empty) is overriding the sim specific implementation.

**Comment by jessegreenberg** [comment]
We have a whole inner class that implements Voicing on a checkbox, that can be removed now that it is built into the main component.

**Comment by jessegreenberg** [comment]
Fixed with the above commit.
