### ISSUE TITLE
Sim Crashes when using Chrome & Voicing

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#325]
I have not yet investigated deeply, but the sim just crashed twice in quick succession when I was using the Voicing feature.

I was using Chrome Version 112.0.5615.49 (Official Build) (arm64)
MacOS Monterey 12.6.2

In both crashes I had the Voicing feature enabled, and I think I was also using the keyboard in both cases, but 100% sure on that.

On the second crash, I had just restarted chrome, loaded the sim from the website, enabled Voicing, checked surrounding context responses, returned to the sim, moved a mass sphere using my track pad, then pressed the Tab key. I think the sim crashed when I got to the Play buttons, but I was tabbing quickly, so not sure.

**Comment by jessegreenberg** [comment]
Hey @terracoda, thanks for reporting. I just tried to reproduce this on Windows 10 Chrome Version 112.0.5615.49 (Official Build) (64-bit) but have not been able to yet in either master or the published version on the PhET website.

Are you able to see any error messages in the dev tools? Are you able to reproduce this using master?

**Comment by jessegreenberg** [comment]
@Nancy-Salpepi or @KatieWoe would you be able to test (on the platform reported by @terracoda if possible) and see if you can reproduce this?

**Comment by Nancy-Salpepi** [comment]
I wasn't able to reproduce using macOS 10.15.7 and macOS 13.3.1 with chrome 112.0.5615.137.
@KatieWoe is going to attempt with macOS 12.

**Comment by KatieWoe** [comment]
The MacOS 12 device is having some trouble. It may be a while before it can be used to test.

**Comment by KatieWoe** [comment]
I didn't see this myself on MacOS 12.6 + Chrome. Sorry

**Comment by jessegreenberg** [comment]
OK, thats helpful to know. Thanks @Nancy-Salpepi and @KatieWoe.

Assigning back to you @terracoda, please let us know if this is still happening for you.

**Comment by terracoda** [comment]
Not crashing anymore. Apologies for the delay. Closing.
