### ISSUE TITLE
Use `ResetAllButton.isResettingAllProperty` to mute sound in `MassSoundGenerator`

### ISSUE THREAD

**Issue by jbphet** [phetsims/gravity-force-lab-basics#328]
In https://github.com/phetsims/tambo/issues/190 a more globally available flag was created that can be used to determine if a "reset all" action is in progress.  This could be used in `MassSoundGenerator` to mute sound generation during reset.

**Comment by jbphet** [comment]
Changes made.  Assigning to @zepumph for review, as he is listed as the responsible dev for this sim.

**Comment by jbphet** [comment]
Note that this also affects gravity-force-lab, but it doesn't seem like it's worth a separate issue.  Both should be reviewed.

**Comment by zepumph** [comment]
Looks great, thanks
