### ISSUE TITLE
Distance arrow text is not instrumented

### ISSUE THREAD

**Issue by phet-steele** [phetsims/gravity-force-lab-basics#33]
I cannot edit this AND there is no knowledge of it in the event stream:

<img width="808" alt="screen shot 2018-01-11 at 2 08 06 pm" src="https://user-images.githubusercontent.com/5863899/34847557-f8b14fc0-f6d8-11e7-90b6-73ebfa12237d.png">

Seen on macOS 10.13.2 Chrome. For phetsims/QA#83.

**Comment by mbarlow12** [comment]
Changes made in master.

**Comment by phet-steele** [comment]
Instrumented and in the data stream, nice!
