### ISSUE TITLE
Puller shadow is not instrumented

### ISSUE THREAD

**Issue by phet-steele** [phetsims/gravity-force-lab-basics#34]
I cannot disable it in instance proxies. Disabling the puller leaves the shadow behind:

<img width="254" alt="screen shot 2018-01-11 at 2 19 07 pm" src="https://user-images.githubusercontent.com/5863899/34847989-6ea29c9c-f6da-11e7-8cf3-576f6a20767d.png">

Seen on macOS 10.13.2 Chrome. For phetsims/QA#83.

**Comment by mbarlow12** [comment]
@samreid and I discussed. We'll instrument the entire puller, shadow, and rope in a single tandem.
