### ISSUE TITLE
Mass control panel strings are not instrumented

### ISSUE THREAD

**Issue by phet-steele** [phetsims/gravity-force-lab-basics#36]
These strings are without instrumentation (title and units):

<img width="281" alt="screen shot 2018-01-11 at 12 05 38 pm" src="https://user-images.githubusercontent.com/5863899/34842148-db2f5d4a-f6c7-11e7-9049-d2f26c75e526.png">

Seen on macOS 10.13.2 Chrome. For phetsims/QA#83.

**Comment by mbarlow12** [comment]
Instrumented in above commit. Closing.

**Comment by phet-steele** [comment]
Instrumented indeed!
