### ISSUE TITLE
Events:Recording playback not showing anything

### ISSUE THREAD

**Issue by brroberts1231** [phetsims/gravity-force-lab-basics#37]
When trying to play a recording of this sim at https://phet-io.colorado.edu/metacog/playback/ , no motion happened in the playback, and the following error showed up in the console. There were over 1900 of these errors for a roughly 30 second playback.
 `SimIFrameAPI Invocation Error: 
Error: invalid number of parameters
Stack trace:
invoke@https://www.colorado.edu/physics/phet/dev/html/gravity-force-lab-basics/1.0.0-dev.13/phet-io/gravity-force-lab-basics_all_phet-io.html?showPointers&phetioEmitStates=false&link&relativeSimPath&localFile:1950:2156516
handleSingleInvoke@https://www.colorado.edu/physics/phet/dev/html/gravity-force-lab-basics/1.0.0-dev.13/phet-io/gravity-force-lab-basics_all_phet-io.html?showPointers&phetioEmitStates=false&link&relativeSimPath&localFile:1950:2155612
handleRequest@https://www.colorado.edu/physics/phet/dev/html/gravity-force-lab-basics/1.0.0-dev.13/phet-io/gravity-force-lab-basics_all_phet-io.html?showPointers&phetioEmitStates=false&link&relativeSimPath&localFile:1950:2156088
initialize/<@https://www.colorado.edu/physics/phet/dev/html/gravity-force-lab-basics/1.0.0-dev.13/phet-io/gravity-force-lab-basics_all_phet-io.html?showPointers&phetioEmitStates=false&link&relativeSimPath&localFile:1950:2157101`

Seen when testing Win 10 Firefox version 57.0.4
I'll be testing whether I see the same in other browsers shortly. 
For phetsims/QA#83

**Comment by brroberts1231** [comment]
Seeing the same on Chrome 63.0.3239.132 and Edge 41.16299.15.0, and

**Comment by jessegreenberg** [comment]
Thanks @brroberts1231. I am unfamiliar with the recording/playback wrapper, @samreid would you be able to help?

**Comment by samreid** [comment]
Thanks @brroberts1231, can you please try playing it back with this playback wrapper?
https://www.colorado.edu/physics/phet/dev/html/gravity-force-lab-basics/1.0.0-dev.13/phet-io/wrappers/playback/playback.html

For future deploys, we are planning to publish a playback wrapper with each version of the sim instead of having a centralized one.  Can you also give me a reference to the testing instructions that guided you to https://phet-io.colorado.edu/metacog/playback/ so I can update it?

**Comment by lmulhall-phet** [comment]
Playback wrapper Ben is using gives this when given CLB recording.

`SimIFrameAPI Invocation Error: Error: invalid number of parameters
    at e.invoke (capacitor-lab-basics_all_phet-io.html?showPointers&phetioEmitStates=false&link&relativeSimPath&localFile:1060)
    at e.handleSingleInvoke (capacitor-lab-basics_all_phet-io.html?showPointers&phetioEmitStates=false&link&relativeSimPath&localFile:1060)
    at e.handleRequest (capacitor-lab-basics_all_phet-io.html?showPointers&phetioEmitStates=false&link&relativeSimPath&localFile:1060)
    at capacitor-lab-basics_all_phet-io.html?showPointers&phetioEmitStates=false&link&relativeSimPath&localFile:1060 Error: invalid number of parameters
    at e.invoke (https://www.colorado.edu/physics/phet/dev/html/capacitor-lab-basics/1.6.0-dev.3/phet-io/capacitor-lab-basics_all_phet-io.html?showPointers&phetioEmitStates=false&link&relativeSimPath&localFile:1060:1207721)
    at e.handleSingleInvoke (https://www.colorado.edu/physics/phet/dev/html/capacitor-lab-basics/1.6.0-dev.3/phet-io/capacitor-lab-basics_all_phet-io.html?showPointers&phetioEmitStates=false&link&relativeSimPath&localFile:1060:1206822)
    at e.handleRequest (https://www.colorado.edu/physics/phet/dev/html/capacitor-lab-basics/1.6.0-dev.3/phet-io/capacitor-lab-basics_all_phet-io.html?showPointers&phetioEmitStates=false&link&relativeSimPath&localFile:1060:1207298)
    at https://www.colorado.edu/physics/phet/dev/html/capacitor-lab-basics/1.6.0-dev.3/phet-io/capacitor-lab-basics_all_phet-io.html?showPointers&phetioEmitStates=false&link&relativeSimPath&localFile:1060:1208308`

New playback wrapper seems to work for CLB!

**Comment by phet-steele** [comment]
> Thanks @brroberts1231, can you please try playing it back with this playback wrapper?
> https://www.colorado.edu/physics/phet/dev/html/gravity-force-lab-basics/1.0.0-dev.13/phet-io/wrappers/playback/playback.html

@samreid QA was unaware of this change and this wrapper's existence. Can this wrapper be listed in wrappers/index please?

> Can you also give me a reference to the testing instructions that guided you to https://phet-io.colorado.edu/metacog/playback/ so I can update it?

There is no centralized location for these instructions, it is sim by sim in their phet-io rc matrix. @samreid I can update the appropriate spots and let QA know about this change.

**Comment by brroberts1231** [comment]
I went to https://phet-io.colorado.edu/metacog/playback/ because that is where I remember going when doing previous phetio-rc tests because it was linked to in the testing spreadsheets like this one: https://docs.google.com/spreadsheets/d/1gTOrMepJm5-fnNVWc81_dC4AqB1GMsrQHzv8cIHRF60/edit#gid=1613863951 in the Events: record column "Then click here for playback." 
This was the only place that I was aware of before now that would let us do playback.

**Comment by samreid** [comment]
It's a very new change, I'll create a link for it in the index.

**Comment by samreid** [comment]
I'll address that in https://github.com/phetsims/phet-io-wrappers/issues/48, anything else to do for this issue?

**Comment by phet-steele** [comment]
> anything else to do for this issue?

Negative, thanks.
