### ISSUE TITLE
Not able to move masses to 1.2 km after checking constant radius

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/gravity-force-lab-basics#39]
**Test device:**

MacBook Air

**Operating System:**

macOS 10.13.2

**Browser:**

Chrome, Firefox, Safari

**Problem description:**

The closest distance possible for the masses is 1.2 km. This distance is only achievable when the constant radius box is checked. Read the steps for more information. This is for phetsims/QA/issues/83.

**Steps to reproduce:**

1. Reduce masses to 1 billion kg.
2. Move them together. The distance should be 1.3 km.
3. Check the constant radius box.
4. Using the keyboard, try to move the masses 0.1 km closer together.

You should find that you're not able to move the masses closer together unless you first move one of the masses away from the other one.

This is only an issue with the keyboard.

**Troubleshooting information (do not edit):**

Name: ‪Gravity Force Lab: Basics‬
URL: https://www.colorado.edu/physics/phet/dev/html/gravity-force-lab-basics/1.0.0-dev.13/phet/gravity-force-lab-basics_all_phet.html?accessibility
Version: 1.0.0-dev.13 2018-01-11 18:09:43 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
Language: en-US
Window: 1440x700
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"104f3dcf","branch":"master"},"brand":{"sha":"53cf227b","branch":"master"},"chipper":{"sha":"c52ae6cb","branch":"2.0"},"dot":{"sha":"ee4d0e25","branch":"master"},"gravity-force-lab-basics":{"sha":"a6770ce9","branch":"master"},"inverse-square-law-common":{"sha":"3a3cd736","branch":"master"},"joist":{"sha":"1188c469","branch":"master"},"kite":{"sha":"e46f990e","branch":"master"},"phet-core":{"sha":"88a51822","branch":"master"},"phet-io":{"sha":"e31dae9a","branch":"master"},"phet-io-website":{"sha":"7440f48b","branch":"master"},"phet-io-wrapper-classroom-activity":{"sha":"c84e3046","branch":"master"},"phet-io-wrapper-lab-book":{"sha":"d128352d","branch":"master"},"phet-io-wrapper-sonification":{"sha":"fe4c6314","branch":"master"},"phet-io-wrappers":{"sha":"f844c39e","branch":"chipper2.0"},"phetcommon":{"sha":"85d72626","branch":"master"},"query-string-machine":{"sha":"b8bdcc28","branch":"master"},"scenery":{"sha":"f72ac66f","branch":"master"},"scenery-phet":{"sha":"7f2ddfbf","branch":"master"},"sherpa":{"sha":"9ca67479","branch":"master"},"sun":{"sha":"97f5c0ae","branch":"master"},"tandem":{"sha":"b77a8102","branch":"master"}}

**Comment by phet-steele** [comment]
@jessegreenberg this is true of any mass values, given that the masses were at the min distance apart at the time of step 3. I mention this since performing this bug when both masses are at 10 bkg sets the masses 2.5 km apart, which is very visually obvious that they should be able to get closer.

**Comment by jessegreenberg** [comment]
The enabled range updates when force changes, and when we drag with a mouse which is why it doesn't update with constant radius.

**Comment by jessegreenberg** [comment]
Should be fixed with https://github.com/phetsims/inverse-square-law-common/commit/c43d77805a4e30bceb259b1a81be53ca1da51198, @lmulhall-phet or @phet-steele could you please verify?

**Comment by phet-steele** [comment]
Looks great on master.
