### ISSUE TITLE
Sonification wrapper

### ISSUE THREAD

**Issue by emily-phet** [phetsims/gravity-force-lab-basics#42]
Need wrapper created as soon as phet-io testing complete.

**Comment by jbphet** [comment]
Assigning to @phet-steele so that he can let me know when testing is complete.

**Comment by emily-phet** [comment]
@jbphet looks like this sim's testing is nearing completion.

**Comment by jbphet** [comment]
I just checked in with @phet-steele on this, and there is a little left to do on it, so he will assign it to me when it's ready.

**Comment by emily-phet** [comment]
@lmulhall-phet can you give me an update on this asap?

**Comment by lmulhall-phet** [comment]
@emily-phet, I was under the impression that QA was going to get another issue to test GFLB, but I talked to @jbphet this morning, and it seems like the testing was done in phetsims/QA/issues/97.

If this is not correct, let me know. @phet-steele might be more familiar with GFLB and whether it requires further testing.

**Comment by emily-phet** [comment]
this issue is old - phet-io and wrapper was complete awhile back.
