### ISSUE TITLE
Constant Radius option is not clickable through whole area

### ISSUE THREAD

**Issue by BryceAG** [phetsims/gravity-force-lab-basics#45]
The Constant Radius option will only be interactive if the mouse or touch is in the top half of its pointer area. All other options are interactive through whole area. 
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/15327201/35827475-6fb4122a-0a79-11e8-9a7f-436ff336ca3a.gif)

Present on Windows 10, Chrome, Firefox, and Edge. Related to phetsims/QA#88

**Comment by lmulhall-phet** [comment]
@BryceAG I'm not able to reproduce the issue on any of the browsers.

**Comment by mbarlow12** [comment]
@BryceAG same here—can't reproduce. Could you give some more details on your configuration?

**Comment by lmulhall-phet** [comment]
@BryceAG @mbarlow12 Just to be clear, I can't reproduce the issue on Windows in any browser.

**Comment by jessegreenberg** [comment]
@phet-steele can this issue be closed or do you recommend spending more time trying to reproduce?

**Comment by mbarlow12** [comment]
@phet-steele any suggestions as to @jessegreenberg 's above comment?

**Comment by lmulhall-phet** [comment]
@mbarlow12 @jessegreenberg I’ll give this one more shot tomorrow morning. If I can’t reproduce it, I think we should go ahead and close the issue.

**Comment by BryceAG** [comment]
I was testing on Hanson, I have no idea why it can't be reproduced. I will try to reproduce it and include more testing information.

**Comment by BryceAG** [comment]
No longer reproducible, have no idea why it was happening on Hanson on all browsers before, but it seems good now. Sorry for the inconvenience. Closing
