### ISSUE TITLE
Credits are missing

### ISSUE THREAD

**Issue by samreid** [phetsims/gravity-force-lab-basics#47]
Noted while I was deploying an RC for #46

**Comment by arouinfar** [comment]
Lead Designer: Amy Rouinfar
Team: Ariel Paul, Kathy Perkins
Devs: Michael Barlow, Jesse Greenberg
Graphic Arts: Mariah Hermsmeyer

**Comment by mbarlow12** [comment]
I have the initial credits as @arouinfar noted above. @samreid should I include you as well? @phet-steele, should I include just you on QA or the other QA team as well?

**Comment by phet-steele** [comment]
> @phet-steele, should I include just you on QA or the other QA team as well?

@mbarlow12 I will update QA credits myself once RC testing is complete.

**Comment by samreid** [comment]
> @samreid should I include you as well? 

No thanks, but thanks for asking!

**Comment by zepumph** [comment]
Demoting priority for now.

**Comment by terracoda** [comment]
When we are ready to publish the accessible version of this sim we will need to add more people to the credits:
- Team: Emily Moore and Taliesin Smith
- Devs: Michael Kauzmann
- Sound Design: Ashton Morris, anyone else??

**Comment by KatieWoe** [comment]
QA: Megan Lai, Liam Mulhall, Laura Rea, Jacob Romero, and Kathryn Woessner should all be there.

**Comment by terracoda** [comment]
@zepumph, adding priority to this issue, so it's on your radar.
I had trouble accessing the sim today, so I don't actually know what credits are missing.

**Comment by zepumph** [comment]
How's that @terracoda ?

**Comment by terracoda** [comment]
@zepumph, I think names are supposed to be alphabetical order by last name. Could you double check that? I think the devs  are not listed that way. I am not sure of all the conventions.

**Comment by terracoda** [comment]
@zepumph, the names all look good though, so if the dev order is good, you can close this issue.
