### ISSUE TITLE
Distance control change of 1 km

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/gravity-force-lab-basics#5]
From the design doc:

> Increase the distance from 4 km to 8 km using the slider. The masses will move equally away from one another. Both masses will move 2 major steps away from one another.

@arouinfar just so I am sure, what should happen when the slider is moved from 4km to 5km?  Would each mass move 0.5 km  so they are in between the grey lines?

**Comment by arouinfar** [comment]
Great question @jessegreenberg. Distance is discretized to the 0.1 km level, so I think the masses would need to move asymmetrically -- one mass would move 0.2 km, and the other mass would move 0.3 km. I'm not sure what would be the best way to decide which mass moves more, however.

**Comment by arouinfar** [comment]
We can talk about this more during design meeting. There are still a few things to flesh out in regards to the distance controls.

**Comment by jessegreenberg** [comment]
We decided to remove the distance slider from the UI.  The masses can be dragged, and through the dragging the positions will snap to the nearest 0.1 km/0.01 km (to be decided). Closing.
