### ISSUE TITLE
Checkboxes are scaled down with long strings

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/gravity-force-lab-basics#51]
It looks like the check boxes themselves (not just the text) are being scaled for i18n.
![capture](https://user-images.githubusercontent.com/6396244/36875432-23892fb4-1d6d-11e8-8d72-b0418ceb8e25.PNG)

I did a little searching, and it looks like maxWidth is only set on the text so I am not sure why this is happening.

UI looks good for doubled strings. 

![capture](https://user-images.githubusercontent.com/6396244/36875846-37e154b2-1d6f-11e8-9256-0c69122e2904.PNG)

For very long strings is this a usability problem? @mbarlow12 can you investigate? For #49.

**Comment by mbarlow12** [comment]
In ISLCCheckboxPanel.js, ln 36:
```
    // the checkboxes in the group will be as wide as the labels are tall
    var checkboxWidth = _.max( checkboxItems.map( function( item ) {
      return item.content.height;
    } ) );
```
@samreid added that height adjustment in https://github.com/phetsims/inverse-square-law-common/commit/6e161bd653193819df55b28da4a7895769751805#diff-db12b6e22fef977bb5446a345cdd0223. That same feature is done in Projectile Motion on the PhET website. I'm ok with the change.

**Comment by jessegreenberg** [comment]
Thanks @mbarlow12,  good to know. I looked through translations of Projectile Motion, strings generally don't get long enough for this to be a problem. It seems unnecessary to me but I don't feel strongly. Closing.
