### ISSUE TITLE
Can showGrid query pram be removed from GravityForceLabBasicsQueryParameters?

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/gravity-force-lab-basics#58]
inverse-square-law-common supports showGrid, and I think the grid is implemented there. I think this querey  param can be removed from GravityForceLabBasicsQuereyParameters.js.

**Comment by jessegreenberg** [comment]
Likewise can GridNode be deleted and replaced with ISLCGridNode?

**Comment by mbarlow12** [comment]
Completed in the above commit. Furthermore, I moved the showDragBounds parameter to ISLC to remove the need for sim specific query parameters.

We'll also consolidate the displays in https://github.com/phetsims/inverse-square-law-common/issues/46.
