### ISSUE TITLE
Options extension without setting options

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/gravity-force-lab-basics#59]
For #49. I saw this code in DistanceArrowNode.
```js
    _.extend( {
      tandem: Tandem.required
    }, options );
```

I think this was added for PhET-iO instrumentation. @mbarlow12 @samreid should this be
```js
    options = _.extend( {
      tandem: Tandem.required
    }, options );
```

**Comment by samreid** [comment]
The options was incorrect, but I don't think we need to require a tandem for the DistanceArrowNode.  I'm inclined to eliminate that statement altogether.

**Comment by jessegreenberg** [comment]
Sounds good to me, thanks @samreid.

**Comment by mbarlow12** [comment]
It looks like we're setting a tandem for the label text at the moment. @samreid are you thinking that we don't need any tandems for the DistanceArrowNode, or that we simply don't want to require it.

**Comment by samreid** [comment]
I'm thinking that we don't need to require the tandem (though we may supply it anyways).

**Comment by mbarlow12** [comment]
Requirement removed, but we're still passing the tandem through the options.
