### ISSUE TITLE
Add static descriptions to this sim

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/gravity-force-lab-basics#61]
@emily-phet @terracoda @arouinfar this sim is about a week away from an RC. This sim has a keyboard help dialog and keyboard navigation. Could we design and add labels for this simulation?

**Comment by arouinfar** [comment]
Exciting news @jessegreenberg! 

@terracoda are the labels a bare-bones description for screen reader users? For example, if a user tabs to a slider that changes an object's mass, would the screen reader read out the corresponding label (eg. "Mass Slider")? Would the labels include any information about the value? Sorry for all the questions, I haven't created any labels before!

**Comment by terracoda** [comment]
Great questions @arouinfar, the value and units are part of the slider information. That info is read out automatically.

Labels are what you want all users to understand about what the interactive sim object is meant to ne and do and hopefully cue how to interact with it. Imagine if all the objects were just plain buttons, what text do you want on each button to identify and distinguish each interactive thing.

For key interactive objects I like the labels to be action oriented if makes sense, e.g. "Grab Yellow Balloon", but a label without a verb can make just as much sense, too.

The "slider" part is not needed in the label as it is read out automatically by screen reader software from the aria `role="slider"`. Also from the html code, a screen reader user should hear that the slider has a horizontal orientation, so they will likely try left/right arrow keys to move the mass. 

Label: "Mass ??" - need to take into account there are two and the pushers?
Possible on-demand help text: "Move mass pushers left and right to play??" "Push mass left and right to play???"

I'll come back to this later.

**Comment by jessegreenberg** [comment]
> the value and units are part of the slider information. That info is read out automatically.

Units are actually not included automatically. Do they need to be for these releases?

> Possible on-demand help text

IMO help text is not necessary for a keyboard navigation release, but maybe we have begun to include it.

**Comment by arouinfar** [comment]
Thanks @terracoda! 

Some of these may be more like help text, but here are some drafted labels:

* Mass 1/2 Slider: Move mass 1/2
* Mass 1/2 Number Picker: Change (value of) mass 1/2
* Show Values Checkbox: Show force values
* Distance Checkbox: Show distance between masses
* Constant Radius Checkbox: Keep radius constant when changing mass

I think this would be helpful to discuss during next week's keyboard nav meeting, as well.

**Comment by terracoda** [comment]
@arouinfar, I'm not clear about which thing is putting force on the other, but here's a quick stab. Not e that commas separate the actual label text from what the sim object's role. The role is readout automatically by the screen reader software.

Mass 1, slider
1. Help text: Move to change force on Mass 1 by Mass 2.
2. Help text: Move to play with force on Mass 1 by Mass 2.

Mass 2, slider
1. Help text: Move to change force on Mass 2 by Mass 1.
2. Help text: Move to play with force on Mass 2 by Mass 1.

Adjust Mass , ? (not sure how this sim control is represented in HTML)
1. Help text: Adjust mass 1 in billions of kilograms.

Adjust Mass 2, ? 
1. Help text: Adjust mass 2 in billions of kilograms.

H3: Sim Options or Sim Screen Options or Play Area Options??
Draft labels and help text for check boxes:
1. Label: Show Values, checkbox checked
2. Label:  Show Force Values, checkbox checked
If option 1, you might need some help text: Show/hide force value for masses.
Alerts: Force values added to/removed from sim screen.

1. Label: Show Distance, checkbox checked
2. Label: Show Distance Between Masses, checkbox checked
If option 1, you might need some help text: Show/hide distance between masses.
Alerts:  Distance between masses added to/removed from sim screen.

1. Label: Constant Radius, checkbox, not checked
Help text: Restrict representation each mass to a constant radius.
Alert: Masses each shown with the same radius.
Alert: Masses each shown with proportional radius.

Label: Reset All
No help text needed.

**Comment by terracoda** [comment]
@jessegreenberg, sorry, I assumed units were read out automatically because they are read out in OL and RIAW.

**Comment by terracoda** [comment]
@arouinfar, I started https://github.com/phetsims/gravity-force-lab-basics/issues/62 to find out about how the Mass tweakers are represented.

**Comment by terracoda** [comment]
@arouinfar, actually, maybe we need the word "Size" in the label for the spinbuttons?
I am going to add a second label option to https://github.com/phetsims/gravity-force-lab-basics/issues/61#issuecomment-371253769

**Comment by terracoda** [comment]
@arouinfar, keep in mind the alerts are not part of label implementation, but I added them there for some context.

**Comment by emily-phet** [comment]
@arouinfar Please put the latest draft of labels in the A11y design doc for this sim, similar to how it is done in Rutherford Scattering's A11y design doc. 
Rather than thinking about these as a list - I think it would help to think of them as content in a document that is being navigated, and putting them in the design doc in that format will help.

**Comment by arouinfar** [comment]
@emily-phet @terracoda I've drafted headings, labels, and help text in the GFLB a11y doc. We an review it in an upcoming keyboard nav meeting. Unassigning myself for now.

**Comment by arouinfar** [comment]
@terracoda and I met today to work on the static descriptions. The latest iteration can be found in the [GFLB a11y doc](https://docs.google.com/document/d/1HdDG9ds2MdbCb21l9qk3cI8yBQxK6-wBWNXC4Tloji8/edit#heading=h.8105qxybjgyi). Discussion should continue in the keyboard nav meeting, so I've added this issue to the agenda.

**Comment by jessegreenberg** [comment]
Today @arouinfar mentioned that static descriptions for this sim are ready to implement. @arouinfar are the latest descriptions still in [GFLB a11y doc](https://docs.google.com/document/d/1HdDG9ds2MdbCb21l9qk3cI8yBQxK6-wBWNXC4Tloji8/edit#heading=h.8105qxybjgyi)?

**Comment by arouinfar** [comment]
In working on the static descriptions for Coulomb's Law https://github.com/phetsims/coulombs-law/issues/43, we made a few decisions that would also apply to GFLB. I've updated the GFLB a11y design doc to reflect these changes. @mbarlow12 no further changes are anticipated at this time.

**Comment by jessegreenberg** [comment]
7/17/18 - this sim will get redeployed without a11y initially, a later version of the sim will include description and keyboard navigation.

**Comment by emily-phet** [comment]
This sim is getting full description and sound. Closing this issue, as full description work will be tracked in other issues.
