### ISSUE TITLE
Create sim primer

### ISSUE THREAD

**Issue by arouinfar** [phetsims/gravity-force-lab-basics#67]
For #16 

- [x] Draft script - 6/5/18
- [x] Record rough version for script verification - 6/7/18
- [x] Review script verification draft, and adjust script as necessary - 6/7/18
<s>Record another draft</s>
<s>Review 2nd draft</s>
- [x] Produce primer and upload 6/13/18
- [x] Caption primer 6/13/18

**Comment by arouinfar** [comment]
Should be done in conjunction with https://github.com/phetsims/gravity-force-lab/issues/97 and https://github.com/phetsims/coulombs-law/issues/56.

**Comment by arouinfar** [comment]
@CWilson4960 the script for GFLB is ready for recording. 

Here's a dev version you can use for recording.
https://bayes.colorado.edu/dev/html/gravity-force-lab-basics/1.0.0-dev.22/phet/gravity-force-lab-basics_en_phet.html

**Comment by arouinfar** [comment]
The primer has been recorded and uploaded to Vimeo, but is awaiting sim publication.

**Comment by arouinfar** [comment]
Since the sim primer is in the master checklist, I'll go ahead and close this issue.

**Comment by zepumph** [comment]
@arouinfar once this sim is published, is anything needed related to the sim primer? I noticed the checkbox in the master list about this is already checked and pointing to this issue.

**Comment by arouinfar** [comment]
Thanks for checking in @zepumph. There is a place for the primer link on the sim admin page. Part of the process to make the sim visible will include adding the primer link. 

I have some upcoming travel this summer, so in the event that someone else will be making the sim visible, I've added the primer link to the [Website Info](https://docs.google.com/document/d/1er1JLZLJGmvTkZNCIEAkEm8RhSm_xGAu2jEFWtVuX-E/edit#heading=h.ihv636) section of the design doc which also contains the keywords, description, etc.
