### ISSUE TITLE
Constant Size on by default?

### ISSUE THREAD

**Issue by arouinfar** [phetsims/gravity-force-lab-basics#69]
Mass and size can be conflated by some students, which was (part of) the [original motivation](https://github.com/phetsims/gravity-force-lab/issues/36) for adding the Constant Size feature to GFL.  

When reviewing the interview with an 8th grader, I noticed that the student initially cited "size" as one of the variables which affects the force. While I'm a bit hesitant to read much into N=1, I do wonder if younger students (who are likely less familiar with density) may generally have a harder time teasing apart mass and size.

@ariel-phet I was thinking we may want to make Constant Size on by default for GFLB. This could allow students to discover the variables to change the force without layering on the complexity of  a variable radius. What do you think?

**Comment by ariel-phet** [comment]
@arouinfar my personal opinion goes something like this....

I do think it is OK if at first a young student thinks of "size" as being a variable that affects the force. In this case, I think size is a proxy for mass. Students are generally familiar with the idea that as similar objects grow larger, they get "heavier". So I actually think it is a good starting point. 

I think the beauty of having the constant size option, is that once a student plays around, and then uses that option, they can begin to question whether size and mass have to be related. I actually think this is the correct scaffolding and flow. The "bigger is more" cue is very powerful, so it seems useful to start there, and then as the student engages more with the sim, have them start to question some assumptions.

**Comment by arouinfar** [comment]
@ariel-phet you make some great points, particularly:

> The "bigger is more" cue is very powerful

Rather than making Constant Size on by default, I can instead make some adjustments to the teacher materials I've been working on.
