### ISSUE TITLE
What else is needed to deploy this simulation?

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/gravity-force-lab-basics#70]
On 7/17/18, it was discussed that this 1.0 version of this sim is not going to include a11y. @ariel-phet @arouinfar @mbarlow12 is anything else needed to deploy this sim? gravity-force-lab-basics received a code review.

**Comment by arouinfar** [comment]
@jessegreenberg I'd like to a review of the latest dev and give it my final sign-off before moving forward with QA testing.

**Comment by jessegreenberg** [comment]
Thanks @arouinfar, here is the latest dev version (built 7/16/18).
https://bayes.colorado.edu/dev/html/gravity-force-lab-basics/1.0.0-dev.24/phet/gravity-force-lab-basics_all_phet.html

The last dev test of gravity-force-lab-basics was dev.20 - we are now up to dev.24. I also think we should review commits between the two versions and determine if we should do another dev test.

**Comment by arouinfar** [comment]
Thanks for the link @jessegreenberg.

> The last dev test of gravity-force-lab-basics was dev.20 - we are now up to dev.24. I also think we should review commits between the two versions and determine if we should do another dev test.

I think most of the changes between dev.20 and dev.24 were pixel-polishing, but it would be good idea to take a look at the commits just to be sure.

**Comment by arouinfar** [comment]
@jessegreenberg dev.24 looks good to me! I think it's ready for QA.

Is the plan to publish the sim with keyboard nav enabled? It seems to be working properly, and the dialog is up-to-date, so I don't see why not.

**Comment by arouinfar** [comment]
The only caveat for the keyboard dialog is that we plan to make some general changes, as described in https://github.com/phetsims/a11y-research/issues/113, but the current dialog is formatted consistently with already-published keyboard navigable sims so I don't think it's an issue.

**Comment by arouinfar** [comment]
> My recommendation would be to hold off from publishing keyboard nav for the moment. I think ideally we want to start to enforce the workflow that if we are publishing with keyboard nav we are also including static description.

That's a really good point @ariel-phet. It probably makes the most sense to disable the keyboard nav until the descriptions are being worked on, but let's see what @emily-phet recommends.

**Comment by mbarlow12** [comment]
@ariel-phet @jessegreenberg was the decision that GFLB would also get another code review prior to RC testing?

**Comment by jessegreenberg** [comment]
We discussed this in a 7/24/18 a11y meeting. @emily-phet said that if there is nothing known that would block keyboard navigation for this sim, then there is no reason to not publish it with keyboard nav. We should go ahead and include keyboard navigation in the QA testing for this simulations release. There is more work to be done for coulombs-law keyboard navigation so we will not include it in that one.

**Comment by emily-phet** [comment]
Let me know if there are questions about this decision.

**Comment by arouinfar** [comment]
Seeing CL make some progress this week has gotten me curious about the status of GFLB. 

It sounds like this sim doesn't require another code review, so are we ready to move forward with QA testing @mbarlow12 @jessegreenberg?

**Comment by jessegreenberg** [comment]
Sorry for the delay @arouinfar, I think that this sim is ready. But I would recommend a dev test first, there have been common code changes to ISLC and ACcessibleSlider (at least).

**Comment by arouinfar** [comment]
Excellent, thanks @jessegreenberg! I think QA is relatively quiet, so I'm sure they'd appreciate seeing this come up for a dev test -- I know I would! :)

**Comment by jessegreenberg** [comment]
OK great! @mbarlow12 could you please create a dev test for this sim? I think the QA team has a new template for dev tests we can give it a test drive here.

https://github.com/phetsims/QA/blob/master/issue-templates/dev-test-template.md

**Comment by mbarlow12** [comment]
New dev test issue created at:
https://github.com/phetsims/QA/issues/199

There's also a fresh dev version:

https://phet-dev.colorado.edu/html/gravity-force-lab-basics/1.0.0-dev.26/phet/gravity-force-lab-basics_en_phet.html

**Comment by emily-phet** [comment]
This sim will be published with full description, alternative input, and sound. Closing this issue, as it seems to be mostly about publishing with alternative input only.
