### ISSUE TITLE
innerContent needed for items in the keyboard help dialog

### ISSUE THREAD

**Issue by zepumph** [phetsims/gravity-force-lab-basics#71]
I updated HelpContent.labelWithIcon so that it requires innerContent (to help catch bugs like this). Here is what the PDOM looks like when I use just a place holder for the innerContent:

![image](https://user-images.githubusercontent.com/6856943/43350974-8cf7211c-91b8-11e8-90b1-2d6e0c0e5bc1.png)

@emily-phet I'm not sure who to assign this to, so it's coming to you. This would need to be done before any a11y related publication.

**Comment by zepumph** [comment]
Found from https://github.com/phetsims/scenery-phet/issues/391

**Comment by jessegreenberg** [comment]
While reviewing https://github.com/phetsims/scenery-phet/issues/391 I found this content in https://github.com/phetsims/gravity-force-lab-basics/issues/29#issuecomment-364934762 from https://github.com/phetsims/gravity-force-lab-basics/issues/29.

```
Move Spheres
Move sphere left and right with the Left and Right Arrow keys.
Move in larger steps with Page Up and Page Down keys.
Jump to left with Home key.
Jump to right with End key.

Change Mass
Increase mass with Up or Right Arrow key.
Decrease mass with Down or Left Arrow key.
Change mass in larger steps with Page Up and Page Down keys.
Jump to maximum mass with Home key.
Jump to minimum mass with End key.

General Navigation
Move to next item with Tab key.
Move to previous item with Shift plus Tab key.
Exit a dialog with Escape key.

Updated content April 10 after Keyboard dialog meeting.
```

Ill add it quickly so we can continue in https://github.com/phetsims/scenery-phet/issues/391.

**Comment by jessegreenberg** [comment]
Done in the above commit.
