### ISSUE TITLE
Enter doesn't select check boxes

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-force-lab-basics#73]
**Test device:**
Dell Laptop
**Operating System:**
Win 10
**Browser:**
Chrome
**Problem description:**
For https://github.com/phetsims/QA/issues/199.
Mostly a question.  I have noticed that, while you can select and unselect checkboxes using keyboard nav with the space bar, you can't use the enter key.  This seems odd to me as you can use enter for the reset all button and I believe you can use it in other sims.
**Steps to reproduce:**
1. Use keyboard nav to go to the Force Values checkbox
2. Press enter (nothing happens)
3. Press space (box is checked/unchecked)

**Troubleshooting information (do not edit):**

<details>

Name: ‪Gravity Force Lab: Basics‬
URL: https://phet-dev.colorado.edu/html/gravity-force-lab-basics/1.0.0-dev.26/phet/gravity-force-lab-basics_en_phet.html
Version: 1.0.0-dev.26 2018-10-03 17:55:25 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
Language: en-US
Window: 1536x732
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"f57d7489","branch":"master"},"brand":{"sha":"1fd6682e","branch":"master"},"chipper":{"sha":"e7e260b0","branch":"master"},"dot":{"sha":"a6af5081","branch":"master"},"gravity-force-lab":{"sha":"afde84e2","branch":"master"},"gravity-force-lab-basics":{"sha":"25c977e5","branch":"master"},"inverse-square-law-common":{"sha":"da8e0a7b","branch":"master"},"joist":{"sha":"2032a802","branch":"master"},"kite":{"sha":"380cef53","branch":"master"},"phet-core":{"sha":"2ff7b489","branch":"master"},"phet-io":{"sha":"45f8664d","branch":"master"},"phet-io-wrapper-classroom-activity":{"sha":"abc4ae3e","branch":"master"},"phet-io-wrapper-hookes-law-energy":{"sha":"429886e7","branch":"master"},"phet-io-wrapper-lab-book":{"sha":"186d07de","branch":"master"},"phet-io-wrappers":{"sha":"d6eaaedd","branch":"master"},"phetcommon":{"sha":"33aef589","branch":"master"},"query-string-machine":{"sha":"9ae63aab","branch":"master"},"scenery":{"sha":"cda0945c","branch":"master"},"scenery-phet":{"sha":"dd1fbed6","branch":"master"},"sherpa":{"sha":"77e666c5","branch":"master"},"sun":{"sha":"38c10e6d","branch":"master"},"tambo":{"sha":"fe63321c","branch":"master"},"tandem":{"sha":"6c14e492","branch":"master"}}

</details>

**Comment by mbarlow12** [comment]
Appears to be the same as phetsims/coulombs-law#69. Closing.
