### ISSUE TITLE
Mouse over behavior remains when mouse disappears

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-force-lab-basics#74]
**Device**
MacBook Air
**OS**
10.14
**Browser**
Firefox
**Problem Description**
For https://github.com/phetsims/QA/issues/199 likely shows up in other sims as well.
Certain elements change visually when moused over.  In this sim mousing over the mass controls causes half of the number to look red or blue, depending on the control.  If this occurs and the control method shifts in a way that makes the mouse disappear the mouse over look remains.  This is seen with keyboard nav and multitouch.
**Steps to Reproduce**
1. Move mouse over a part of the number control
2. Hit tab to start keyboard nav
3. Note that blue or red highlight behavior is there even though mouse is gone.

**Alternative Method**
1. Go to chrome on a Win 10 touch screen device
2. Put the mouse over a part of the number control
3. Use your finger to drag one of the spheres
4. Note that blue or red highlight behavior is there even though mouse is gone.

**Screenshots**
![screen shot 2018-10-05 at 12 59 05 pm](https://user-images.githubusercontent.com/41024075/46557455-29bac600-c8a7-11e8-9ccb-789b49fe9b51.png)

**Comment by mbarlow12** [comment]
This is a little tricky as its handled within `NumberPicker` by `updateColors()` internally, so I'm not sure how we'd access the blue/red highlights from a `blur` event in the sim. I _think_ that the mouse is still technically 'over' the number picker.

I was tinkering within number picker with a blur event, and what results is that the styling is removed; however, when the mouse moves again, it has to completely exit the element and move back over to activate the hover state of the picker. @jessegreenberg do you have any ideas?

**Comment by arouinfar** [comment]
> I think that the mouse is still technically 'over' the number picker.

For the first method (mouse + keyboard), this sounds correct, but is this true even for the alternative method described by @KatieWoe? Shouldn't the touch event move the cursor?

@KatieWoe can you reproduce the alternative method for a sim with a `NumberPicker` (e.g. Proportion Playground)?

**Comment by KatieWoe** [comment]
@arouinfar just checked on published Proportion Playground and the multitouch method of producing this effect happens there too.

**Comment by mbarlow12** [comment]
@arouinfar @KatieWoe the second situation does seem more problematic, but I'm pretty unfamiliar with touch screen + mouse interaction. Can we confirm whether the touch event moves the cursor?

**Comment by arouinfar** [comment]
I had that exact same question @mbarlow12, so I followed up with @KatieWoe. It appears that a touch event doesn't actually move the cursor position. 

For example:
* Use the mouse to press `ResetAllButton`
* Use touchscreen to interact with some other UI element elsewhere in the sim
* Moving the mouse, the cursor is still located near `ResetAllButton`

Given that touch and keyboard events do not move the cursor, I don't think this is actually a bug, just an astute observation by @KatieWoe.

I think we can safely close this issue @mbarlow12.

**Comment by mbarlow12** [comment]
Thanks @arouinfar @KatieWoe!
