### ISSUE TITLE
Person goes slightly off screen on iPad

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-force-lab-basics#75]
**Device**
iPad Air 2
**OS**
iOS 12
**Browser**
Safari
**Problem description**
For https://github.com/phetsims/QA/issues/199
When the person pushing/pulling an orb is on the very side of the screen, it is possible to make them lean off screen.  This does not affect the performance or usability of the sim.
**Steps to Reproduce**
1. Enter sim on an iPad
2. Pull both orbs as far left as they will go.
3. Make sure orbs are not at a constant size.
4. Make both as massive as possible
5. Observe left person

**Screenshot**
![img_1316](https://user-images.githubusercontent.com/41024075/46564242-5b418a80-c8c3-11e8-8c25-b806bc2762b3.PNG)

**Comment by arouinfar** [comment]
Nice find @KatieWoe. While this is not strictly a usability issue, I do find it a bit odd.

Comparing to other ISLC sims, GFLB appears to be the outlier.

![image](https://user-images.githubusercontent.com/8419308/46564909-a9588d00-c8c7-11e8-9b36-96174218edea.png)
![image](https://user-images.githubusercontent.com/8419308/46564911-b07f9b00-c8c7-11e8-8813-c501603bc796.png)

Is it possible that the grid spacing is somehow different in GFLB? I would have thought it would be the same across all ISLC sims. @mbarlow12 can you investigate?

**Comment by mbarlow12** [comment]
Good point. I noticed in GLF it's set to 4.8, so this adjustment makes sense. Thanks!

**Comment by mbarlow12** [comment]
I believe this is fixed. @arouinfar @KatieWoe can we close this issue?

**Comment by arouinfar** [comment]
@mbarlow12 I am unable to reproduce the original issue. 

The figure's shadow does get slightly clipped, but I would prefer to keep `MAX_DISTANCE_FROM_CENTER` as large as possible.

![image](https://user-images.githubusercontent.com/8419308/46827842-ed7bdf80-cd56-11e8-93f6-5b5d4ae084a4.png)

@KatieWoe can you check this on iPad?  If the situation looks like the screenshot above, please close.

**Comment by KatieWoe** [comment]
Looks about right on master.

**Comment by mbarlow12** [comment]
@arouinfar I added a little tweaking to the shadows so they sit a little more directly underneath the pullers.

**Comment by arouinfar** [comment]
Looks good @mbarlow12, thanks!
