### ISSUE TITLE
Where should distance go in the PDOM?

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#78]
The description for the distance between the center of the spheres is currently out of place.

I'm not sure exactly where to put it, so marking this as discussion point for today's Design Meeting.
<img width="460" alt="screen shot 2018-11-06 at 3 07 01 pm" src="https://user-images.githubusercontent.com/1902116/48069764-8971fd00-e1d6-11e8-8e6a-6215520cc105.png">

**Comment by terracoda** [comment]
@terracoda will make sure design doc for this is clear.

**Comment by terracoda** [comment]
I think the paragraph describing distance should come right after the H3 heading for Sphere Positions.

And it could also be an alert when the Distance checkbox is checked.

**Comment by terracoda** [comment]
A dynamic paragraph containing the distance between the two spheres is to go under the Sphere Positions h3 heading in the PDOM, and before the paragraph containing the help text for the sphere position sliders. 

I have updated the design document, see [Sphere Positions in PDOM section](https://docs.google.com/document/d/1HdDG9ds2MdbCb21l9qk3cI8yBQxK6-wBWNXC4Tloji8/edit#heading=h.7pi83hpdmyxw).

As noted in the design document, the paragraph is removed from the PDOM when the Distance checkbox is not checked.

**Comment by terracoda** [comment]
The rough HTML goes like this:
H3: Sphere Positions
P: Centers of spheres are {{4}} kilometers apart.
P: Move spheres closer or farther from each other.
Input type range: mass 1 position, slider
Input type range: mass 1 position, slider

**Comment by zepumph** [comment]
1. Move `masses are 4 km apart` in between "Sphere Positions" and the help text (Move spheres, closer or further from each other). It will also need rewording (in the design document).
2. "‪mass 1‬ and ‪mass 2‬ are extremely close each other, centers exactly 4 kilometers apart." Remove ", centers exactly 4 kilometers apart"

@terracoda will add more nuances as she encounters them.

**Comment by zepumph** [comment]
RE number 1:

In the code it was easiest to put the help text and this distance description into the same paragraph, like
![image](https://user-images.githubusercontent.com/6856943/51775128-23906580-20a1-11e9-93ab-6b4fee972c8e.png)

The reasoning is that right now it is all one node, from top to bottom it is the label sibling, the description sibling, and then the primary sibling:

![image](https://user-images.githubusercontent.com/6856943/51775201-63574d00-20a1-11e9-920f-bb5e094703fb.png)


@terracoda let me know if you would like me to do a bit of refactoring so that they are separate paragraphs (more than one node).

**Comment by zepumph** [comment]
RE number 2:

@terracoda I didn't know if you wanted that piece completely removed, or just removed in GFLB. Can you disambiguate for me please?

**Comment by terracoda** [comment]
@zepumph, great question.

We can keep the distance phrases in GFL REGULAR as there is no checkbox to remove distance in that sim, and we want the use of the ruler to be completely optional for non-visual users.

In GFL BASICS, I would like the quantitative distance phrase removed from the PDOM (here at the front of the sphere positions help text), when the Distance checkbox is not checked. This removal is currently working up in the Scene Summary.

There will be some places in the alerts, too, (still for me to identify when I review the position alerts) where we will need to remove quantitative distance phrases.

In addition, I would like the distance phrase to be:
- "Centers of spheres, {{4}} kilometers apart."

And it is fine that this phrase and the help text are in the same paragraph in both sims.

**Comment by zepumph** [comment]
I removed the "centers exactly" just for BASICS in the above commit. I see two more things left for this issue before review. @terracoda please let me know if anything I'm doing doesn't match what you asked for above:

* While working on the above commit, I noticed that `qualitativeDistance` in `PositionDescriber.getObjectDistanceSummary()` wasn't working correctly for GFLB. I didn't check in REGULAR.
* I also need to change the sentence under "Sphere Positions" from something like "Masses are {{3}} km apart." to "Centers of spheres, {{4}} kilometers apart." For both REGULAR and BASICS.

**Comment by zepumph** [comment]
@terracoda ready for review!

**Comment by terracoda** [comment]
@zepumph, this distance string is in the right place - just before the help text. Exact wording and changes to the strong when the Distance checkbox is checked or notchecked are now being tracked in #101. 

Thus, closing this issue.
