### ISSUE TITLE
Change m1 and m2 to mass 1 and mass 2

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#81]
@zepumph, I just noticed that m1 and m2 are being used in the h3 headings that describe the spheres.
Please change the content of the h3 headings to:
- mass 1, Blue Sphere 
- mass 2, Red Sphere

<img width="967" alt="incorrect-h3-heading-content" src="https://user-images.githubusercontent.com/1902116/51031615-6defed80-159d-11e9-9cfd-8d8447b2296c.png">

Note that there are other places where m1 and m2 show up in this sim. I'll make separate issues as I find them.

**Comment by zepumph** [comment]
After speaking with @terracoda, she will note any more cases she finds in this issue.

**Comment by terracoda** [comment]
@zepumph, I found another place where the m1/m2 mass1/mass 2 change needs to happen:

When the alert that fires when the Constant Size checkbox is checked, see screenshot. The alert content is correct when Constant size is unchecked. The alert content in the case of the Constant Size checkbox is dynamic. This may be the reason. There might be something connecting both Regular and Basics here?
<img width="435" alt="screen shot 2019-01-18 at 2 54 39 pm" src="https://user-images.githubusercontent.com/1902116/51391117-7f9f3b00-1b31-11e9-921d-96078042d54b.png">

**Comment by terracoda** [comment]
@zepumph, I was mistaken, the alert that actually has dynamic content (unchecked state) is correct, but the checked state which is not dynamic is incorrect. Perhaps it is because it is static that it is the same in both sims?

**Comment by zepumph** [comment]
I hope that there are no more version of m1 and m2 in GFLB. Please double check for me and review @terracoda.

**Comment by terracoda** [comment]
@zepumph, did you push your changes? 
I still see and hear "m1 and m2 set to same size." when toggling the Constant Size to a checked state. See a11y view and voice over:
<img width="874" alt="screen shot 2019-01-28 at 2 03 24 pm" src="https://user-images.githubusercontent.com/1902116/51838324-41aacf80-2306-11e9-838f-187fb601fed6.png">

<img width="603" alt="screen shot 2019-01-28 at 1 58 57 pm" src="https://user-images.githubusercontent.com/1902116/51838417-833b7a80-2306-11e9-9434-da9b2987da19.png">

And I think that is indeed the last spot!

**Comment by terracoda** [comment]
As I just said, I think you got everything except the _Constant-Size-checked_ alert.

The only other possible place where "m1" or "m2" might show up is in the Mass edge-case alerts where an increase in the mass of one sphere moves the opposite sphere left or right. These Mass edge-case alerts are not yet working in GFL:BASICS. Here is an example from GFL REGULAR for reference.

**Interaction:** As I increase the mass of m2, m1 gets pushed left.
<img width="731" alt="m1-being-pushed-left-by-increased-mass-of-m2" src="https://user-images.githubusercontent.com/1902116/51839695-39549380-230a-11e9-8bb9-cfa8a46e022a.png">

**Comment by zepumph** [comment]
fixed constant size checkbox alert above. I'll keep a look out for the mass alert edge cases. Ready to close?

**Comment by terracoda** [comment]
Looks good! Will re-open if I find anything, but I think we are good!
