### ISSUE TITLE
Update UI interaction alerts for the Distance checkbox

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#85]
Please update the alerts that describe the state change when the Distance checkbox is unchecked and checked:
- When unchecked replace: “Distance arrow removed.” with "Distance hidden."
- When checked replace “Distance arrow visible." with "Distance shown in kilometers."

Change also noted in design document.

**Comment by zepumph** [comment]
Implemented above.

**Comment by terracoda** [comment]
@zepumph, I have verified the new alert strings. Sounds great! Thanks. Closing issue.
