### ISSUE TITLE
Implement wording simplications for Gravity Force Lab:Basics

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#86]
@kathy-phet and @ariel-phet, I laid out side-by-side examples for wording simplifications between GFL Basics and GFL in the GFL Basics A11y Design Document. 

I have the following design questions regarding wording simplifications. Please answer the 4 questions, or let me know if I should request design time?

If you go to the design document to see the examples, please try to focus on the 4 questions and the yellow highlights.

**I need answers to the following questions:**
1. Can we use “force arrow” or “force arrows” in GFL Basics where we use “vector”, “force vector”, “vectors”, “force vectors” in Gravity Force Lab?
2. Could we simplify “force vector magnitude” to “strength of force” in the following phrase when describing the state of a mass sphere: 
    - “Strength of force on mass 1 by mass 2 is 33.4 Newtons.”
3. Can we (or is it correct to) simplify “magnitude” to “strength” in the following phrase when describing the state of the sim?:
    - “Currently, force on mass 1 by mass 2 is equal in strength and opposite in direction of force on mass 2 by mass 1.”
4. If my suggestion for 3 is not workable, do you have any idea on how to simplify this “equal and opposite” sentence in a way that might be easier for 10 year olds?

Questions are also here in the [Dynamic Descriptions section](https://docs.google.com/document/d/1HdDG9ds2MdbCb21l9qk3cI8yBQxK6-wBWNXC4Tloji8/edit#heading=h.cickaapr2neb) of the design document.

I have included visuals of the sims to help you see how the descriptions are being used. I have also highlighted in yellow the relevant strings/phrases in both the [Dynamic Descriptions section](https://docs.google.com/document/d/1HdDG9ds2MdbCb21l9qk3cI8yBQxK6-wBWNXC4Tloji8/edit#heading=h.cickaapr2neb) and the [Complex Interaction Alerts section](https://docs.google.com/document/d/1HdDG9ds2MdbCb21l9qk3cI8yBQxK6-wBWNXC4Tloji8/edit#heading=h.mgmn7olsqd39) to show exactly where/how this phrases are used in descriptions and alerts.

Thanks in advance for your help on this.

**Comment by terracoda** [comment]
@arouinfar, thanks for self-assigning! In retrospect I should have assigned to you first.

**Comment by ariel-phet** [comment]
@terracoda 

1. Force arrow is reasonable terminology

2. Strength is OK. Size might also work. Value would also be appropriate terminology. 

3. Again, I think this simplification would be OK.  I probably lean towards size or value more than strength.

**Comment by arouinfar** [comment]
> @arouinfar, thanks for self-assigning! In retrospect I should have assigned to you first.

No worries! I saw this issue pop up in my inbox, and self-assigned so I wouldn't forget about it. The tables were super handy for comparing the two sims too.

In general, I agree with @ariel-phet's https://github.com/phetsims/gravity-force-lab-basics/issues/86#issuecomment-454857724.

I slightly prefer "size" to "strength", but I'm not much of a fan of "value".

These are the phrases currently showing up in the descriptions:
* "Strength of force on mass 1 by mass 2"
* "force on mass 1 by mass 2 is equal in strength and opposite in direction"

Replacing "strength" with "size" sounds nice, but I think "value" would probably need some re-phrasing.

**Comment by terracoda** [comment]
@ariel-phet and @arouinfar thanks for the comments!

**Comment by zepumph** [comment]
@terracoda please review everything that won't be handled by #94. It should all be done at this point.

I did see one more usage of "vecors"

![image](https://user-images.githubusercontent.com/6856943/51780078-116df180-20b8-11e9-9bd7-6bdba4a85658.png)


It occurs from an alert that is triggered when you stop dragging a mass slider, but the position hasn't changed 

(note to self `regionForceClausePattern` from `vectorsSizeClausePattern` in `ISLCA11yStrings.js`)

Would you like me to change that too?

**Comment by terracoda** [comment]
@zepumph, I have to review the position alerts, including the one you mention above in https://github.com/phetsims/gravity-force-lab-basics/issues/86#issuecomment-457782990 which is triggered when there is a key press on a position slider, but the position does not change (e.g. situation: sphere is at edge, or against the other sphere). I'm not sure we will keep that alert, but if we do, the word "vectors" would have to be changed to "force arrows". So if straightforward, please go ahead and change that instance as well.

**However, please note** that we will be handling any needed changes to the position alerts in a separate issue (or issues) once I start my review. If it is not straight forward to update the word, you can wait until I review the position alerts.

**Comment by terracoda** [comment]
**In terms of the other simplifications you implemented all are good except one.** And I don't think I explicitly mentioned this one above (apologies).

The force alerts that happen when changing mass, still contain, "vectors" instead of "force arrows"
<img width="1056" alt="changing-mass-alert-not-simplified" src="https://user-images.githubusercontent.com/1902116/51842052-4f655280-2310-11e9-876c-a00723ab8574.png">

And also in the Mass edge-case alerts (not fully implemented yet):
<img width="850" alt="edge-case-mass-alerts-not-simplified" src="https://user-images.githubusercontent.com/1902116/51842745-df57cc00-2311-11e9-9113-897143cf44cf.png">

**Comment by zepumph** [comment]
I found another case, when you move the slider to the edge, and then end the drag, then START the drag again toward the edge. That no-op will now say "force arrows" instead of "vectors"

**Comment by zepumph** [comment]
And above is the fix for @terracoda's screenshots above. Note that there are two different strings that had to be changed, one each depending on whether the force arrows are showing. Back to you @terracoda.

**Comment by terracoda** [comment]
The alerts all look good.
However, I missed the mass 1, Blue Sphere and mass1, Red Sphere dynamic descriptions where "vector" should be "force arrow" (singular).
<img width="959" alt="screen shot 2019-02-02 at 7 59 57 pm" src="https://user-images.githubusercontent.com/1902116/52168087-bd9d8100-2725-11e9-93da-eb3915d01594.png">

**Comment by zepumph** [comment]
I thought the above will be covered by https://github.com/phetsims/gravity-force-lab-basics/issues/94. I'll see you over in that issue. Anything else here?

**Comment by terracoda** [comment]
Ok great. Closing!
