### ISSUE TITLE
Remove described qualitative size of sphere in mass spheres' dynamic descriptions

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#87]
@zepumph, in issue https://github.com/phetsims/gravity-force-lab/issues/128 qualitative size was correctly removed from the `aria-valuetext`, however, I would also like it removed from dynamic descriptions in the PDOM for both simulations, BASICS and REGULAR. 

I am adding screen shots for both sims, red lines strike out the size information that I would like removed.

**GFL BASICS**
<img width="1070" alt="remove-sise-mass-spheres" src="https://user-images.githubusercontent.com/1902116/51469191-13127f00-1d71-11e9-9355-41d51593d4a1.png">

**GFL REGULAR**
<img width="954" alt="gfl-regular-remove-size-from-dynamic-description" src="https://user-images.githubusercontent.com/1902116/51469449-a8157800-1d71-11e9-924b-0030dba68384.png">

**Note to self** (@terracoda) this change has already been noted in design document.

**Comment by terracoda** [comment]
@zepumph, because this change is the same for both sims, I think it might be an easy one to implement.

**Comment by zepumph** [comment]
Assigning to @terracoda to work on further. At our meeting we were not totally sure if we want to remove them in both, or just BASICS.

**Comment by terracoda** [comment]
@zepumph, yes, the actual described size of the spheres is not needed, and it has already been removed.

Only the comparative size is needed and that will be looked after in issue #96.

Closing this issue.
