### ISSUE TITLE
Adjust slider/spinbutton values and alerts to jump to latest value (prevent pile up of stale alerts)

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#89]
This sim will benefit from timing adjustments when reading out the slider values and spinbutton values. The adjustments should limit the number of values and alerts that pile up in the utterance queu when a person is using the keyboard and changing position or changing mass quickly.

I think we made similar adjustments in John Travoltage & Resistance in a Wire.

I think these are possible related issues which solved some untimely repetitive situations in John John Travoltage & Resistance in a Wire.
- https://github.com/phetsims/john-travoltage/issues/302
- https://github.com/phetsims/resistance-in-a-wire/issues/193#issuecomment-438050116

Can similar adjustments be made for this sim, and perhaps these changes could be generalized as a default for all sliders?

**Comment by zepumph** [comment]
Alerts like "Force arrows get bigger, forces now 21.4 ‪newtons‬"

We want to make sure these don't pile up. I'll take a look1

**Comment by zepumph** [comment]
This would be good to work on before interviews, marking priority as such.

**Comment by terracoda** [comment]
@zepumph, we can wait until after interviews to optimize slider  and alerts.

**Comment by terracoda** [comment]
@zepumph, if you can do this today, great! If this too hard to fix by end of day, I will let the interviewers know that the participant may need to go down.

**Comment by terracoda** [comment]
@zepumph, the piling up of alerts might only be happening with VoiceOver. It is very consistent in VoiceOver, but in interviews it has been less problematic.

I have a feeling, yours and @jessegreenberg work on optimizing the utterance queue might resolve this issue.

**Comment by jessegreenberg** [comment]
Using the new ValueChangeUtterance may help.

**Comment by terracoda** [comment]
@zepumph, alerts are no longer piling up.  I think this issue can be closed.
