### ISSUE TITLE
Sphere movement described when no movement occurs

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#91]
This issue is related to #90 and perhaps https://github.com/phetsims/gravity-force-lab/issues/135, too.

Earlier today I noticed this, and I accidentally deleted my issue without realizing it.

I noticed that movement was being described in the alert when movement was not not happening (see screen shot of a11y view). I am now having trouble reproducing this issue, though I was able to reproduce it a few hours ago by triggering the alert in the correct situation, then moving the spheres apart and then increasing mass again after the spheres were no longer right next to each other. The issue even occurred after hitting the reset button.

I thought I should log the issue even though I am not able to reproduce it now in case it pops up again.
<img width="486" alt="movement-described-when-no-movement" src="https://user-images.githubusercontent.com/1902116/51541195-83e09680-1e58-11e9-89f3-01aaf958f05b.png">

@zepumph, if you cannot reproduce the, I guess we can close it.

**Comment by zepumph** [comment]
From meeting, @terracoda will try reproduce.

**Comment by terracoda** [comment]
I cannot reproduce this issue.
Closing and will re-open if it pops up again.

**Comment by terracoda** [comment]
@

**Comment by terracoda** [comment]
@zepumph, I just heard this bug again, so I am re-opening.
It seems to only happen on Mass is changed first - after page load or after a reset with the Reset All button. Hopefully, that narrows things down.

**To reproduce:**
1. Load the sim
2. Tab to one of the Mass controls
3. Make mass 1 or mass 2 bigger

<img width="852" alt="screen shot 2019-02-25 at 11 12 57 am" src="https://user-images.githubusercontent.com/1902116/53332189-fc70c200-38f2-11e9-86e2-3dd74483ac17.png">
<img width="850" alt="screen shot 2019-02-25 at 11 13 37 am" src="https://user-images.githubusercontent.com/1902116/53332203-04306680-38f3-11e9-82c9-fd607baec277.png">

**Comment by terracoda** [comment]
Adding for clarity, this bug does not seem to happen if the position of a either mass sphere is changed before the mass of a mass sphere is change.

**Comment by terracoda** [comment]
@zepumph, this bug seems to be gone. 
I started changing mass after page load and I did not hear the bug any more.
