### ISSUE TITLE
new sonification version for interviews

### ISSUE THREAD

**Issue by zepumph** [phetsims/gravity-force-lab-basics#97]
we need a new sonification wrapper for interviews starting tomorrow.

**Comment by zepumph** [comment]
Here is the current sound design:

https://phet-dev.colorado.edu/html/phet-io-wrapper-sonification/1.0.0-dev.101/phet-io-wrapper-sonification/gravity-force-lab-basics/html/gravity-force-lab-basics-sonification.html?sonificationFile=sonificationOptions&massSound=0&forceSound=3&massBoundaryLimitSound=2&accessibility


Taken from https://phet-dev.colorado.edu/html/phet-io-wrapper-sonification/1.0.0-dev.101/phet-io-wrapper-sonification/sonification.html

Let me know if you need anything. I will see you tonight.

**Comment by terracoda** [comment]
@zepumph, these are good for today's interview, rescheduled from last Thursday.

**Comment by zepumph** [comment]
see #104 for latest.
