### ISSUE TITLE
Still hear "Vectors" in force alert on last stop

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#98]
Creating an issue for this straggling occurrence of "vectors". It seems kind of persistent.

It seems to only happen in the force alert when a sphere reaches the last stop.
<img width="621" alt="screen shot 2019-02-20 at 7 31 02 am" src="https://user-images.githubusercontent.com/1902116/53071124-92ff4680-34e1-11e9-9b18-96e6632139cb.png">
<img width="618" alt="screen shot 2019-02-20 at 7 26 33 am" src="https://user-images.githubusercontent.com/1902116/53071175-bfb35e00-34e1-11e9-99f5-6ef72c57b18f.png">

**Comment by terracoda** [comment]
This issue was original listed in issue #88.

**Comment by terracoda** [comment]
@zepumph, I don't think this gets in the way too much. Please fix if there is time after the distance issues are implemented.

**Comment by zepumph** [comment]
Ugh! Sorry for your patience, I think this is the last one. I looked through all usages of "Vector" in the common ISLC code and didn't see any more. How about that?

**Comment by terracoda** [comment]
No apologies necessary. It was a slippery fish! I think you finally hooked it.
