### ISSUE TITLE
Optimize visual movement when a mass change causes sphere movement

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#99]
The edge case alerts were verified in #90, but @zepumph mentioned there is some work to optimize when and how the spheres move in the visual sim. Their movement is somewhat restricted by the snap-to behavior of the slider.

This sometimes creates some visual inconsistencies with the alerts that say it a mass moved when it visually didn't or vice-versa. 

This might be a big issue to tackle.

**Comment by terracoda** [comment]
The alerts for the edge cases (described movement caused by a mass change) work correctly on mass changes.

@zepumph, this issue is purely about visuals. Sometime there's movement and sometimes not. I am not sure what priority I should put on this issue.

**Comment by zepumph** [comment]
@terracoda and I think that this small discrepancy is fine for now. It's an issue with the visual design and how it used the snap-to locations. In this case we think that the the descriptions are actually more correct, although it doesn't align with the visual display. Closing for now, and we can revisit this if we find that this is an issue in interviews with users using auditory descriptions and the visual display.
